### ISSUE TITLE
Support running GraphScope on macOS

### ISSUE THREAD

**Issue by yecol** [alibaba/GraphScope#1]
**Is your feature request related to a problem? Please describe.**
- When running the demo on macOS with minikube/docker-desktop, it occurs error due to a known issue about exposing address.
- learning feature doesn't support yet on macOS.

**Describe the solution you'd like**
- make it fully support on macOS.

**Describe alternatives you've considered**

**Additional context**

**Comment by sighingnow** [comment]
The status of MacOS support:

+ minikube: works
+ kubernetes in Docker Desktop: works after the "load-balancer" PR (https://github.com/alibaba/GraphScope/pull/24)
+ the gremlin endpoint part: still in-progress by @shirly121.

There will be a CI workflow for MacOS later after everything being fixed.
