### ISSUE TITLE
Print logs after session failed.

### ISSUE THREAD

**Issue by siyuan0322** [alibaba/GraphScope#10]
**Is your feature request related to a problem? Please describe.**
Session has a param called `show_log` which controls whether print backend logs to stdout / stderr, which is great. But when we run a session with `show_log=False` since we don't want to be distracted by logs, and occasionally session launched failed, we can't get much useful information about why it failed and how to fix it, usually we need to rerun the session with `show_log=True`.

**Describe the solution you'd like**
Print logs when session failed, even when `show_log=False`.

**Comment by yecol** [comment]
As we discussed, stderr should stream to client when the session launching failed. This should be fixed when addressing the issue #7 .
