### ISSUE TITLE
replace storage impl

### ISSUE THREAD

**Issue by tianliplus** [alibaba/GraphScope#1048]

**Comment by yecol** [comment]
Hi @tianliplus Could you give some detailed descriptions about this issue? To help the community get more context. e.g., background, target, or why...

**Comment by tianliplus** [comment]
The implementaion of the read-related interfaces of groot storage engine in current version will copy all data into a vector, and then return vector as iterator to the caller. While "return vector as iterator" is easy to implement, it involves unnecessary data copy and may cause error. For example, if the return data are huge, process may crash since system memory is not enough to hold all of the data. So we use a zero-copy implementation to replace the old version in this PR to fix this problem.
