### ISSUE TITLE
[BUG] Figure out the required protobuf version for the graphscope python package.

### ISSUE THREAD

**Issue by sighingnow** [alibaba/GraphScope#106]
**Describe the bug**

GraphScope will raise if the existing protobuf package version is too low:

```
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
```

That is because we didn't specify the version range of protobuf in `requirements.txt`. That is bad when raising during `import graphscope`, and without a clear error message to tell the users how to fix that.

**Expected behavior**

Declare which version that we could accept in `requirements.txt`.

**Additional context**

N/A.

**Comment by lidongze0629** [comment]
protobuf>=v3.12.0
