### ISSUE TITLE
Respect the `--user` option when pip install.

### ISSUE THREAD

**Issue by siyuan0322** [alibaba/GraphScope#1069]
Make experiment to mock a typical user behavior who have no root permission and wants to install graphscope by `pip3 install graphscope --user`. Make sure that all the stuffs and logs doesn't goes outside `$HOME`, even better, not outside of `$home/.local`.

Check the permission of the default log location, if the default location can't be used, then prompt user to provide one.

**Comment by yecol** [comment]
I think weibin has a commit merged about the log location, 
@siyuan0322 Could you test and verify your proposal?

**Comment by acezen** [comment]
@siyuan0322  prompting user to provide a log location during runtime seems wired.  GraphScope would chose to output log to `$HOME/.local/log/graphscope` if user does not has write  permission  to default location (`/var/log/graphscope`)

**Comment by siyuan0322** [comment]
Closed as it worked as expected.
