### ISSUE TITLE
[BUG Gaia/Engine]  The engine gets stuck after repeating certain tasks multiple times 

### ISSUE THREAD

**Issue by BingqingLyu** [alibaba/GraphScope#1073]
**Describe the bug**
As titled

**To Reproduce**
1. Go to the branch 'gaia-x'
2. 'cd research/engine/pegasus/pegasus'
3. Run 'cargo test -- modern_graph_filter_test_five_times'

**Expected behavior**
The test seems to be get stuck

**Screenshots**
![image](https://user-images.githubusercontent.com/28559306/143853231-15ce059a-30fd-473d-870b-e9c20b633f0f.png)

**Additional context**
Another similar case is 'modern_graph_filter_test_twice', which seems like to be output expected results. The bug occurs occasionally.

**Comment by longbinlai** [comment]
The task looks like this: 
```
move |input, output| {
            input
                .input_from(src)?
                .repartition(|x| Ok(*x as u64))
                .flat_map(move |x| Ok(MAP.get(&x).unwrap().1.iter().cloned()))?
                .repartition(|x| Ok(*x as u64))
                .flat_map(move |x| Ok(MAP.get(&x).unwrap().0.iter().cloned()))?
                .repartition(|x| Ok(*x as u64))
                .filter(|x| Ok(*x == 5))?
                .repartition(|x| Ok(*x as u64))
                .flat_map(|x|Ok(MAP.get(&x).unwrap().1.iter().cloned()))?
                .sink_into(output)
        }
```
Note that without the **LAST** `repartition(|x| Ok(*x as u64))`, the case is fine.

**Comment by longbinlai** [comment]
More input: While running the above task in the `release` mode, it will block casually even just running once. @bmmcq
