### ISSUE TITLE
[BUG] verify compatibility of Python 3.6 (NetworkX)

### ISSUE THREAD

**Issue by yecol** [alibaba/GraphScope#1125]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - GraphScope version: [e.g., v0.1, v0.2.2, master]
 - OS: [e.g. MacOS, Linux]
 - Version [e.g. 10.15]
 - Kubernetes Version [e.g., 1.19]

**Additional context**

**Comment by acezen** [comment]
as a note, networkx2.6 would not support python3.6 any more.
https://networkx.org/documentation/stable/release/release_2.6.html
