### ISSUE TITLE
Deprecate the codepath for minikube (if kind workers better for Mac) to simply our environment prepration steps.

### ISSUE THREAD

**Issue by sighingnow** [alibaba/GraphScope#114]
**Is your feature request related to a problem? Please describe.**

Currently the "Prerequisites" section in README is a bit confusion, e.g., do we advertise that kind is OK as well for Mac? AFAIK we haven't test it yet.

And the codepath for minikube to get the service endpoint on Mac, as well as the `k8s_minikube_vm_driver` parameter in `graphscope.session` is a bit hacky.

**Describe the solution you'd like**

If kind works better we could deprecate the support for minikube and use kind everywhere in our codebase and documentation.

**Additional context**

N/A

**Comment by acezen** [comment]
the 'kind' is not very OK for Mac, it need some hack tool like [docker-tuntap-osx](https://github.com/AlmirKadric-Published/docker-tuntap-osx) and [MetalLB](https://metallb.universe.tf/) to  Load Balancing on Mac.
