### ISSUE TITLE
Meaningful error message when shared memory is not enough.

### ISSUE THREAD

**Issue by siyuan0322** [alibaba/GraphScope#1172]
When shared memory is not enough to load a graph (This is common when running graphscope in docker, after we release the standalone deployment support, as the default configuration doesn't contains shared memory size), the `_Seal` method will fail.

Consider give it a meaningful error message. Also reported in #1142.

Another thing we could do is add tips about running graphscope in docker container. (--shm-size)
Also make sure this also works on other [Container Runtimes](https://kubernetes.io/docs/setup/production-environment/container-runtimes/)

**Comment by sighingnow** [comment]
Will  be fixed in vineyard.

**Comment by siyuan0322** [comment]
OK~ I'll take the tips part.

**Comment by sighingnow** [comment]
Fixed in vineyard.
