### ISSUE TITLE
hdfs 读取异常

### ISSUE THREAD

**Issue by sighingnow** [alibaba/GraphScope#1183]
### Discussed in https://github.com/alibaba/GraphScope/discussions/1181

<div type='discussions-op-text'>

<sup>Originally posted by **inurfuture** December 17, 2021</sup>
![image](https://user-images.githubusercontent.com/42594720/146478606-20539a8e-fd1b-4898-ac55-1eb61f1bc49c.png)
异常信息如上，参考文档中的载图-loader变种里的方法（ds3 = Loader("hdfs:///datafiles/group.e", host='localhost', port='9000', extra_conf={'conf1': 'value1'})）</div>

**Comment by inurfuture** [comment]
@sighingnow 请问一下这个bug有计划什么时候修复吗？

**Comment by sighingnow** [comment]
> 

Hopefully be fixed in our next release v0.10, and will be cut in next week.
