### ISSUE TITLE
算法能否支持字符串id

### ISSUE THREAD

**Issue by inurfuture** [alibaba/GraphScope#1184]
![image](https://user-images.githubusercontent.com/42594720/146484435-350a1458-887e-4702-b5eb-c16e51983681.png)
在载图的文档中看到，id是支持为字符串的，只是会影响存储和算法性能

![image](https://user-images.githubusercontent.com/42594720/146484328-ec3510ac-9c93-426c-8869-cf3854c821ba.png)
根据api文档中描述，例如sssp算法的入参src类型为int

请问sssp算法是否能支持字符串id呢，对性能的影响会有多大呢

**Comment by sighingnow** [comment]
> 请问sssp算法是否能支持字符串id呢

`src` definitely could be a `str` if the oid type of the graph is string.

> 对性能的影响会有多大呢

For built-in app `sssp`, the impact on performance should be ignoreable.

**Comment by sighingnow** [comment]
And yes, we should update the document to reflect the truth that here `str` is ok as well.
