### ISSUE TITLE
SSSP documentation  needs some updates.

### ISSUE THREAD

**Issue by siyuan0322** [alibaba/GraphScope#1197]
The SSSP Algorithm supports pass a value typed `str` as source id, when the graph's origin ID type is `str`. This is not reflected in the documents neither in the comments.

Actually,  all algorithms that can pass a  parameter which  type should be consistent with the ID type of graph  have this problem.

Reported in #1185

**Comment by acezen** [comment]
we should describe that this SSSP is computing `path lengh`, not `path` in document too
