### ISSUE TITLE
[BUG] AnalyticalEngineInternalError

### ISSUE THREAD

**Issue by inurfuture** [alibaba/GraphScope#1217]
**Describe the bug**
AnalyticalEngineInternalError

**To Reproduce**

> AnalyticalEngineInternalError: "'/work/analytical_engine/core/server/dispatcher.cc:72: operator() -> Unmatched std::exception detected: [json.exception.type_error.305] cannot use operator[] with a string argument with null\\n0x0000000000464EEE: (SP:0x00007F12B5EF03F0) (void boost::throw_exception<boost::bad_function_call>(boost::bad_function_call const&) + 0x5B3)\\n0x0000000000534719: (SP:0x00007F12B5EF0690) (gs::Dispatcher::publisherLoop() + 0x3B9)\\n0x00007F12C5EEE8D0: (SP:0x00007F12B5EF0840) (execute_native_thread_routine + 0x10)\\n0x00007F12BC3E2E25: (SP:0x00007F12B5EF0860) (start_thread + 0xC5)\\n0x00007F12BADC534D: (SP:0x00007F12B5EF0900) (clone + 0x6D)\\n\\n/work/analytical_engine/core/server/dispatcher.cc:72: operator() -> Unmatched std::exception detected: [json.exception.type_error.305] cannot use operator[] with a string argument with null\\n0x0000000000464EEE: (SP:0x00007F5163FF64C0) (void boost::throw_exception<boost::bad_function_call>(boost::bad_function_call const&) + 0x5B3)\\n0x0000000000533AE2: (SP:0x00007F5163FF6760) (gs::Dispatcher::subscriberLoop() + 0xB2)\\n0x00007F5177BAF8D0: (SP:0x00007F5163FF6840) (execute_native_thread_routine + 0x10)\\n0x00007F516E0A3E25: (SP:0x00007F5163FF6860) (start_thread + 0xC5)\\n0x00007F516CA8634D: (SP:0x00007F5163FF6900) (clone + 0x6D)\\n\\n'"

1.读取单文件4.2G 5400w条边(字符串id)异常
2.读取单文件255M 450w条边(字符传id)耗时90s

**Screenshots**
![image](https://user-images.githubusercontent.com/42594720/147076311-19d5833c-bf61-4fc5-b344-e3767fa582e4.png)

**Environment (please complete the following information):**
 - GraphScope version: [master]
 - OS: [Linux]
单机部署 服务器配置：256G内存,32C

**Comment by yecol** [comment]
Hi @inurfuture
Could you add me as a WeChat friend and we can help you on this case?  
our wechat account: graphscope

**Comment by siyuan0322** [comment]
Hi, I did some experiment with a generated file (5000w lines, where the vertex ID is a string with length 32) but cannot reproduce the error.

Could you provide more details such as the format of your input file and some lines of example?

**Comment by lidongze0629** [comment]
We will feedback the result after testing on the dataset provided by @inurfuture.

**Comment by siyuan0322** [comment]
Closed as stale.
