### ISSUE TITLE
[BUG] UDF App can't compile on graphs with string as OID.

### ISSUE THREAD

**Issue by siyuan0322** [alibaba/GraphScope#1266]
**Describe the bug**
As titled.

**To Reproduce**
```python
import graphscope

from graphscope.analytical.udf import pregel
from graphscope.framework.app import AppAssets

# decorator, and assign the types for vertex data, message data.
@pregel(vd_type="double", md_type="double")
class SSSP_Pregel(AppAssets):
    @staticmethod
    def Init(v, context):
        v.set_value(1000000000.0)
    @staticmethod
    def Compute(messages, v, context):
        src_id = context.get_config(b"src")
        cur_dist = v.value()
        new_dist = 1000000000.0
        if v.id() == src_id:
            new_dist = 0
        for message in messages:
            new_dist = min(message, new_dist)
        if new_dist < cur_dist:
            v.set_value(new_dist)
            for e_label_id in range(context.edge_label_num()):
                edges = v.outgoing_edges(e_label_id)
                for e in edges:
                    v.send(e.vertex(), new_dist + e.get_int(2))
        v.vote_to_halt()
    @staticmethod
    def Combine(messages):
        ret = 1000000000.0
        for m in messages:
            ret = min(ret, m)
        return ret


graphscope.set_option(show_log = True)

sess = graphscope.session()
graph = sess.g(oid_type='string', directed=True, generate_eid=True)
my_app = SSSP_Pregel()
ret = my_app(graph)
```

**Comment by siyuan0322** [comment]
Thanks @wuyueandrew for reporting this issue.
@lidongze0629 Could you please take some time to look into this issue? 🌹

**Comment by wuyueandrew** [comment]
maybe there is another reason, default attribute `k8s_coordinator_mem=4Gi` cannot compile algo on my machine, so i try to change this attr to `8Gi` and it's fixed, u can take it to consider. 
version:0.9.1
i use `/usr/bin/make -j4` to make the error happened again. 
Compiler shows 
`[ 50%] Building CXX object CMakeFiles/9350aad69a34b592fae103c8ccae7f7d72f52191625b9573dc3214803bc38569.dir/home/graphscope/.local/lib/python3.8/site-packages/graphscope.runtime/include/graphscope/frame/app_frame.cc.o
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [CMakeFiles/9350aad69a34b592fae103c8ccae7f7d72f52191625b9573dc3214803bc38569.dir/build.make:76: CMakeFiles/9350aad69a34b592fae103c8ccae7f7d72f52191625b9573dc3214803bc38569.dir/home/graphscope/.local/lib/python3.8/site-packages/graphscope.runtime/include/graphscope/frame/app_frame.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/9350aad69a34b592fae103c8ccae7f7d72f52191625b9573dc3214803bc38569.dir/all] Error 2
make: *** [Makefile:91: all] Error 2`
