### ISSUE TITLE
string indices must be intergers 

### ISSUE THREAD

**Issue by banbsyip** [alibaba/GraphScope#1273]
sub_graph = interactive.subgraph("g.V().has('year', inside(2014, 2020)).outE('cites')")
当我运行上行代码时出现错误‘’string indices must be intergers ‘’
请问如何解决

![WechatIMG38](https://user-images.githubusercontent.com/18277076/149490548-396bd2be-9a6d-4846-a927-efa4a135df04.jpeg)

- [ ] #

**Comment by sighingnow** [comment]
Hi @banbsyip,

Thanks for reporting the issue! Could you please provide more details about the setting ? e.g., the version of graphscope that you are working with.

**Comment by banbsyip** [comment]
@sighingnow  the data down from the ogbn-mag,the version of graphscope is 0.8,i think it maybe caused by the property default set when I run the add_vertices()

**Comment by banbsyip** [comment]
@sighingnow when I add properties=[('year','int')] to the paper's line,it still this error.

**Comment by siyuan0322** [comment]
> @sighingnow the data down from the ogbn-mag,the version of graphscope is 0.8,i think it maybe caused by the property default set when I run the add_vertices()

Hi, this error is because the error format returned by the interactive engine does not conform to the parsing format of Gremlin-Python. Can you upgrade to the 0.10.0 image and try again on the client side? This problem may be solved in the new version

**Comment by sighingnow** [comment]
> @sighingnow when I add properties=[('year','int')] to the paper's line,it still this error.

Have you tried to upgrade your `gremlin_python` to the latest version? that might be helpful.

**Comment by banbsyip** [comment]
> > @sighingnow the data down from the ogbn-mag,the version of graphscope is 0.8,i think it maybe caused by the property default set when I run the add_vertices()
> 
> Hi, this error is because the error format returned by the interactive engine does not conform to the parsing format of Gremlin-Python. Can you upgrade to the 0.10.0 image and try again on the client side? This problem may be solved in the new version

after i  upgrade to the 0.10.0 image，the problem has resolved, but another problem occured,
the code is : ret1 = graphscope.kcore(simple_g, k=5)
AttributeError: module 'graphscope' has no attribute 'kcore'

**Comment by siyuan0322** [comment]
Happy to know that~ I'll close this issue for now, and if you have any other questions, feel free to reopen this or open another thread~

**Comment by banbsyip** [comment]
> > @sighingnow the data down from the ogbn-mag,the version of graphscope is 0.8,i think it maybe caused by the property default set when I run the add_vertices()
> 
> Hi, this error is because the error format returned by the interactive engine does not conform to the parsing format of Gremlin-Python. Can you upgrade to the 0.10.0 image and try again on the client side? This problem may be solved in the new version

please change the code  'ret1 = graphscope.kcore(simple_g, k=5)' to 'ret1 = graphscope.k_core(simple_g, k=5)' on the https://graphscope.io/docs/zh/getting_started.html if the website managed by yours

**Comment by sighingnow** [comment]
> 

Thank you @banbsyip.

@lidongze0629 could you please fix the `kcore` related typos in documentation in your PR? Thanks!
