### ISSUE TITLE
[BUG] The document of `graphscope.graphlearn` is not clear

### ISSUE THREAD

**Issue by jmd300** [alibaba/GraphScope#1274]
https://nbviewer.org/github/alibaba/GraphScope/blob/main/tutorials/zh/7_unsupervised_learning_with_graphsage.ipynb
![image](https://user-images.githubusercontent.com/38930973/149502351-bf68038c-201f-431c-a4d3-efd3a6da7dd7.png)
你这参数都是啥，为啥写不清楚呢？
# launch a learning engine.
lg = graphscope.graphlearn(
    graph,
    nodes=[("protein", paper_features)],
    edges=[("protein", "link", "protein")],
    gen_labels=[
        ("train", "protein", 100, (0, 100)), # ？？？
    ],
)

**Comment by acezen** [comment]
Thanks for reporting the issue!  The document of the `graphscope.graphlearn` is not clear, we will improve it ASAP.
