### ISSUE TITLE
can't pip install graphscope

### ISSUE THREAD

**Issue by banbsyip** [alibaba/GraphScope#1284]
when i pip the graphscope in my anaconda,it failed,python version is 3.8.8,pip version is  21.0.1
the error detail is as follow:

![图片](https://user-images.githubusercontent.com/18277076/150079758-b752d357-07c9-4545-9ef8-898a97cf4639.png)

**Comment by sighingnow** [comment]
Hi @banbsyip ,

Currently Windows is not supported. You could try graphscope in [WSL](https://docs.microsoft.com/en-us/windows/wsl/install).

**Comment by sighingnow** [comment]
The error message could be improved to deliver users a hint.

**Comment by banbsyip** [comment]
@sighingnow ok,thanks
