### ISSUE TITLE
The default memory (4G) for coordinator may not enough to build an application

### ISSUE THREAD

**Issue by siyuan0322** [alibaba/GraphScope#1286]
Could we reduce the dependency of `app_frame` to make it less memory-intensive?

**Comment by sighingnow** [comment]
Related to #1266.

It's time to reduce the intra-dependency complexity between our modules...

**Comment by siyuan0322** [comment]
And speed up the compilation of UDF apps.

**Comment by yecol** [comment]
The app build process has moved to engine worker.
