### ISSUE TITLE
Upgrade arrow version in basic image.

### ISSUE THREAD

**Issue by siyuan0322** [alibaba/GraphScope#1311]
Arrow have released 7.0.0 stable with a lot of new features.
We are still using 1.0.1 in our runtime image; it'll be appreciated if we can upgrade to the newer version.

**Comment by yecol** [comment]
When you update the runtime/basic image, could you also add dependencies like `go` and others?

**Comment by siyuan0322** [comment]
Closed by #1462

**Comment by sighingnow** [comment]
See also https://github.com/alibaba/GraphScope/pull/1476.
