### ISSUE TITLE
Project fragment: select a set of labels and properties to project

### ISSUE THREAD

**Issue by sighingnow** [alibaba/GraphScope#134]
**Is your feature request related to a problem? Please describe.**

We have `Graph.project_to_simple` which select an edge + a vertice and a property to project a property fragment as a simple fragment. But we cannot obtain a subset of the original graph as a new property graph. The implementation should be straightforward.

**Describe the solution you'd like**

Implements `Graph.project(elabels: Map[string, List[string]], vlabels: Map[string, List[string]]) -> Graph`.

- [x] Use `session.g()` to return a `Graph`.
- [x] Delete `remove` related syntax and docs.
- [ ] Unify `project` and `project_to_simple`
- [ ] Make `add_column` works by checking individual vertex label's signature, not by graph object id.

**Comment by yecol** [comment]
Maybe take gremlin `subgraph` as reference.

**Comment by siyuan0322** [comment]
* Use `session.g()` to return a `Graph`.
* Delete `remove` related syntax and docs.
* unify `project`

**Comment by siyuan0322** [comment]
The method `project` will project a set of vertex labels, along with a set of properties and a set of edge labels, with a set of properties, to a sub property graph.

```python
class Graph:
    def project(
        self,
        edges: Mapping[str, Union[List[str], None]],
        vertices: Mapping[str, Union[List[str], None]] = None
    ):
        pass
```

The parameter definition means it's a `dict`, the key is the label name, the value is a `list` of `str`, which is the properties name. Specifically, if the value is None, it means select all properties.

If the parameter `vertices` is None, it means implicitly select all vertex labels referred by the edges, with all properties.

A graph that produced by `project` should just like a normal property graph, and can be projected further.

When a graph is used to query an app, it will implicitly trigger a `project_to_simple` operation, iff the property graph can be converted to a projected fragment.
```python
graph = load_modern_graph()
sub_graph = graph.project(edges={"knows": ["weight"]}, vertices={"person": []})
ret = sssp(sub_graph, src=6)
```

User can `AddColumn` to a graph if the target vertex's signature is same as the vertex's signature when the context is computed.

```python
graph.add_column(ret, select={'xxx': 'xxx'})
```
