### ISSUE TITLE
Each coordinator create its own etcd cluster，how about use unified etcd cluster for all coordinators

### ISSUE THREAD

**Issue by wuyueandrew** [alibaba/GraphScope#1343]
**Is your feature request related to a problem? Please describe.**
Each coordinator create its own etcd cluster, its not efficient.
**Describe the solution you'd like**
Supply a arg(etcd cluster url) to coordinator, and all coordinators can use a unified resident etcd cluster .

**Comment by wuyueandrew** [comment]
英语太难了，提供一个coordinator的启动参数，创建coordinator时指定一个常驻的etcd集群，这样不需要每次启动session都创建一个etcd浪费资源了。

**Comment by sighingnow** [comment]
这个可以支持。

**Comment by wuyueandrew** [comment]
coordinator这块我比较熟，要不分给我试试

**Comment by sighingnow** [comment]
> coordinator这块我比较熟，要不分给我试试

可以的，赞 👍 ，你提交PR就可以
