### ISSUE TITLE
consider about extend alternative log protocols

### ISSUE THREAD

**Issue by wuyueandrew** [alibaba/GraphScope#1344]
**Is your feature request related to a problem? Please describe.**
for now，gs prints logs to stdout. consider a scene : scheduler starts several session to run tasks every day, and if some tasks are failed and sessions closed, admin cannot check the log anymore.

**Describe the solution you'd like**
A solution of mine is start a proxy pod to collect coordinators log,  and send it to a server which persists log to file, i think it's not 
elegant. A Better solution is supply some builtin protocols,such as tcp or remote file system.

**Comment by yecol** [comment]
Thansk for your feedback!
We use stdout/stderr, since it allows users to stream the logs to 3rd-party logging service, e.g., st or fluentd. In addition, it is also a recommended way for logging on K8s.  

In your case, `kubectl logs –previous` may help.

further ref: https://sematext.com/guides/kubernetes-logging/

**Comment by wuyueandrew** [comment]
> Thansk for your feedback! We use stdout/stderr, since it allows users to stream the logs to 3rd-party logging service, e.g., st or fluentd. In addition, it is also a recommended way for logging on K8s.
> 
> In your case, `kubectl logs –previous` may help.
> 
> further ref: https://sematext.com/guides/kubernetes-logging/

thanks your suggest， previous option is alternative，it can deal with part of my trouble

**Comment by wuyueandrew** [comment]
> Thansk for your feedback! We use stdout/stderr, since it allows users to stream the logs to 3rd-party logging service, e.g., st or fluentd. In addition, it is also a recommended way for logging on K8s.
> 
> In your case, `kubectl logs –previous` may help.
> 
> further ref: https://sematext.com/guides/kubernetes-logging/

thanks your suggest， previous option is alternative，it can deal with part of my trouble
