### ISSUE TITLE
Pre-compile common apps/graphs in the distributed docker image

### ISSUE THREAD

**Issue by sighingnow** [alibaba/GraphScope#137]
**Is your feature request related to a problem? Please describe.**

To bump up the time-to-response when loading graphs, run analytical apps, etc.

**Additional context**

The common used apps/graphs combinations should be a small set.

**Comment by siyuan0322** [comment]
arrow fragment: <int64_t, int64_t> <string, int64_t>
app: combinations between <int64, double, int32, float, string>
