### ISSUE TITLE
Move the jar parsing logic from client to coordinator.

### ISSUE THREAD

**Issue by siyuan0322** [alibaba/GraphScope#1384]
Currently in client we use java to [parse](https://github.com/alibaba/GraphScope/blob/c3903d5ee875150ceaec4b6d5a5db56562c20a53/python/graphscope/analytical/app/java_app.py#L61) some meta from the jar,
Ideally this process should be done in coordinator so as to

1. Remove the java dependency of client,
2. Enable user to upload jar to remote server.

**Comment by zhanglei1949** [comment]
1. Agreed
2. Already available https://github.com/alibaba/GraphScope/blob/main/python/graphscope/client/session.py#L1272
