### ISSUE TITLE
Compile and run GraphScope locally (without kubernetes)

### ISSUE THREAD

**Issue by lidongze0629** [alibaba/GraphScope#139]

**Comment by yecol** [comment]
You may want to work on the branch: dev/local

**Comment by yecol** [comment]
Let's support ubuntu-20 as start.

**Comment by varinic** [comment]
## Work Progress:
1. Complete a script to install dependencies of GraphScope on ubuntu-20.
2. Complete a script to compile GAE, GIE and GLE locally.
3. Run GAE demo locally.
## TODO List:
1. Add code to support local connection to GIE and run GIE demo.
2. The work of GLE is the same as above.
