### ISSUE TITLE
[BUG] The download of data set could fail, and retry is not supported

### ISSUE THREAD

**Issue by sighingnow** [alibaba/GraphScope#1391]
**Describe the bug**

The download of data set could fail: https://github.com/alibaba/GraphScope/runs/5640280386?check_suite_focus=true

We need at least add support for "retry" in the download part, and add an optional `graphscope.set_option(dataset_download_retries)` to allow users to configure the behaviour.

The default value could be `3`.

**Additional context**

**Comment by yecol** [comment]
ref: https://github.com/urllib3/urllib3/blob/main/src/urllib3/util/retry.py
