### ISSUE TITLE
[BUG] fix slack invitation link

### ISSUE THREAD

**Issue by wenyuanyu** [alibaba/GraphScope#140]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/16228013/107142608-3e259680-696b-11eb-98e8-a492fed7a2e9.png)

**Environment (please complete the following information):**
 - GraphScope version: [e.g., v0.1, v0.2.2, master]
 - OS: [e.g. MacOS, Linux]
 - Version [e.g. 10.15]
 - Kubernetes Version [e.g., 1.19]

**Additional context**

**Comment by yecol** [comment]
Thanks for reporting!
a new invitation link is generated: 
https://join.slack.com/t/graphscope/shared_invite/zt-m06868qb-dyZvIm6aQrxHVrQ3n8INeg

Could you update the record of 
slack.graphscope.io 
or
slack.graphscope.app ?

**Comment by wenyuanyu** [comment]
> Thanks for reporting!
> a new invitation link is generated:
> https://join.slack.com/t/graphscope/shared_invite/zt-m06868qb-dyZvIm6aQrxHVrQ3n8INeg
> 
> Could you update the record of
> slack.graphscope.io
> or
> slack.graphscope.app ?

maybe we can use slackin (https://github.com/rauchg/slackin) and host it on aliyun? (https://serverless.aliyun.com/)

**Comment by sighingnow** [comment]
I think this issue in relative high priority.

**Comment by sighingnow** [comment]
Unfortunately slackin won't work anymore.. https://github.com/rauchg/slackin/issues/417 https://github.com/rauchg/slackin/issues/417

**Comment by yecol** [comment]
fixed manually.
