### ISSUE TITLE
A better way to show client version is not compatible 

### ISSUE THREAD

**Issue by wuyueandrew** [alibaba/GraphScope#1435]
**Is your feature request related to a problem? Please describe.**

when client version is not compatible , server only print a log like:
2022-03-31 18:24:39,217 [WARNING][coordinator:259]: Version between client and server is inconsistent: 0.9.0 vs 0.11.0
and there is no feedback for client.

**Describe the solution you'd like**

maybe  throw a exception when  client create not compatible session.

**Describe alternatives you've considered**

**Additional context**

**Comment by wuyueandrew** [comment]
创建连接的时候没有异常，然后进一步操作的时候会报rpc请求无法反序列化。

**Comment by wuyueandrew** [comment]
Maybe there is a slution:
1.Client cannot create coordinator which not compatible to it's version.
2.Coordinator throws an Exception when  a not compatible client connect to it, and then the client throws it to user.

**Comment by wuyueandrew** [comment]
If my solution is confirmed, maybe i can fix it, its not complicated.

**Comment by yecol** [comment]
Thanks for your bug reporting and the upcoming PR~ :)
Looking forward to it!
