### ISSUE TITLE
训练时目前只用到一个cpu核？不能配置多核训练？

### ISSUE THREAD

**Issue by bookug** [alibaba/GraphScope#1437]
在训练时发现cpu占有率只有130%，目前是不支持多核训练么？

**Comment by sighingnow** [comment]
@xiaoming-qxm @baoleai,

Could you folks take a look at this issue and if possible, give some guidence to users?

Thanks!

**Comment by baoleai** [comment]
This issue is a duplicate of the one in Graph-Learn https://github.com/alibaba/graph-learn/issues/185

**Comment by sighingnow** [comment]
Thanks @baoleai ❤️ 

Close as answered in https://github.com/alibaba/graph-learn/issues/185
