### ISSUE TITLE
0.12.0版本本地执行示例教程报错

### ISSUE THREAD

**Issue by czl753951** [alibaba/GraphScope#1444]
![487411-2c67b550bd642536919d5729a88f6d7e](https://user-images.githubusercontent.com/46732720/161436498-f3db3fba-5cff-432c-96ee-1e754ec59280.jpg)

**Comment by sighingnow** [comment]
If you are trying graphscope inside docker, please specify enough shared memory argument like

```
docker run --rm -it --shm-size=8Gi ......
```

**Comment by czl753951** [comment]
OK

**Comment by sighingnow** [comment]
Close as resolved.
