### ISSUE TITLE
[NetworkX] Improve the report performance with cache strategy

### ISSUE THREAD

**Issue by acezen** [alibaba/GraphScope#1448]
The report methods like `nodes` of graphscope.nx fetch the node attribute and neighbors one after another and it's too slow.
The  performance of these methods can be improved by implement a cache strategy.

**Comment by acezen** [comment]
### MsgPack vs simdjson (micro benchmarks)

#### python loads
<img width="645" alt="截屏2022-04-12 上午8 49 04" src="https://user-images.githubusercontent.com/11835645/162856974-f62857be-28ee-4260-88e2-d07b96799603.png">

<img width="645" alt="截屏2022-04-12 上午8 52 35" src="https://user-images.githubusercontent.com/11835645/162856992-7efd7e78-edb2-4f08-9690-90c16c2fb132.png">

**Comment by TkTech** [comment]
To add a clarification, as specified in the pysimdjson documentation, it has no serialization method. `simdjson.dump[s]` is just a convenience alias for `json.dump[s]`. simdjson is _only_ a parser.

**Comment by sighingnow** [comment]
> To add a clarification, as specified in the pysimdjson documentation, it has no serialization method. simdjson.dump[s] is just a convenience alias for json.dump[s]. simdjson is only a parser.

Thank you, Tyler. We do have noticed that and use `orjson` for serialization in our previous implementation.

We moved to msgpack after we realized that a binary protocol (msgpack here) works better than a textual protocol (json here) as the human-readability of the wire data is not a necessity for us.
