### ISSUE TITLE
[BUG]cannot run pagerank using code in tutorial

### ISSUE THREAD

**Issue by chenjiebo** [alibaba/GraphScope#1490]
**Describe the bug**
when try to run pagerank using code below, reporting cmake warning and errors. but running sssp succeeded
```python
import graphscope
graphscope.set_option(show_log=True)
from graphscope.dataset import load_p2p_network
graph = load_p2p_network(directed=False)
simple_graph = graph.project(vertices={"host": []}, edges={"connect": ["dist"]})
from graphscope import pagerank
pr_context = pagerank(simple_graph, delta=0.85, max_round=10)
```
errors:
>CMake Error at graphscope.runtime/lib/cmake/graphscope-analytical/cmake/FindArrow.cmake:270 (add_library):
  add_library cannot create imported target "arrow_shared" because another
  target with the same name already exists.
Call Stack (most recent call first):
  graphscope.runtime/lib/cmake/graphscope-analytical/cmake/FindArrow.cmake:319 (arrow_find_package_pkg_config)
 graphscope.runtime/lib/cmake/graphscope-analytical/cmake/FindArrow.cmake:350 (arrow_find_package)
  CMakeLists.txt:220 (include)

> CMake Error at graphscope.runtime/lib/cmake/graphscope-analytical/cmake/FindArrow.cmake:287 (add_library):
  add_library cannot create imported target "arrow_static" because another
  target with the same name already exists.
Call Stack (most recent call first):
  graphscope.runtime/lib/cmake/graphscope-analytical/cmake/FindArrow.cmake:319 (arrow_find_package_pkg_config)
  graphscope.runtime/lib/cmake/graphscope-analytical/cmake/FindArrow.cmake:350 (arrow_find_package)
  CMakeLists.txt:220 (include)
>
warning:
>   Found package configuration file:
>    /usr/local/lib/cmake/arrow/ArrowConfig.cmake
>  but it set Arrow_FOUND to FALSE so package "Arrow" is considered to be NOT
>  FOUND.  Reason given by package:
>  Arrow could not be found because dependency OpenSSL could not be found.
> Call Stack (most recent call first):
  /graphscope.runtime/lib/cmake/graphscope-analytical/cmake/FindArrow.cmake:313 (arrow_find_package_cmake_package_configuration)
 /graphscope.runtime/lib/cmake/graphscope-analytical/cmake/FindArrow.cmake:350 (arrow_find_package)
  CMakeLists.txt:220 (include)

**Environment (please complete the following information):**
 - GraphScope version: 0.12.0
 - OS: macOS Monterey 12.3.1
 - cluster type: hosts

**Comment by siyuan0322** [comment]
> Arrow could not be found because dependency OpenSSL could not be found
You can check if you have openssl installed, and you can use
```
# brew install openssl@1.1
brew info openssl@1.1
```
And it will print something like
```
export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"
```
You can execute this `export` command and run your script again.

**Comment by chenjiebo** [comment]
problem solved， thanks! 
my default openssl version is 3, is it required that openssl version=1.1?

**Comment by siyuan0322** [comment]
> my default openssl version is 3, is it required that openssl version=1.1?

No we didn't require a specific openssl version, you can use yours as long as arrow won't complain.
