### ISSUE TITLE
An additional parameter `degree_threshold` on algorithms to allow bypassing nodes with xxxlarge degree

### ISSUE THREAD

**Issue by yecol** [alibaba/GraphScope#1494]
as titled. Algorithms below would support:
- [x] LCC
- [ ] PageRank
- [x] Katz

**Comment by PaulWongDlut** [comment]
Clustering Coefficient, Pagerank and Katz.

**Comment by PaulWongDlut** [comment]
Clustering Coefficient, Pagerank and Katz.

**Comment by yecol** [comment]
> Clustering Coefficient, Pagerank and Katz.

Thanks for your feedback!
