### ISSUE TITLE
[GIE] Push filter to storage

### ISSUE THREAD

**Issue by tianliplus** [alibaba/GraphScope#1530]
**描述：**
在交互式查询引擎中，对于带有过滤条件的查询，计算会从存储中读取数据后进行过滤。由于目前我们采用的是 share-nothing 架构，计算和存储在同个进程，所以这种方式不会引入性能问题。但是后面我们计划向计算存储分离的架构演进，这样就需要把过滤条件下推到存储，从而减少计算和存储之间的数据交互。

**产出目标：**
1. 存储支持带有过滤条件的查询 (包括行过滤和列过滤)
2. 使用带有过滤条件的存储接口重新实现现有计算逻辑

**Comment by waruto210** [comment]
finished after PR #2003

**Comment by waruto210** [comment]
please close this issue.

**Comment by sighingnow** [comment]
> please close this issue.

Closing as a series of pull requests (e.g., #1905, #2003, #2086) has been merged.
