### ISSUE TITLE
review `.bachrc` in CI

### ISSUE THREAD

**Issue by yecol** [alibaba/GraphScope#1548]
- it is very strange our CI depends on bashrc.
- the envs should in .graphscope_env?
- @shirly121 reports if she removed the bashrc, it cannot find cargo envs.
 
![image](https://user-images.githubusercontent.com/426463/168027329-e54e2a97-9b42-4fca-a208-049f17cdd975.png)

- if some envs are CI specific, put them in the CI code, do not generate a bashrc.

**Comment by siyuan0322** [comment]
> @shirly121 reports if she removed the bashrc, it cannot find cargo envs.

This is because the env to find cargo executable is in `.bashrc`
https://github.com/alibaba/GraphScope/blob/95bd70166113d11fd325255bedf15499fee21f93/k8s/manylinux2014.Dockerfile#L305

> if some envs are CI specific, put them in the CI code, do not generate a bashrc.

Do `source ~/.cargo/env` in ci commands will work.

**Comment by siyuan0322** [comment]
Already been fixed. Now we doesn't rely on .bashrc on anywhere.
