### ISSUE TITLE
[BUG] 在官方例程测试平台测试"adamW"学习率优化算法出错

### ISSUE THREAD

**Issue by HEROhaoyu** [alibaba/GraphScope#1553]
在官方提供的平台上测试例程1论文分类，不改动其它代码，只是把学习率优化算法由“adam”改为“adamW”就显示出错了。adamW是官方支持的学习率算法。
![image](https://user-images.githubusercontent.com/47972100/168244130-88952978-7fe1-451d-9c85-c62385075c6d.png)

**Comment by acezen** [comment]
Seems the `adamW` strategy implement in graphlearn is not compatible with tensorflow 2.x.
The temporary workaround install tensorflow 1.5( which means you need to run with python3.6)

**Comment by HEROhaoyu** [comment]
好的，谢谢。
