### ISSUE TITLE
[GAE]  Decomposed `GraphXFragment` into `graphx_vertex_map`, `graphx_csr` for `VertexRDD` and `EdgeRDD`

### ISSUE THREAD

**Issue by longbinlai** [alibaba/GraphScope#1563]
As titled

**Comment by zhanglei1949** [comment]
- [done] VertexRDD(graphx_vertex_map,  graphx_vertex_data)
- [done] EdgeRDD(graphx_vertex_map, graphx_csr)
- [Onging] GrapeVertexRDD: mapvertices, iterator, reverse
- [Onging] GrapeEdgeRDD: mapVertices, iterator, reverse
- [TODO] GrapeGraph
