### ISSUE TITLE
Gremlin CI for GAIA-IR on vineyard

### ISSUE THREAD

**Issue by yecol** [alibaba/GraphScope#1565]
Currently the CI for GAIA-IR covers:
- the building stage
- triggers a test suite, `com.alibaba.graphscope.ir.maxgraph.IrGremlinTest` (however, it was an empty function)
- open a session and load a graph.

(If I overlooked something, please tell me)

We may need a CI covering the gremlin queries on GAIA-IR on vineyard, (e.g., like the previous `function_test.sh`)

**Comment by shirly121** [comment]
'com.alibaba.graphscope.ir.maxgraph.IrGremlinTest' is the entrypoint to the standard gremlin test runner, tests are in 'com.alibaba.graphscope.ir.maxgraph.IrGremlinTestSuite' and 90 have been passed.

<img width="1353" alt="image" src="https://user-images.githubusercontent.com/22363306/168542805-28f99c10-ea94-40fb-aaed-a067b74f7191.png">

**Comment by yecol** [comment]
Thanks for addressing!
