### ISSUE TITLE
Improve the response time of each step in Python

### ISSUE THREAD

**Issue by yecol** [alibaba/GraphScope#157]
Currently, some steps are response in a long time in Python, due to k8s pods/container launching, app/graph compilation... 
To reduce the response time, we may need to profile the steps, break down each part of cost in the engines, and find out the bottleneck.

**Comment by lidongze0629** [comment]
Related Issues:

#137 Pre-compile common apps/graphs in the distributed docker image

**Comment by yecol** [comment]
Hi Dongze, besides issue #137, you may also want to profiling other operations, e.g., `.gremlin()`, `.draw()`, ...

**Comment by lidongze0629** [comment]
**Rough profiling for each step:**

launch session:  29s   (image pulled already)
load graph: 54s (compile time: 40s, load time: 14s)
sess.gremlin:   50s
interactive subgraph time: 19s (load graph)
project_to_simple time: 26s
build_app time: 26s
add_column time: 3s

**Comment by lidongze0629** [comment]
**Reopen this issue to record the latest time(after improved) for each step.**

launch session:  
load graph: 
sess.gremlin:   
interactive subgraph time: 
project_to_simple time: 
build_app time: 
add_column time:
draw time: 
close time: 

**Some case for further optimization**
