### ISSUE TITLE
[GIE] Sort out the working items for replacing MaxGraph with Gaia 

### ISSUE THREAD

**Issue by longbinlai** [alibaba/GraphScope#1583]
1. Clarify the workflows in GraphScope that involves MaxGraph. 
2. Clarify the missing pieces in the above workflows that are supported by MaxGraph but not Gaia
3. Based on 2, summarize some milestones for the whole project of replacing MaxGraph. 

A WIP doc: 
https://yuque.antfin-inc.com/7br/graphscope/wqbz6p/edit

**Comment by yecol** [comment]
IMHO, we may consider to design elegant methods to replace our temporary workarounds introduced in the first version.
- e.g., get port from log file; (related issue #1577 )
- e.g., start a server and run tests by `POST` python code; (see details in #1499 )
- e.g., `kill.sh` 🤣
- ...
