### ISSUE TITLE
[BUG] Latest main branch cannot pass unittest, missing few python files

### ISSUE THREAD

**Issue by hh2712** [alibaba/GraphScope#1585]
**Describe the bug**
Latest main branch cannot pass unittest, missing few python files

**To Reproduce**
1. make test

**Screenshots**
`If applicable, add screenshots to help explain your problem.
ImportError while loading conftest '/home/graphscope/GraphScope/python/graphscope/tests/conftest.py'.
graphscope/__init__.py:19: in <module>
    from graphscope.analytical.app import *
graphscope/analytical/app/__init__.py:21: in <module>
    from graphscope.analytical.app.attribute_assortativity import \
graphscope/analytical/app/attribute_assortativity.py:22: in <module>
    from graphscope.framework.app import AppAssets
graphscope/framework/app.py:30: in <module>
    from graphscope.framework.context import create_context_node
graphscope/framework/context.py:28: in <module>
    from graphscope.framework import dag_utils
graphscope/framework/dag_utils.py:22: in <module>
    from graphscope.framework import utils
graphscope/framework/utils.py:39: in <module>
    from graphscope.framework.errors import check_argument
graphscope/framework/errors.py:21: in <module>
    from graphscope.proto import error_codes_pb2
E   ImportError: cannot import name 'error_codes_pb2' from 'graphscope.proto' (/home/graphscope/GraphScope/python/graphscope/proto/__init__.py)
make: *** [unittest] Error 4`

**Environment (please complete the following information):**
 - GraphScope version: master
 - OS: Linux
 - Version Ubuntu 20.04

**Comment by siyuan0322** [comment]
Hi， may I ask if this is a fresh environment / repo, or you updated from the previous version?
The latest PR #1547 has a directory change of proto files.

**Comment by acezen** [comment]
You need to `make graphscope` first

**Comment by hh2712** [comment]
> You need to `make graphscope` first

neglected from my description, yes, by all means, I have done `make graphscope`

**Comment by hh2712** [comment]
> Hi， may I ask if this is a fresh environment / repo, or you updated from the previous version? The latest PR #1547 has a directory change of proto files.

checked out from the latest main branch.

**Comment by siyuan0322** [comment]
Thanks for sharing, I will try to reproduce the bug.

**Comment by siyuan0322** [comment]
Can you do `ls /home/graphscope/GraphScope/python/graphscope/proto/` and copy the output to here?

**Comment by hh2712** [comment]
> Can you do `ls /home/graphscope/GraphScope/python/graphscope/proto/` and copy the output to here?

`-rw-rw-r-- 1 1006 1006 2707 May 18 09:41 attr_value.proto
-rw-rw-r-- 1 1006 1006 1405 May 18 09:41 coordinator_service.proto
-rw-rw-r-- 1 1006 1006 2330 May 18 09:41 data_types.proto
-rw-rw-r-- 1 1006 1006 2445 May 18 09:41 ddl_service.proto
-rw-rw-r-- 1 1006 1006  993 May 18 09:41 engine_service.proto
-rw-rw-r-- 1 1006 1006 2649 May 18 09:41 error_codes.proto
-rw-rw-r-- 1 1006 1006 3762 May 18 09:41 graph_def.proto
-rw-rw-r-- 1 1006 1006  683 May 18 09:41 __init__.py
-rw-rw-r-- 1 1006 1006 4751 May 18 09:41 message.proto
-rw-rw-r-- 1 1006 1006 2453 May 18 09:41 op_def.proto
-rw-rw-r-- 1 1006 1006 4135 May 18 09:41 proto_generator.py
-rw-rw-r-- 1 1006 1006 6687 May 18 09:41 types.proto
-rw-rw-r-- 1 1006 1006 2063 May 18 09:41 write_service.proto`

**Comment by siyuan0322** [comment]
The python proto files should be generated in this place while there is none. So I guess the `make graphscope` may have some errors.

You can generate it manually by `cd /home/graphscope/GraphScope/python && python3 setup.py build_proto`. Then the tests should pass.

**Comment by sighingnow** [comment]
Closed as stale.

@hh2712 Thanks for the reporting and feel free to reopen if you are still blocked by this issue.
