### ISSUE TITLE
[Proposal]Performance optimization in clustering coefficient

### ISSUE THREAD

**Issue by PaulWongDlut** [alibaba/GraphScope#1586]
@yecol 

I got a very bad performance when I use the clustering coefficient api over a very large dataset.  

Then I realized that there are lots of nodes in the graph with only 1 neighbor which theoretically means that their clustering coefficient is zero.

So I think if there is any possibility to reduce the computation cost over the nodes with degree of 1, in order to improve the clustering coefficient performance.

**Comment by yecol** [comment]
Thanks for your proposal! 
We will consider this solution and try to improve its performance!
Could you also provide the datasets to reproduce this?
