### ISSUE TITLE
[BUG] Servers seems cannot be connected when given ServerConf::All in JobConfig 

### ISSUE THREAD

**Issue by BingqingLyu** [alibaba/GraphScope#1590]
**Describe the bug**
When starting pegasus on two servers, given a JobConfig with ServerConf::All, it will output two results separately, which is not expected.

**To Reproduce**
1. Go to repo https://github.com/longbinlai/GraphScope/tree/ir_runtime_service
2. `cd ~/GraphScope/research/query_service/ir/compiler` and `make build`; then start compiler  by `make run`
3. `cd ~/GraphScope/research/query_service/ir`; then start servers by 
`RUST_LOG=Info DATA_PATH=path_of_data PARTITION_ID=0 ./target/release/start_rpc_server --config ./integrated/config/distributed/server_v0`
`RUST_LOG=Info DATA_PATH=path_of_data PARTITION_ID=1 ./target/release/start_rpc_server --config ./integrated/config/distributed/server_v1`
4. query `g.V().count()` by gremlin console, see errors:
![image](https://user-images.githubusercontent.com/28559306/169202432-59a8379a-2fc1-4953-90ea-441dc230978b.png)

**Expected behavior**
When given config of ServerConf::Part(vec![0,1]), we can get expected result:
![image](https://user-images.githubusercontent.com/28559306/169202498-28bf0132-8c29-4b4c-b944-81f3961fc46a.png)

**Comment by lnfjpt** [comment]
https://github.com/alibaba/GraphScope/compare/gaia-x...lnfjpt:gaia-x
