### ISSUE TITLE
[BUG] Missing 'label' info during gremlin query with GAIA engine under vineyard store

### ISSUE THREAD

**Issue by lidongze0629** [alibaba/GraphScope#1611]
vineyard_version: v0.4.1
graphscope version: main branch (0aa8c3c6f0f18cb5c2a4aabc2814561a2357699c)

<img width="512" alt="截屏2022-05-24 下午1 57 58" src="https://user-images.githubusercontent.com/23491543/169989824-c1ca3927-4cd8-4248-9290-c9f8110e15aa.png">

**Comment by BingqingLyu** [comment]
This can be resolved in #1615
