### ISSUE TITLE
Listening port of GAIA frontend

### ISSUE THREAD

**Issue by lidongze0629** [alibaba/GraphScope#1612]
~~A list of issues to address some tiny problems, which are not suitable for a new issue~~

- [ ] Listen `0.0.0.0` address in GAIA frontend

**Comment by yecol** [comment]
There is no "problem" not suitable for a new issue!
Every bug deserves an issue~
Please do not hesitate to open an issue~!
It would always be warmly welcome!
As we told the community and shown on README!

<img width="453" alt="image" src="https://user-images.githubusercontent.com/426463/169991947-ddb10491-bc9c-4adb-bb35-38673d29f6fa.png">
