### ISSUE TITLE
GraphScope Gremlin 引擎问题反馈

### ISSUE THREAD

**Issue by baizn** [alibaba/GraphScope#1617]
**Describe the bug**
使用 Gremlin 查询过程中遇到的问题，都反馈到这个 issues 下面， 麻烦  @yecol   统一看一下，感谢！

- [x] nodejs id 不一致
- [x] valueMap 支持
- [x] gremlin 3.5.1 patch 包发布
- [x] `bothE` failed
- [x] `both().bothE()` failed
- [x] `valueMap` 为 None 的点也返回
- [ ] 边属性 (#1723 )
- [x] 模式匹配：JSON 转 Gremlin 语句，查询结果
- [ ] ~~g.V().has('id', 'xxx')，报错 key id must be positive number~~
- [ ] repeat operator support (#1722 )

**Comment by baizn** [comment]
通过 gremlin console 查询结果和使用 python client 查询一致的，但和使用 nodejs client 查询返回的节点 ID 不一致。

使用 Gremlin console：
![image](https://user-images.githubusercontent.com/9443867/170026673-32864807-7583-4e99-9a97-8c76fe5a1ebb.png)


使用 node client：
![image](https://user-images.githubusercontent.com/9443867/170026594-0eb78598-34fb-4aab-be27-94071d229ff1.png)

**Comment by baizn** [comment]
通过类似 g.V().has('id', 'xxxx') 这种 Gremlin 语句查询到的数据没有 label 和 properties 信息。
![image](https://user-images.githubusercontent.com/9443867/170026891-d0f76bcd-b99c-428e-bf81-d228ff0c79e8.png)

**Comment by baizn** [comment]
不支持 repeat 语法
![image](https://user-images.githubusercontent.com/9443867/170164365-ffe9d16e-e457-4376-9d60-abc6d32c4475.png)

**Comment by baizn** [comment]
不支持 g.V().valueMap() 和 g.V().properties()

**Comment by baizn** [comment]
查询多个点的属性，如果其中一个点没属性，现在返回来就是把没属性的忽略了，如下图，出现的问题是不知道哪个节点ID没属性，不好一一对应，因为属性返回的没有查的那个id
![image](https://user-images.githubusercontent.com/9443867/170646164-296094e7-e74d-45f3-bf4a-70abc8b44794.png)

**Comment by baizn** [comment]
不能直接使用  g.E(1, 3).valueMap() 获取边的属性，目前只能通过以下两种方式：
- 一种是通过属性 id 去查，比如 g.E().hasLabel('knows').has('id', xx)；
- 另一种，假如是从某个点拿到邻边的话，直接在拿邻边操作里查到，比如 g.V(xx).outE().valueMap()

**Comment by baizn** [comment]
查询点的属性，比如 g.V(1, 2, 3, 4).valueMap()，但节点 ID 为 2 的节点没有属性时，需要返回一个空对象占位，否则没有办法将节点和返回的属性值一一匹配。

**Comment by baizn** [comment]
Gremlin 引擎： @lidongze0629  支持 bigNumber 的 3.5.1 版本，需要发新包，否则线上环境查询到的节点 ID 还是会丢失精度。

**Comment by baizn** [comment]
同一个 inner_id，g.V(id).both() 返回的节点的 inner_id 和 g.V(id).bothE()  中 outV/inV 中的 inner_id  完全不一样
![image](https://user-images.githubusercontent.com/9443867/171530664-4f1ccee0-d5a0-42ba-95bc-aea5f5bf3eaa.png)

**Comment by baizn** [comment]
使用 g.V().has('id', 'xxx') 查询，报如下错误信息：
![image](https://user-images.githubusercontent.com/9443867/171816436-85d2e855-9790-4824-b4eb-21f27e279187.png)

**Comment by longbinlai** [comment]
> 不支持 repeat 语法 ![image](https://user-images.githubusercontent.com/9443867/170164478-9d1f7acc-95fd-40f2-a4cd-24b12b30ff69.png)
Hi, `repeat` 目前在GIE是deprecated的. 但是对于如下的查询， `g.V().repeat(both(‘knows’)).times(n)`，其中both()可以是in/out，但repeat里必须只有一个算子（也就是目前还不支持类似`g.V().repeat(outE().inV()).times(n)` 这种），那么可以写成`g.V().both('knows', n .. n+1)`，这个 `x..y` 是一个多跳的语义，表示至少x跳（包含）最多y跳（不包含）。

**Comment by longbinlai** [comment]
> 不支持 repeat 语法 ![image](https://user-images.githubusercontent.com/9443867/170164478-9d1f7acc-95fd-40f2-a4cd-24b12b30ff69.png)
Hi, `repeat` 目前在GIE是deprecated的. 但是对于如下的查询， `g.V().repeat(both(‘knows’)).times(n)`，其中both()可以是in/out，但repeat里必须只有一个算子（也就是目前还不支持类似`g.V().repeat(outE().inV()).times(n)` 这种），那么可以写成`g.V().both('knows', n .. n+1)`，这个 `x..y` 是一个多跳的语义，表示至少x跳（包含）最多y跳（不包含）。
