### ISSUE TITLE
[BUG] LPA failed on graph with 'string' OID

### ISSUE THREAD

**Issue by lidongze0629** [alibaba/GraphScope#1628]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - GraphScope version: [e.g., v0.1, v0.2.2, master]
 - OS: [e.g. MacOS, Linux]
 - Version [e.g. 10.15]
 - Kubernetes Version [e.g., 1.19]

**Additional context**

**Comment by septicmk** [comment]
solved by https://github.com/alibaba/libgrape-lite/pull/128
