### ISSUE TITLE
[Question]How to store additional feature in GraphScope

### ISSUE THREAD

**Issue by littleDrew** [alibaba/GraphScope#1629]
您好，咨询下GraphScope中怎么存储多余的一些字段：

例如，在看vectornet实现代码时，它的每个子图包含额外的字段cluster, valid_len, 其中一条数据的shape可以如下
> 该代码是在PYG基础上实现的
> https://github.com/xk-huang/yet-another-vectornet/blob/master/modeling/vectornet.py#L49

```Python
data (Data): [x, y, cluster, edge_index, valid_len]

# 一条数据的shape
Data(cluster[253], edge_index=[2, 2342], time_step_len=[1], valid_len=[1], x=[253, 8], y=[60])
```

- `cluster`, `time_step_len`, `valid_len` 这些是这数据集中特有的额外的字段
- 对应如果在GraphScope中存储的话，怎么存来着，这些额外的字段 不属于`node_feat`或`edge_feat`吧

**Comment by lidongze0629** [comment]
@littleDrew 这些数据集中特有的额外的字段，是如何参与计算的呢？
