### ISSUE TITLE
[BUG] unexist docker dataset image & unsuitable timeout_seconds param

### ISSUE THREAD

**Issue by wuyueandrew** [alibaba/GraphScope#1646]
**Describe the bug**

1. There is no 0.13.0 dataset docker image (registry.cn-hongkong.aliyuncs.com/graphscope/dataset:0.13.0), maybe missing to build.
2. Default value of timeout_seconds(60) is not enough for pull all images in some situation and  it will throws a timeout exception. Some beginners feel confused, so how about add a FAQ item to explain it or change timeout_seconds longer.

**Comment by lidongze0629** [comment]
Thanks @wuyueandrew for reporting the problems and giving excellent suggestions.

1. `registry.cn-hongkong.aliyuncs.com/graphscope/dataset:0.13.0` is already published, you can try again.
2. The `timeout_seconds` is defaults to [600](https://github.com/alibaba/GraphScope/blob/main/python/graphscope/config.py#L96) in GraphScope codebase, and we will add a FAQ item in the next release.

**Comment by wuyueandrew** [comment]
> Thanks @wuyueandrew for reporting the problems and giving excellent suggestions.
> 
> 1. `registry.cn-hongkong.aliyuncs.com/graphscope/dataset:0.13.0` is already published, you can try again.
> 2. The `timeout_seconds` is defaults to [600](https://github.com/alibaba/GraphScope/blob/main/python/graphscope/config.py#L96) in GraphScope codebase, and we will add a FAQ item in the next release.

Thanks
