### ISSUE TITLE
[BUG] install_deps on macOS failed 

### ISSUE THREAD

**Issue by Issac-Newton** [alibaba/GraphScope#1649]
**Describe the bug**
I try to build GraphScope on macOs in standalone mode, and I install dependencies, but it failed when installing zetcd.

**To Reproduce**
./install_deps.sh --dev --cn

**Screenshots**
`[2022-06-01T07:20:56+0800]: Installing zetcd.
go: found github.com/etcd-io/zetcd/cmd/zetcd in github.com/etcd-io/zetcd v0.0.5
go: finding module for package github.com/coreos/zetcd
go: finding module for package golang.org/x/net/context
go: finding module for package github.com/coreos/etcd/pkg/transport
go: finding module for package github.com/coreos/etcd/clientv3
go: finding module for package github.com/coreos/zetcd/zk
go: finding module for package github.com/coreos/zetcd/version
go: downloading github.com/coreos/etcd v0.9.4
go: finding module for package github.com/coreos/zetcd/xchk
go: found github.com/coreos/zetcd in github.com/coreos/zetcd v0.0.5
go: found github.com/coreos/zetcd/version in github.com/coreos/zetcd v0.0.5
go: found github.com/coreos/zetcd/xchk in github.com/coreos/zetcd v0.0.5
go: found github.com/coreos/zetcd/zk in github.com/coreos/zetcd v0.0.5
go: found golang.org/x/net/context in golang.org/x/net v0.0.0-20220531201128-c960675eff93
go: finding module for package github.com/coreos/etcd/pkg/transport
go: finding module for package github.com/coreos/etcd/clientv3
go: finding module for package github.com/coreos/etcd/clientv3/concurrency
go: finding module for package github.com/golang/glog
go: found github.com/golang/glog in github.com/golang/glog v1.0.0
go: finding module for package github.com/coreos/etcd/pkg/transport
go: finding module for package github.com/coreos/etcd/clientv3
go: finding module for package github.com/coreos/etcd/clientv3/concurrency
go: finding module for package github.com/coreos/etcd/pkg/transport
go: finding module for package github.com/coreos/etcd/clientv3
go: finding module for package github.com/coreos/etcd/clientv3/concurrency
go: finding module for package github.com/coreos/etcd/pkg/transport
go: finding module for package github.com/coreos/etcd/clientv3
go: finding module for package github.com/coreos/etcd/clientv3/concurrency
../../../go/pkg/mod/github.com/etcd-io/zetcd@v0.0.5/cmd/zetcd/zetcd.go:27:2: reading github.com/coreos/etcd/go.mod at revision v0.9.4: unknown revision v0.9.4
../../../go/pkg/mod/github.com/coreos/zetcd@v0.0.5/zketcd.go:27:2: reading github.com/coreos/etcd/go.mod at revision v0.9.4: unknown revision v0.9.4
../../../go/pkg/mod/github.com/etcd-io/zetcd@v0.0.5/cmd/zetcd/zetcd.go:28:2: reading github.com/coreos/etcd/go.mod at revision v0.9.4: unknown revision v0.9.4`

**Environment (please complete the following information):**
 - GraphScope version: main
 - OS: MacOS
 - Version 12.3.1
 - Kubernetes Version : none
 - go version: 1.15.14

**Additional context**
I looked up the repository under CoreOs, it doesn't contain etcd, which may cause the error. 

Maybe it's a problem for zetcd, but it seems stop maintenance for a long time.

**Comment by acezen** [comment]
Thanks for the bug report, can you try to 
`export GO111MODULE="auto"` 
before running the script.

**Comment by Issac-Newton** [comment]
it works, thanks a lot.

**Comment by yecol** [comment]
Thanks for reporting!
It will be fixed with a following PR.
