### ISSUE TITLE
Can't load graph from HDFS

### ISSUE THREAD

**Issue by parkerzf** [alibaba/GraphScope#1652]
Hey GS,
I try to test GraphScope with data in HDFS with the following code:

```python
import graphscope
import graphscope.nx as nx
from graphscope.framework.loader import Loader

graphscope.set_option(show_log=True)

edges = Loader("hdfs:///data/graph/twitter.e", host='localhost', port='8020')
graph = graphscope.g(directed=False)

graph.add_edges(edges)
```

However I got this error:

```
E0601 08:12:02.784389411  227251 fork_posix.cc:76]           Other threads are currently calling into gRPC, skipping fork() handlers
Exception ignored in: <function Launcher.__del__ at 0x7f0f10f4a550>
Traceback (most recent call last):
  File "/opt/app_graphyen/venv3.8/lib/python3.8/site-packages/vineyard/launcher/launcher.py", line 63, in __del__
    self.join()
  File "/opt/app_graphyen/venv3.8/lib/python3.8/site-packages/vineyard/drivers/io/stream.py", line 139, in join
    raise RuntimeError(
RuntimeError: Subprocesses failed with the following error: 
Failed to launch job [/opt/app_graphyen/venv3.8/lib/python3.8/site-packages/vineyard/drivers/io/ssh.sh localhost vineyard_read_bytes /tmp/vineyard.sock.1654063891.489883 "hdfs:///user/feng/notebooks/data/graph/twitter.e" eyJob3N0IjogImhkcC1saXZlLWEiLCAicG9ydCI6ICI4MDIwIn0= eyJkZWxpbWl0ZXIiOiAiLCIsICJoZWFkZXJfcm93IjogdHJ1ZSwgInNjaGVtYSI6ICIwLDEiLCAiY29sdW1uX3R5cGVzIjogImludDY0X3QsaW50NjRfdCIsICJpbmNsdWRlX2FsbF9jb2x1bW5zIjogdHJ1ZX0= 1 0], exited with 127: bash: vineyard_read_bytes: command not found

extra diagnostics are as follows: 

/tmp/arrow-apache-arrow-1.0.1/cpp/src/arrow/result.cc:28: ValueOrDie called on an error: NotImplemented: Got HDFS URI but Arrow compiled without HDFS support
```

Do you know how to resolve this issue: `Got HDFS URI but Arrow compiled without HDFS support`? Thanks!

**Comment by parkerzf** [comment]
The twitter.e is the one used in the 03_run_graphscope_like_networkx.ipynb.

**Comment by sighingnow** [comment]
> The twitter.e is the one used in the 03_run_graphscope_like_networkx.ipynb.

Could you paste the output about `pip freeze`?

**Comment by sighingnow** [comment]
We have introduced some break changes and the IO drivers fir HDFS and the graph loader has diverged a bit.

Will be fixed in the next bug-fix release which will be dilivered next week.

**Comment by sighingnow** [comment]
FIxed on main and will be release this week.

**Comment by Song-xx** [comment]
can load graph from HDFS now? and what about load graph from graph database such as neo4j and tiger graph?

**Comment by sighingnow** [comment]
> can load graph from HDFS now?

Loading HDFS should work (and have been tested in CI) in current release (v0.17.0).

> and what about load graph from graph database such as neo4j and tiger graph?

Load graph from graph database such as neo4j and tiger graph is not supported yet and there's no such a plan yet. We suggest you export the data as CSV then loading to graphscope.

**Comment by Song-xx** [comment]
> > can load graph from HDFS now?
> 
> Loading HDFS should work (and have been tested in CI) in current release (v0.17.0).
> 
> > and what about load graph from graph database such as neo4j and tiger graph?
> 
> Load graph from graph database such as neo4j and tiger graph is not supported yet and there's no such a plan yet. We suggest you export the data as CSV then load into graphscope.

thanks
