### ISSUE TITLE
[BUG] CI procedures is not consistent between pull request and main after pull request merged

### ISSUE THREAD

**Issue by sighingnow** [alibaba/GraphScope#1673]
**Describe the bug**

It looks quite strange that some test cases are not executed in pull request but are executed on main after the same pull request merged, see

- CI on pull request: https://github.com/alibaba/GraphScope/runs/6749142646?check_suite_focus=true
- CI on main after pull request merged: https://github.com/alibaba/GraphScope/runs/6751168467?check_suite_focus=true

It's quite risky to receive a :x: on main due to the inconsistence.

**Additional context**

**Comment by siyuan0322** [comment]
https://github.com/alibaba/GraphScope/blob/c4a2f9ed65422ee02550cf4c03228b95dd633249/.github/workflows/ci.yml#L558
