### ISSUE TITLE
Refactor packages in GIE

### ISSUE THREAD

**Issue by siyuan0322** [alibaba/GraphScope#1677]
The packages in GIE should be refactored/reorg, and move research package into GIE.

**Package Rename:**
There should not exist such package name of `com.alibaba.maxgraph`, but only `com.alibaba.graphscope.groot` and `com.alibaba.graphscope.interactive`.

**Packages Reorg:**
The expected org is as follows:

------ Rust codes -------------
interactive_engine/executor/engine/pegasus
interactive_engine/executor/ir/{common, core, graph_proxy, integrated, runtime, proto}
interactive_engine/executor/common/{dyn_type} 
interactive_engine/executor/assembly/{groot, v6d}
interactive_engine/executor/store/{global_query, groot_store, exp_store} 

------ Java codes -------------
interactive_engine/frontend/{ir-compiler}
interactive_engine/benchmark/
interactive_engine/groot/{groot, groot_server, lgraph, data-load-tools}
interactive_engine/common/
interactive_engine/sdk/
interactive_engine/tests/

**Comment by yecol** [comment]
how about to use `io.graphscope.xxx` :)

**Comment by BingqingLyu** [comment]
`executor` (i.e., the rust related codes) is reorganized in #1883, with two remaining issues/TODO:

**Comment by BingqingLyu** [comment]
executor (i.e., the rust related codes) is reorganized in https://github.com/alibaba/GraphScope/pull/1883, with two remaining issues/TODO: 1). a bug occurs in `gremlin_test`, described in #1898 . 2). The `compiler` package is still in `executor/ir`, and need to be moved into `frontend`.
