### ISSUE TITLE
Failed to use `./scripts/launch_cluster.py` on AWS EKS

### ISSUE THREAD

**Issue by parkerzf** [alibaba/GraphScope#1696]
Got this error when running the launch_cluster.py. Should I just use `ekscli` to launch the cluster?

```
central-1 --output ./kube_config
Checking requirements...
Requirements fulfilled.
Now cloud has clusters ['n-eks-cluster'], Do you want to use existed clusters? [y/N]: N
The name of cluster to create: graphscope-eks
k8s version (1.15, 1.16, 1.17, 1.18, 1.19) [1.18]: 1.19
Worker node instance type, defalut [t4g.large]: t3.medium
Worker node num, default [4]: 2
*** EKS cluster
*** VPC stack
Creating VPC stack...
Created stack graphscope-eks-vpc
Waiting for VPC stack creation to complete...
        VPC stack created
VPC ID: vpc-0c8f288a469a17093
VPC security group: sg-03f32527978e3e8a0
VPC subnet IDs: subnet-09fac690198083789,subnet-0b423e3c37f541974,subnet-080480beff34cccfc
*** IAM role
IAM role does not exist.  Creating...
Creating cluster (ETA ~10 minutes)...
Start creating cluster.
Waiting for completion (ETA 10 minutes)...
Cluster active.
*** EKS configuration.
Cluster: https://6496C49557686D8F9E1A916A4A65632A.gr7.eu-central-1.eks.amazonaws.com
Written to ./kube_config.
*** Workers stack.
Creating workers stack...
Initiated workers (ETA 5-20 mins)...
Waiting for workers stack creation to complete...
Error: Waiter StackCreateComplete failed: Waiter encountered a terminal failure state: Matched expected service error code: ValidationError, gave up waiting for stack to create.
```

**Comment by parkerzf** [comment]
Thanks for looking into it. We end up using `ekscli` to create the cluster. GraphScope is quite a promising project and we are trying to make a proper benchmark and decide if we are going to use it in production. However, it seems that the deployment documentation is not quite reproducible and I will share my deployment/benchmark journey and hopefully I could contribute to make it smoother for people to start using GraphScope.

**Comment by yecol** [comment]
Hi @parkerzf ,

Thank you for your interest in GraphScope!
Sorry for the inadequate documentation, we are still working to improve it.
Please don't hesitate to contact us by opening issues or via DingTalk/Slack, if you have any questions.

And looking forward to your sharing and contribution! 
:)
