### ISSUE TITLE
[BUG] build on ubuntu20.04 failed

### ISSUE THREAD

**Issue by waruto210** [alibaba/GraphScope#1735]
**Describe the bug**
The readme states that builds are supported on ubuntu.
But `research/query_service/ir/compiler/pom.xml:259` use `sh` to execute `build_ir_core.sh`, while `sh` on ubuntu is a symbol link to dash, which whill cuase `build_ir_core.sh` run `echo "cargo not exit, skip compile"`. 

**To Reproduce**
build on ubuntu20.04

**Comment by sighingnow** [comment]
This is a known issue and has been fixed on fork, will be submitted along with the _subgraph_ PR.
