### ISSUE TITLE
Why is there a dependency graphscope-client==0.12.0->gs-coordinator==0.14.0

### ISSUE THREAD

**Issue by parkerzf** [alibaba/GraphScope#1754]
`pip-compile requirements.txt`:

```
2022-06-22 14:32:43,299 main PipCompileRequirements         [abstract_step.py    :93  ] DEBUG    networkx==2.6 (from graphscope-client==0.12.0->gs-coordinator==0.14.0->graphscope==0.14.0->-r requirements.txt (line 22))
```

while in graphscope v0.14.0, we need networkx==2.8, which results in a conflict.

**Comment by sighingnow** [comment]
Which requirements.txt are your auditting? `python/requirements.txt` or `coordinator/requirements.txt`?

**Comment by sighingnow** [comment]
Are you working on the latest main branch? May I know your python version?

**Comment by parkerzf** [comment]
My python version: Python 3.8.11
GraphScope version: V0.14.0
I created my own requirements.txt with graphscope in it:
`graphscope==0.14.0`

**Comment by sighingnow** [comment]
Cannot reproduce with a requirements.txt that contains only

```
graphscope==0.14.0
```

(Using latest pip-tools).

@parkerzf Could you please paste a complete `requirements.txt` so that we can investigate the issue further? Thanks!

**Comment by parkerzf** [comment]
Indeed, only graphscope doesn't has any issue. It is only appeared when I have a conflicted networkx version from other libs. Just the error message is quite missing leading: `graphscope-client==0.12.0->gs-coordinator==0.14.0`. Without other libs, it is graphscope-client==0.14.0 in the compiled file. I will close the issue. Thanks!

**Comment by sighingnow** [comment]
> 

Thanks for the information. GraphScope starts to reply on networkx==2.8.0 for Python 3.8 since v0.14.0: https://github.com/alibaba/GraphScope/blob/main/python/requirements.txt#L8-L9
