### ISSUE TITLE
[BUG] Iterate operator failed after fold when input is empty

### ISSUE THREAD

**Issue by lnfjpt** [alibaba/GraphScope#1759]
**Describe the bug**
iterate operator will fail after fold&unfold operations when input is empty

switch operator will throw warning: [root] not end while [x] leave iteration (x is max_iters of iteration condition)
then panicked at 'iteration of [root] not found; 

**To Reproduce**
Here is an example to reproduce this bug
``` rust
let stream = input.input_from(vec![0i64])?;
stream
    .fold(0, || |collect, _| Ok(collect))?
    .unfold(|source| Ok(Some(source).into_iter()))?
    .filter_map(move |source| if source > 0 { Ok(Some(source)) } else { Ok(None) })?  // all data will be filtered here
    .iterate_emit_until(IterCondition::max_iters(64), EmitKind::After, move |start| {
        start.map(|count| Ok(count + 1))
    })?
    .sink_into(output)
```

**Comment by bmmcq** [comment]
check: https://github.com/bmmcq/fork-pegasus/commit/a7fd4fdfe354d87260fee484d4710baeab71d28e
