### ISSUE TITLE
[Pegasus] Compiling warnings while compiled with the latest Rust version (> 1.60)

### ISSUE THREAD

**Issue by longbinlai** [alibaba/GraphScope#1789]
While updating to the latest Rust version (> 1.60), Pegasus starts to produce some warnings during compilation, such as:
![Screen Shot 2022-07-04 at 10 20 36](https://user-images.githubusercontent.com/7007589/177070442-9588aade-0c32-4d3c-8b7a-aa7b6b52b829.png)

**Comment by siyuan0322** [comment]
The warning will addressed by #1782

**Comment by siyuan0322** [comment]
The fix commit has been merged and confirmed that these warnings are gone.
