### ISSUE TITLE
Support loading graph from HuaWei Cloud OBS

### ISSUE THREAD

**Issue by lidongze0629** [alibaba/GraphScope#18]
**FYI**
https://www.huaweicloud.com/product/obs.html
https://support.huaweicloud.com/sdk-c-devg-obs/obs_20_0004.html

**Comment by wenyuanyu** [comment]
We will add AWS S3 support (#51 ) in Jan, which will be compatible with Huawei OBS and other storages.
See: https://blog.csdn.net/weixin_39132936/article/details/103260024

**Comment by wenyuanyu** [comment]
Another option: try https://github.com/huaweicloud/huaweicloud-obs-obsfs
