### ISSUE TITLE
Support Tinkerpop gremlin test cases in GAIA IR.

### ISSUE THREAD

**Issue by siyuan0322** [alibaba/GraphScope#1802]
**We plan to support these test cases in this scrum (0627 - 0715)**
- [x] aggregation, min / max / sum / countDistinct / toList(fold) (to be fixed in `ir_compiler_aggFn`)
- [x] mean (avg in ir)
- [x] hasNot
- [x] dedup by variables
- [x] dedup by subtask
- [x] selecting a none tag should return empty result instead of throwing exception (to be fixed in `select_none_tag`)
- [x] cases with unexpected results (`range(1,2)` with a lower bound greater than 0 is unsupported in runtime)

**We plan to support these test cases in the near future**
- [ ] and/or operators
- [ ] count(local)/order(local)
- [ ] repeat
- [ ] path, simplePath, cyclicPath

**Support for these test cases are not planned**
1. choose
2. parameters of V() and hasId() are constrained to integer or list of integers in ir grammar, V("1") or hasId("id") will not be supported under this consideration

**Comment by siyuan0322** [comment]
Remove the TODO in [ci.yml](https://github.com/alibaba/GraphScope/blob/a675598e54c74ce9699de84718f09cd334bf6956/.github/workflows/ci.yml#L620)

**Comment by longbinlai** [comment]
Remaining cases such as path/repeat etc may be reopened in a new issue in the next-stage scrum.
