### ISSUE TITLE
Subgraph will stuck in some certain configuration

### ISSUE THREAD

**Issue by siyuan0322** [alibaba/GraphScope#1803]
With 2 threads and 2 workers, the following subgraph query will stuck

```python
interactive.subgraph('g.V().hasLabel("person").outE("knows")')
```

**Comment by BingqingLyu** [comment]
The is caused by the bug in Pegasus. Related issue #1800

**Comment by siyuan0322** [comment]
Remove the TODO in [test_min.py](https://github.com/alibaba/GraphScope/blob/a675598e54c74ce9699de84718f09cd334bf6956/python/graphscope/tests/minitest/test_min.py#L179) and [test_demo_script.py](https://github.com/alibaba/GraphScope/blob/a675598e54c74ce9699de84718f09cd334bf6956/python/graphscope/tests/kubernetes/test_demo_script.py#L172)

**Comment by BingqingLyu** [comment]
Still get stuck in distributed computation.
