### ISSUE TITLE
[BUG] build failed on mac

### ISSUE THREAD

**Issue by yecol** [alibaba/GraphScope#1818]
I tried to build GraphScope on my MacBook Pro(with M1 pro), but failed. 

<img width="1444" alt="image" src="https://user-images.githubusercontent.com/426463/177946834-9f64c8c0-275d-4345-b626-5056bdc6337c.png">

**Comment by yecol** [comment]
It can be fixed with zulu dist of Java. 
Is that possible to support M1 in a more native way?
- low-priority.

**Comment by sighingnow** [comment]
@siyuan0322 has upgrade the required protobuf version.

It should no longer require x86 jdk on M1 MacOS.

**Comment by yecol** [comment]
Cool! Will try and verify later.

**Comment by sighingnow** [comment]
Reopen as https://github.com/alibaba/GraphScope/pull/1830 is still on the way.
