### ISSUE TITLE
Improve the `install_deps.sh`, or make the documentc around it better.

### ISSUE THREAD

**Issue by parkerzf** [alibaba/GraphScope#1849]
**Is your feature request related to a problem? Please describe.**
It is quite frustrated to install GraphScope using the `install_deps` script. Either we make the script more robust or make the document more complete around it.

**Describe the solution you'd like**
Here is how we made it work:

* Requirement: Ubuntu 20.x
```
sudo apt update
sudo apt-get install -y llvm-11-dev lld-11 clang-11 libre2-dev libc-ares-dev
export LLVM11_HOME=/usr/lib/llvm-11
sudo ln -fs /usr/lib/llvm-11/bin/clang /usr/bin/
sudo ln -fs /usr/lib/llvm-11/bin/clang++ /usr/bin/
sudo ln -fs /usr/lib/llvm-11/bin/clang-cpp /usr/bin/

git clone https://github.com/alibaba/GraphScope.git
cd GraphScope/
./scripts/install_deps.sh --dev
rustup component add rustfmt

source $HOME/.graphscope_env
make graphscope
```

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by acezen** [comment]
Thanks for you suggestion.  Could you tell us what problem you encounter when using `install_deps` script, that would give us a direction to revise the script and enhance the document.

**Comment by parkerzf** [comment]
You could reproduce it by starting a standard EC2 instance on AWS with `Ubuntu 20.x`. Just to give you more context, here are the extra things we need to do besides `install_deps.sh`:

* re2, c-ares are not auto installed and CMake folder settings are missing.
* clang/llvm is not auto installed.
* LLVM11_HOME is expected by one of the components build.xml. I would expect that to use latest llvm available or at least use clang,clang++ relative to LLVM11_HOME.
* Had to run rustup component add rustfmt in the middle

**Comment by acezen** [comment]
Thanks! @parkerzf
