### ISSUE TITLE
[BUG] Some basic gremlin queries are slow. 

### ISSUE THREAD

**Issue by siyuan0322** [alibaba/GraphScope#1854]
**Describe the bug**
Some gremlin queries are very slow, which are supposed to be very fast.

- [x] g.V().limit(1)  # Sometimes 1 min, sometimes < 1s.
- [ ] g.V().count() # timeout after 10 min, 900 million vertices
- [ ] g.E().count() # cost 56s, 30 million edges
- [x] g.E().hasLabel(%s).has('id', %s)  # slow, seems not using pk.

Endpoints from E results may not correct, i.e. there's not a vertex associated with it.
- [x] g.V(%s).bothE() -> [eid][srcid -> label -> dstid], then g.V(srcid/dstid) may be empty.

**Comment by siyuan0322** [comment]
`limit` seems has been fixed by some recent commits;
`count` may need to refactor the `GlobalGraphQuery` implementation in store.

**Comment by BingqingLyu** [comment]
`count` may need: 
1) maintain a meta info of number of vertices, number of edges in store, rather than count() each time; 
2) fuse `source` and `count` in plan in ir-core; 
3) support query for source+count in ir-runtime

**Comment by siyuan0322** [comment]
Fixed by a flurry of PRs. Waiting to be confirmed by real life workloads.
