### ISSUE TITLE
[BUG] can't drop edge if edge's vertex drop first on GraphScope Store

### ISSUE THREAD

**Issue by iamdrq** [alibaba/GraphScope#1933]
**Describe the bug**
can't drop edge if accidentally drop edge's vertex first on GraphScope Store

**To Reproduce**
1.create vertexA
2.create edgeB relation vertexA
3.update
4.drop vertexA
5.update
6.drop edgeB (fail)

**Expected behavior**
drop vertexA check vertexA  relation edge

**Comment by siyuan0322** [comment]
Thanks for reporting! Could you paste the codes so I can get more clear about it.
I think it should first drop e together with the src and dst, then drop e.
for example:
```python
schema.drop(E, A, A)
schema.drop(E)
schema.update()
```
Will make more clear and refine about the schema part later.
https://github.com/alibaba/GraphScope/blob/1de75338949fbcf7733bdd27328ac4500204be6c/python/graphscope/framework/graph_schema.py#L521

**Comment by iamdrq** [comment]
I know should drop edge first according to doc. yes, I accidentally drop vertex first.
```
schema.drop(A)
schema.update()
schema.drop(E, A, A)
schema.update()
```
then can't drop E

**Comment by iamdrq** [comment]
additional, I got exception when try load data from S3.

I found some key msg on coordinator pod ( I use GraphScope 0.15.0 on k8s ):
```
extra diagnostics are as follows: Cannot find such files for 's3://minio.cdst.svc.cluster.local/graph/v.csv'
/tmp/arrow-apache-arrow-1.0.1/cpp/src/arrow/result.cc:28: /tmp/arrow-apache-arrow-1.0.1/cpp/src/arrow/result.cc:28: ValueOrDie called on an error: NotImplemented: Got S3 URI but Arrow compiled without S3 supportValueOrDie called on an error: NotImplemented: Got S3 URI but Arrow compiled without S3 support
```

How install with S3 support ?

**Comment by sighingnow** [comment]
Should be a bug and needs a patch.

**Comment by sighingnow** [comment]
> Should be a bug and needs a patch.

We have to two possible solutions:

- upgrade the arrow version in the graphscope-runtime image and enables the S3 support when building arrow
- delegate s3 IO to vineyard-io module

**Comment by siyuan0322** [comment]
> I know should drop edge first according to doc. yes, I accidentally drop vertex first.
> 
> ```
> schema.drop(A)
> schema.update()
> schema.drop(E, A, A)
> schema.update()
> ```
> 
> then can't drop E

OK~ Then it's a bug then. We shouldn't let the vertex be dropped as long as there is a edge related with it. Will be fixed later. Thanks!
