### ISSUE TITLE
[BUG] Building error in compiling GAE with ENABLE_JAVA_SDK=ON

### ISSUE THREAD

**Issue by yecol** [alibaba/GraphScope#1939]
**Describe the bug**

**To Reproduce**
`make gae`

**Screenshots**
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/426463/183032416-a2fc991c-9599-4717-af8c-023408358763.png">

**Environment (please complete the following information):**
 - GraphScope version: [master]
 - OS: [e.g. MacOS 12.15, M1 chip]

**Additional context**

**Comment by zhanglei1949** [comment]
This bug has been resolved in fastffi:0.1.2, please check with  fastffi:0.1.2 from maven central.

**Comment by sighingnow** [comment]
Closing as resolved as we have already upgrade to fastffi:0.1.2.
