### ISSUE TITLE
[BUG] Unsupported data type should not crash the engine.

### ISSUE THREAD

**Issue by siyuan0322** [alibaba/GraphScope#1977]
**Describe the bug**
When encountered unsupported type when loading graphs, the engine will crash.

**Screenshots**

![19E89C41-BC89-4232-9BB7-E1A5E86F91C7](https://user-images.githubusercontent.com/8400184/185542378-3deeb3d0-d3b6-4b8a-a0a6-bf61dd9184d1.png)

**Environment (please complete the following information):**
 - GraphScope version: [e.g., v0.1, v0.2.2, master]
 - OS: [e.g. MacOS, Linux]
 - Version [e.g. 10.15]
 - Kubernetes Version [e.g., 1.19]

**Additional context**

**Comment by sighingnow** [comment]
Should a bug in vineyard.

**Comment by sighingnow** [comment]
See also: https://github.com/v6d-io/v6d/issues/926

**Comment by sighingnow** [comment]
Closed in vineyard by https://github.com/v6d-io/v6d/pull/928.
