### ISSUE TITLE
Ask for the GIE support on "g.V().label()"

### ISSUE THREAD

**Issue by TerryWang1208** [alibaba/GraphScope#2027]
I'm using v0.16. Right now the GIE does not support "label()" grammer.
Could you please consider to support this grammer? It is quite important in the Gremlin world. For example, usually we need to fetch all labels by "g.V().label().dedup()" and compare with the incoming data to see if there is a new label to add into the db.
Thanks!

**Comment by longbinlai** [comment]
> I'm using v0.16. Right now the GIE does not support "label()" grammer. Could you please consider to support this grammer? It is quite important in the Gremlin world. For example, usually we need to fetch all labels by "g.V().label().dedup()" and compare with the incoming data to see if there is a new label to add into the db. Thanks!

Thank you for using GIE. We will quickly support `label()` and `id()`.

**Comment by longbinlai** [comment]
This is relevant to the issue #2030
