### ISSUE TITLE
[BUG] macos import graphscope error

### ISSUE THREAD

**Issue by oohx** [alibaba/GraphScope#2046]
- GraphScope version: 0.16.0/0.15.0
 - OS: MacOS  x86
 - Version: 12.5
 - Python: 3.7.13
 - pip: 21.2.2
 
 1. pip install graphscope 
 2. import graphscope
 
 
![image](https://user-images.githubusercontent.com/41443157/191151237-1e78a642-2a19-41d9-bb11-981399fd7163.png)
![image](https://user-images.githubusercontent.com/41443157/191151288-d43edb0f-f83c-4ee7-92f3-c0d463ce6921.png)

**Comment by oohx** [comment]
protobuf == 3.18.3  is a failure
protobuf == 3.18.1 Succeeded

**Comment by sighingnow** [comment]
Protobuf version constraint has been fixed on main.
