### ISSUE TITLE
Bit operation query

### ISSUE THREAD

**Issue by liuyuanpeng** [alibaba/GraphScope#2067]
I need to query vertexes or edges which have a hex formatted value property.  And the value has more than 50 bits, it's not so elegant to split it in to more than 50 properties.
Bit operation is needed.
A gremlin expression query support would be fine.

**Comment by longbinlai** [comment]
Confirm that it is fine to support bit operations in integers, e.g. 232 (11101000) & 64 (01000000) != 0
