### ISSUE TITLE
[BUG] Changes on GAE `CMakeLists.template` didn't invoke necessary CI Checks

### ISSUE THREAD

**Issue by zhanglei1949** [alibaba/GraphScope#2070]
When a PR only changes CMAKELists.template, the pull request CI didn't invoke GAE CI check and some other necessary checks, see https://github.com/alibaba/GraphScope/pull/2069

**Comment by sighingnow** [comment]
The issue is not GAE CI is not triggered. The issue is GAE CI shouldn't depend on Python CI to run. Where the python is requires should be moved to python test, even where java is involved.
