### ISSUE TITLE
GLE添加java版dataloader sdk

### ISSUE THREAD

**Issue by 4613** [alibaba/GraphScope#2078]
1.目前GLE的dgs dataloader仅有c++版sdk，是否后续会添加java版sdk？

2.目前dgs的部署根据不同的schema和采样方式似乎需要部署不同实例，是否后续会开发动态启动dgs实例或者不同schema或采样可以共用一个。

**Comment by sighingnow** [comment]
Let's discuss the DGS part in graph-learn's repo.
