### ISSUE TITLE
Unify Integrated CI Test Cases for GIE on ExpStore/Groot/Vineyard

### ISSUE THREAD

**Issue by BingqingLyu** [alibaba/GraphScope#2133]
**Is your feature request related to a problem? Please describe.**

Unify Integrated CI Test Cases for GIE on exp_store/Groot/Vineyard. Currently, we have 3 entries of ci tests on different storages:
`GraphScope/interactive_engine/tests/src/test` (for Vineyard),
`GraphScope/interactive_engine/compiler/src/test` (for ExpStore),
`GraphScope/interactive_engine/groot-server/src/test` (for Groot).
The cases seems have minor differences. Still, try to unify the common ones.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by siyuan0322** [comment]
Closed as completed
