### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by JackyYangPassion** [alibaba/GraphScope#2162]
**Describe the bug**

**To Reproduce**
`
# Import the graphscope module
import os
import graphscope
graphscope.set_option(show_log=False)  # enable logging
graphscope.set_option(log_level='DEBUG') # log level
sess = graphscope.session(addr='ip:port',cluster_type='k8s', mount_dataset='/home/data/testingdata')

# Load the obgn_mag dataset as a graph
from graphscope.dataset import load_ogbn_mag
graph = load_ogbn_mag(sess,'/tmp/testingdata/')

# get the entrypoint for submitting Gremlin queries on graph g.
interactive = sess.gremlin(graph)
print(interactive.graph_url)
`

**Expected behavior**
coodinator log
`Create GIE instance with command: /home/graphscope/.local/lib/python3.8/site-packages/graphscope.runtime/bin/giectl create_gremlin_instance_on_k8s /tmp/gs/graphscope-1666685425/session_pkzhchoo 105809399820113850 /tmp/graph_7LaSXd5t.json gs-engine-graphscope-1666685425-7mxj6,gs-engine-graphscope-1666685425-lqspj engine 8239 8240 8241 graphscope-1666685425-coordinator`

juputer log 
``

**Screenshots**

**Environment (please complete the following information):**
 - GraphScope version: 0.17.0
 - OS: Linux
 - Version [e.g. 10.15]
 - Kubernetes Version 1.19.5

**Additional context**

**Comment by sighingnow** [comment]
Closing as duplicated with #2161.
