### ISSUE TITLE
Unified the version information of GIE in 'VERSION'

### ISSUE THREAD

**Issue by lidongze0629** [alibaba/GraphScope#2164]
**Is your feature request related to a problem? Please describe.**

https://github.com/alibaba/GraphScope/blob/main/interactive_engine/pom.xml#L8
https://github.com/alibaba/GraphScope/blob/main/interactive_engine/common/pom.xml#L9
https://github.com/alibaba/GraphScope/blob/main/interactive_engine/data_load_tools/pom.xml#L8

Maybe we can parse the [VERSION](https://github.com/alibaba/GraphScope/blob/main/VERSION) file in GIE engine to unify the version information.

**Comment by yecol** [comment]
Hi @longbinlai could you triage this issue to a right person to address it?
