### ISSUE TITLE
[BUG] [GraphScope-0.17.0]Load HDFS Data failed in 'k8s' GraphScope cluster

### ISSUE THREAD

**Issue by nckfssu** [alibaba/GraphScope#2173]
**Describe the bug**
My graph data is stored on HDFS and I need to load HDFS data into GraphScope cluster to do the graph analytical task. So I use `graphscope.framework.loader.Loader` to load HDFS Data into GraphScope cluster.  The k8s cluster is managed by DockerDesktop on Mac OS, and the HDFS is a single node cluster which is deployed on the host machine of the k8s cluster. And I'm sure that the network between the  GraphScope k8s cluster and the HDFS is works well. Then I found that the data load task is success when I use the `hosts cluster_type` to launch GraphScope data load task, however the data load task is failed when I use the  `k8s cluster_type` to launch GraphScope data load task. The only difference of  codes between the two mode is the different `cluster_type`. 
The code of data load task with `hosts cluster_type` is showed below:
```
import graphscope
from graphscope.framework.loader import Loader
from graphscope.client.session import get_default_session

graphscope.set_option(show_log=True)
# The default session is created with 'hosts' cluster_type
session = get_default_session()
graph = session.g()
graph = graph.add_vertices(Loader("hdfs:///GraphScope/Data/ogbn_mag_small/field_of_study.csv",
                                  host="192.168.2.152", port=9000),
                           label="field_of_study",
                           vid_field="id")
vertexLabelCount = len(graph.v_labels)
print('Vertex label count is ', vertexLabelCount, '.')
session.close()
print('============ Session closed. ==========')
```
The code of data load task with `k8s cluster_type` in Jupyter is showed below:
```
import graphscope
graphscope.set_option(show_log=True)
# Create GraphScope client session, the 'cluster_type' is k8s by default.
session = graphscope.session(
                             k8s_service_type="LoadBalancer",
                             k8s_coordinator_cpu=1,
                             k8s_coordinator_mem="2Gi",
                             k8s_etcd_cpu=1.0,
                             k8s_etcd_num_pods=1,
                             k8s_etcd_mem='1Gi',
                             k8s_vineyard_cpu=0.2,
                             k8s_vineyard_mem="1Gi",
                             vineyard_shared_mem="4Gi",
                             k8s_engine_cpu=0.2,
                             k8s_engine_mem="2Gi",
                             num_workers=1,)
print('========= Session created. ==========')

# Load data from HDFS
from graphscope.framework.loader import Loader
graph = session.g()
graph = graph.add_vertices(Loader("hdfs:///GraphScope/Data/ogbn_mag_small/field_of_study.csv",
                                  host="192.168.2.152", port=9000),
                           label="field_of_study",
                           vid_field="id")
labelCount = len(graph.v_labels)
print('Label count is ', labelCount, '.')
```

The the `hosts cluster_type` data load task works well, the log and output of console is showed in [hosts.log](https://github.com/nckfssu/graphscopelearning/blob/main/hosts.log)

But the `k8s cluster_type` data load task is failed, the code, log and output of console in JupyterLab is showed in [HdfsTest2.ipynb](https://github.com/nckfssu/graphscopelearning/blob/main/HdfsTest2.ipynb), and the log of GraphScope coordinator Pod is showed in [coordinator.log](https://github.com/nckfssu/graphscopelearning/blob/main/coordinator.log)

**To Reproduce**
1. Start an HDFS cluster.
2. Start jupyter lab.
3. Run the `hosts cluster_type`  code showed above and modify the HDFS connection param to adapt your HDFS cluster.
4. Then you'll see the data load task works well.
5. Run the `k8s cluster_type` code showed above and modify the HDFS connection param to adapt your HDFS cluster.
6. Then you'll see the error occurred.

**Expected behavior**
The data load task works well, and the result is same as the log showed in [hosts.log](https://github.com/nckfssu/graphscopelearning/blob/main/hosts.log)

**Screenshots**
The detail information is described in the urls showed above.

**Environment (please complete the following information):**
 - GraphScope version: 0.17.0
 - OS: MacOS Ventura
 - DockerDesktop for Mac, version: 4.12.0(85629)
 - Docker version: 20.10.17, build 100c701
 - Kubernetes Version v1.25.0

**Comment by sighingnow** [comment]
Looks that the HDFS loader has been broken.
