### ISSUE TITLE
Delete all deployed resources when using `helm uninstall` without a extra rbac role

### ISSUE THREAD

**Issue by dashanji** [alibaba/GraphScope#2207]
**Is your feature request related to a problem? Please describe.**
Now, we need an extra rbac role to install the graphscope chart via [the doc](https://artifacthub.io/packages/helm/graphscope/graphscope#install-chart). The main reason is that we can't delete the resources deployed by the coordinator as the `rbac role` of deleting resources has been deleted during `helm uninstall`.

**Describe the solution you'd like**
A possible way is to use the [kubernetes finializer](https://kubernetes.io/docs/concepts/overview/working-with-objects/finalizers/) to mark the rbac role of coordinator, while all resources deployed by the coordinator have been deleted, then remove the mark of rbac role during [preStop hooks](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#container-hooks).

**Comment by sighingnow** [comment]
I think adding a "OwnershipReference" would be enough to this problem, that says, all resources created by coordinator are "owned" by the "coordinator" pod/deployment.

**Comment by dashanji** [comment]
Yeah, but the relevant components are produced by `python code` not a `yaml` in the graphscope chart, so I think it's better to use the finializer here.
