### ISSUE TITLE
[BUG] graphscope-dev image has been deleted but we still use it for CI

### ISSUE THREAD

**Issue by sighingnow** [alibaba/GraphScope#2240]
**Describe the bug**

The CI looks failed every night: https://github.com/alibaba/GraphScope/actions/runs/3534940665/jobs/5932399398

If the image been droped, we shouldn't used it anywhere anymore.

**Additional context**

**Comment by siyuan0322** [comment]
Oh, it's recently added and not yet changed to public...

**Comment by sighingnow** [comment]
Failed again: https://github.com/alibaba/GraphScope/actions/runs/3534940665/jobs/5936824031
