### ISSUE TITLE
pagerank of graphscope.nx is slower than that of nx

### ISSUE THREAD

**Issue by gogogo66** [alibaba/GraphScope#2255]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I wish GraphScope can imporove it as the **clustering** does, as well as other APIs, such as **write_graphml**

**Additional context**
<img width="573" alt="a4a9977e4f5788756f7bafbba3c372c" src="https://user-images.githubusercontent.com/15956735/204718928-90a00c07-06ed-4c3c-a870-b97cac04d47f.png">

**Comment by gogogo66** [comment]
你的邮件已收到

**Comment by acezen** [comment]
how about using `ret_gs = gs_nx.builtin.pagernak(g2)` ?

**Comment by gogogo66** [comment]
Yes, it is faster than nx,about 5 times, Thanks very much.
And I'm wondering if all the APIs of nx are optimized in GraphScope or only partially supported. Is there a list or reference of those optimized APIs, thanks again!

**Comment by sighingnow** [comment]
> Is there a list or reference of those optimized APIs, thanks again!

Please refer to https://github.com/alibaba/GraphScope/blob/main/python/graphscope/nx/algorithms/builtin.py

**Comment by gogogo66** [comment]
I get it, thanks
