### ISSUE TITLE
[BUG] GIE: invalid gremlin script exception

### ISSUE THREAD

**Issue by sighingnow** [alibaba/GraphScope#2265]
**Describe the bug**

```python
interactive.subgraph("g.V().outE().endV().path().limit(10)")
```

![image](https://user-images.githubusercontent.com/7144772/204986548-14f9c73a-22cf-4c17-8ad7-46b7133ac9ae.png)

**Comment by Codelone** [comment]
coordinator log file
[frontend.log](https://github.com/alibaba/GraphScope/files/10130155/frontend.log)

**Comment by shirly121** [comment]
`path()` is unsupported yet and we only support an edge-induced subgraph currently. Use `interactive.subgraph(g.V()...outE().limit(10))` if you want to build a subgraph containing a subset of edges and both vertices of these edges.
