### ISSUE TITLE
[BUG] build binary on local with command 'make interactive' for GIE failed

### ISSUE THREAD

**Issue by yecol** [alibaba/GraphScope#2268]
**Describe the bug**
Failed to build GIE, either on local or in the graphscope-dev

**To Reproduce**
`make interactive`

**Expected behavior**
Do you use this command in the daily dev? 
We should provide a way for dev and test on local dev-env

**Comment by sighingnow** [comment]
See also: https://github.com/alibaba/GraphScope/issues/2127

Already working in progress.

**Comment by siyuan0322** [comment]
Should be address in current release.
