### ISSUE TITLE
Support C++ custom algorithms

### ISSUE THREAD

**Issue by siyuan0322** [alibaba/GraphScope#2299]
We could let user write a python algorithm and load it to GraphScope and run query with it.
However, it's pretty naive compared to C++ algorithms, we need to expose the entrypoint to plug in a UDF C++ algorithm.

**Comment by wuyueandrew** [comment]
im looking forward to c++ udf.

**Comment by sighingnow** [comment]
We do support user-defined algorithms in C++, by using a gar to initilaizing an `AppAsset`.

**Comment by siyuan0322** [comment]
Yeah，the essential components are ready but we do need to try this whole process from the beginning to the end and present it formally.

**Comment by sighingnow** [comment]
See https://github.com/GraphScope/cpp-template

**Comment by siyuan0322** [comment]
> See https://github.com/GraphScope/cpp-template

Nice template! I'll try it myself. And I need to bootstrap a pregel example.
