### ISSUE TITLE
Integrate GIE GraphManager into Coordinator

### ISSUE THREAD

**Issue by lidongze0629** [alibaba/GraphScope#235]
**Is your feature request related to a problem? Please describe.**

In GraphScope, the coordinator holds all meta info of graphs, such as schema path, object id, even the IPC socket. And copy these infos to GraphManager for gremlin instance management. Thus, I think it's better we can manage the gremlin instance by coordinator directly.

Some other pros:
-  Reduce the resource usage by deleting the GraphManager role
- No need to expose a service of GraphManager.

**Comment by yecol** [comment]
And try to using [zetcd](https://github.com/etcd-io/zetcd)
