### ISSUE TITLE
[GAIA] The query of operator 'V()' with primary key is slower than expected

### ISSUE THREAD

**Issue by lidongze0629** [alibaba/GraphScope#2361]
**Is your feature request related to a problem? Please describe.**
**Graph Schema**

Vertex label: company, size: 310 million
| property name |  type |  primary key |
| -- | -- | -- |
| onecomp_id | STRING | False |
| ent_name | STRING | False  |
| vertex_id | STRING | **True** |

Edge label: edge, size: 10M
| property name |  type |  primary key |
| -- | -- | -- |
| weight | DOUBLE | False |
| edge_id | STRING | False  |

For a vertex with `vertex_id(primary key) == '1:1180716022835080526'`. The query `g.V().has('vertex_id', '1:1180716022835080526')` takes **150 seconds** to get the result, which <1s on other's GraphDB like GDB.

```bash
gremlin> g.V().has("vertex_id", "1:1180716022835080526")  # takes 150s to get the result
==>v[-175673522527949910]

# frontend log
[2022-12-28 06:36:30,054][INFO][gremlin-server-exec-92][com.alibaba.graphscope.gremlin.plugin.processor.IrStandardOpProcessor:131] query "g.V().has("vertex_id", "1180716022835080526")" total execution time is 150131.92 ms
```

**Comment by BingqingLyu** [comment]
Try `g.V().hasLabel("company").has("vertex_id", "1:1180716022835080526")`
