### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by justwell407** [alibaba/GraphScope#2409]
**Describe the bug**
安装出错

**To Reproduce**
当我按照开发者指南（https://graphscope.io/docs/zh/developer_guide.html）的在docker中安装graphscope报错。

1、sudo docker pull registry.cn-hongkong.aliyuncs.com/graphscope/graphscope-vineyard:latest

2、# set docker container shared memory: 10G
sudo docker run --shm-size 10240m -it registry.cn-hongkong.aliyuncs.com/graphscope/graphscope-vineyard:latest /bin/bash

git clone https://github.com/alibaba/GraphScope.git

# download dataset for test
git clone https://github.com/GraphScope/gstest.git

# building
cd GraphScope 
 make install     （按照报错，报错信息如下，看起来很明显这里面的代码都没有做自测：）

CMake Error at CMakeLists.txt:237 (find_package):
  Could not find a configuration file for package "vineyard" that is
  compatible with requested version "0.11.7".

  The following configuration files were considered but not accepted:

    /usr/local/lib/cmake/vineyard/vineyard-config.cmake, version: 0.8.2
    /opt/vineyard/lib/cmake/vineyard/vineyard-config.cmake, version: 0.8.2

# testing
cd GraphScope && make minitest(unittest)

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - GraphScope version: [e.g., v0.1, v0.2.2, master]
 - OS: [e.g. MacOS, Linux]
 - Version [e.g. 10.15]
 - Kubernetes Version [e.g., 1.19]

**Additional context**

**Comment by siyuan0322** [comment]
Sorry for that the dev guide is some kind of out of date.. and we are preparing for a series of new docs, including the dev guide.

Currently, we renamed the docker to `graphscope_dev`, please use
`registry.cn-hongkong.aliyuncs.com/graphscope/graphscope-dev:latest` instead.

**Comment by justwell407** [comment]
> 

thanks, i have other troubles。 After i run sudo make install in docker, "mvn package -DskipTests -Drust.compile.mode=release -P graphscope,graphscope-assembly --quiet" hang （ running for a long time without any information)

**Comment by siyuan0322** [comment]
Try remove the `--quiet` and see what happened.
This command will take some time since it would compile java and rusts in sequential.

**Comment by sighingnow** [comment]
Closing as lack of response.

@justwell407 Feel free to reopen if there're still failures.
