### ISSUE TITLE
[BUG] Finding bugs in dogfooding 

### ISSUE THREAD

**Issue by doudoubobo** [alibaba/GraphScope#2415]
- [x] Give minimum dependencies for user to compile applications when starts from a bare docker image like ubuntu:22.04
- [ ] Run WCC on `modern_graph` occurs error

```python
import graphscope as gs
from graphscope.dataset.modern_graph import load_modern_graph
g = load_modern_graph()
ret = gs.wcc(g)
```
- [ ] ...

**Comment by sighingnow** [comment]
Can you tell us the detailed error message you have seen?

Thanks!

**Comment by doudoubobo** [comment]
> 

![image](https://user-images.githubusercontent.com/47907647/217447728-dde43951-eeee-42d8-b0b2-4945cc595eac.png)

**Comment by siyuan0322** [comment]
> Can you tell us the detailed error message you have seen?
> 
> Thanks!

@sighingnow This issue acts as the problem tracker for the dogfooding process. I'll take care of most of that~.

**Comment by siyuan0322** [comment]
Already leverage discussions to track issues.
