### ISSUE TITLE
[BUG] graph.add_vertices() The specified vid_field = 'name' is not valid

### ISSUE THREAD

**Issue by JackyYangPassion** [alibaba/GraphScope#2443]
**Describe the bug**
**demo data**
edge.csv
```
from,to,ratio
zhangsan,lisi,0.5
zhangsan,wangwu,0.6
lisi,wangwu,0.4

```
vertices.csv

```
name,age
zhangsan,100
lisi,90
wangwu,88
```

load graph
```
# Import the graphscope module
import graphscope
import os
from graphscope.framework.loader import Loader
from graphscope.client.session import get_default_session


graphscope.set_option(show_log=True)  # enable logging
sess = get_default_session()
graph = sess.g(oid_type="string",generate_eid=True,directed=False)

prefix = "/home/data/graphscope/"
graph = (
        graph.add_vertices(os.path.join(prefix, "test_vertices.csv"), "person",vid_field="name")
             .add_edges(
        os.path.join(prefix, "test_edge.csv"),
        "link",
        src_label="person",
        dst_label="person",
    )

)

# Get the entrypoint for submitting Gremlin queries on graph g.
interactive = graphscope.gremlin(graph)

querySubgraph = "g.V().has('name',within('zhangsan','lisi')).both('1..3','link').with('PATH_OPT', 'SIMPLE').with('RESULT_OPT', 'ALL_V')"
subgraph = interactive.execute(querySubgraph).all()
for one in subgraph:
    print("one: ",one)

```

get vertices:

```
one:  [v[0], v[1]]
one:  [v[0], v[2]]
one:  [v[0], v[1]]
one:  [v[0], v[2]]
one:  [v[1], v[0]]
one:  [v[1], v[2]]
one:  [v[1], v[0]]
one:  [v[1], v[2]]
```

**Expected behavior**
expect result:
```
one:  [v[zhangsan], v[lisi]]
one:  [v[zhangsan], v[wangwu]]
```

**Environment (please complete the following information):**
 - GraphScope version: v0.19.0
 - OS: Linux

**Comment by JackyYangPassion** [comment]
```
 def add_vertices(self, vertices, label="_", properties=None, vid_field=0):
        """Add vertices to the graph, and return a new graph.

        Args:
            vertices (Union[str, Loader]): Vertex data source.
            label (str, optional): Vertex label name. Defaults to "_".
            properties (list[str], optional): List of column names loaded as properties. Defaults to None.
            vid_field (int or str, optional): Column index or property name used as id field. Defaults to 0.
```
i see the args vid_field in the function.
graph.add_vertices(os.path.join(prefix, "test_vertices.csv"), "person",vid_field="name")
vid_field="name" is not valid

**Comment by JackyYangPassion** [comment]
print(graph.schema)
```
oid_type: STRING
vid_type: ULONG
type: VERTEX
Label: person
Properties: Property(0, age, LONG), Property(1, name, STRING)

type: EDGE
Label: link
Properties: Property(0, eid, LONG), Property(1, ratio, DOUBLE)
Relations: [Relation(source='person', destination='person')]
```

**Comment by siyuan0322** [comment]
try `g.V().valueMap()` instead of `g.V()`

**Comment by JackyYangPassion** [comment]
> try `g.V().valueMap()` instead of `g.V()`

g.V().has('name',within('zhangsan','lisi')).both('1..3','link').with('PATH_OPT', 'SIMPLE').with('RESULT_OPT', 'ALL_V')

get path:
path:  [v[0], v[1]]
path:  [v[0], v[2]]


expect result:
one:  [v[zhangsan], v[lisi]]
one:  [v[zhangsan], v[wangwu]]

**Comment by siyuan0322** [comment]
@JackyYangPassion the `vid_field` is used to select the primary key, and it works as expected. The reason that your expected output is differ from the actual, is the output behavior of the GIE engine.

**Comment by siyuan0322** [comment]
@longbinlai Could you confirm that the output behavior is designed like this or not?

**Comment by BingqingLyu** [comment]
@JackyYangPassion 
Hi, thanks for reporting. Actually, the output is as expected in GIE.
In GIE engine, the output result when querying for vertices (or paths), is actually the `global_id` (or consisting of `global_id`s in the path) in the engine. This is also identical to the definition in Gremlin.

For example, if you query with `g.V()`, you'll get results like:
```
one:  v[0]
one:  v[1]
one:  v[2]
```
Here, `0`, `1`, `2` are the `global_id`s (although it is not defined in the data, it can be 'recognized' by the engine). With the `global_id`s, you can further query like `g.V(0).values('name')`, and you'll get:
```
one:  "zhangsan"
```

Unlike primary key, which I think the values are identical under SPECIFIC LABELS (e.g., "person" in your example), such 'global_id' can identify a vertex in the whole graph.

In addition, for primary key query, e.g., you can query like `g.V().hasLabel("person").has("name", "zhangsan")`, which is expected to be faster than `g.V().hasLabel("person").has("age", 18)`, as "name" is a primay key.
