### ISSUE TITLE
[BUG] 设置图可使用的内存

### ISSUE THREAD

**Issue by xglreal** [alibaba/GraphScope#2472]
载入9G的亿级关系数据，报错显示4G内存不够分配。哪里可以设置该图可使用的内存大小？

**Comment by sighingnow** [comment]
See the 9th item in https://graphscope.io/docs/frequently_asked_questions.html

> What’s the relationship between k8s_vineyard_mem, vineyard_shared_mem and k8s_engine_mem?

**Comment by sighingnow** [comment]
Moving to discussion.
