### ISSUE TITLE
[BUG] Through the graphscope service constructed by helm, the role and rolebinding resources cannot be deleted normally when the application is deleted

### ISSUE THREAD

**Issue by YANGBoSunning** [alibaba/GraphScope#2506]
**Describe the bug**
Through the graphscope service constructed by helm, the role and rolebinding resources cannot be deleted normally when the application is deleted.

**To Reproduce**
1. helm install graphscope with the version 0.18.0
2. delete the namespace 
3. The namespace is always in the deleted state and there are some resources like role and rolebinding always exist

**Expected behavior**

**Screenshots**
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/23427842/224601650-a2e04474-557c-4bf3-9146-7905f15b97b3.png">
<img width="756" alt="image" src="https://user-images.githubusercontent.com/23427842/224601707-4f08cc2b-f84d-460a-b5fe-3731e38dbc06.png">

**Environment (please complete the following information):**
 - GraphScope version: v0.18.0
 - OS: Linux(Ubuntu18.04)
 - Kubernetes Version:1.22.10

**Comment by sighingnow** [comment]
Have been fixed by https://github.com/alibaba/GraphScope/pull/2350, which has already been included in our latest release v0.19.0.

Closing as already fixed. Thanks for reporting!
