### ISSUE TITLE
Enable proxy settings for dataset in values of helm

### ISSUE THREAD

**Issue by YANGBoSunning** [alibaba/GraphScope#2512]
**Is your feature request related to a problem? Please describe.**
The dataset container of graphscope provides the function of obtaining sample dataset online, but there are many inconveniences in accessing the external network to obtain data in many Intranet environments. Therefore, the option of configuring the proxy service address for the dataset container should be added to the configuration file of helm

**Describe the solution you'd like**
In the values file of helm, add the configuration item proxy of dataset.

**Describe alternatives you've considered**
I provided the corresponding configuration of dataset in the values file of helm, modified the cluster_builder.py coordinator.py kubernetes_launcher.py, and added a dataset_proxy attribute in the corresponding classes

**Additional context**

**Comment by siyuan0322** [comment]
> I provided the corresponding configuration of dataset in the values file of helm, modified the cluster_builder.py coordinator.py kubernetes_launcher.py, and added a dataset_proxy attribute in the corresponding classes

Great! Have you already roll out a working version? Would you consider to submit a PR to address this?

**Comment by YANGBoSunning** [comment]
please hold on, i will push it some minutes later.

**Comment by YANGBoSunning** [comment]
我很抱歉 我们部署是用的0.19.0版本，main分支的代码我们还没有做实际部署。期待您的review @siyuan0322

**Comment by YANGBoSunning** [comment]
I'm sorry that we used version 0.19.0 for deployment. We haven't actually deployed the code of main branch yet. Looking forward to your review @siyuan0322
