### ISSUE TITLE
[BUG] typo in slogan

### ISSUE THREAD

**Issue by Amber1990Zhang** [alibaba/GraphScope#252]
![image](https://user-images.githubusercontent.com/42762957/114977086-b05dae80-9eb9-11eb-8b66-5017d0bb8d85.png)
An open

**Comment by Amber1990Zhang** [comment]
![image](https://user-images.githubusercontent.com/42762957/114977135-c79c9c00-9eb9-11eb-8459-12c4c2b7d20e.png)
same here

**Comment by yecol** [comment]
Hi @Amber1990Zhang, 

Thanks for your careful check and the kind advice!
I guess [“A one” is correct because “one” starts with a “w” sound. ](https://www.quora.com/Which-is-correct-a-one-or-an-one)
