### ISSUE TITLE
[BUG] Run subgraph failed on local

### ISSUE THREAD

**Issue by JackyYangPassion** [alibaba/GraphScope#2596]
**Describe the bug**
Run subgraph failed on local

**To Reproduce**
```
# Import the graphscope module
import graphscope
import os
# 单机验证 加载图数据 from HDFS
from graphscope.framework.loader import Loader
from graphscope.client.session import get_default_session


graphscope.set_option(show_log=True)  # enable logging
session = graphscope.session(cluster_type="hosts", num_workers=1)
graph = session.g(oid_type="string")

prefix = "/dataset/subgraph"
graph = (
        graph.add_vertices(os.path.join(prefix, "186_vertices.csv"), label="address",vid_field="address")
        .add_edges(
                os.path.join(prefix, "186.csv"),
                "transaction",
                src_label="address",
                dst_label="address",
                src_field='from',
                dst_field='to'
    )

)

# Get the entrypoint for submitting Gremlin queries on graph g.
interactive = session.gremlin(graph)

```

when run this 
```
sub_graph = interactive.subgraph("g.V().outE()")
```
error log
```
I20230411 11:31:57.688288 25077 /work/analytical_engine/core/grape_instance.cc:144] Loading graph, graph name: graph_jzhMaiRr, graph type: ArrowFragment, type sig: f2982087e4f61dc89675375a632a28210b9370606f6bc2791ca14223feef8b0b

[warn] Warning: this version of vineyard client may be incompatible with connected server: client's version is 0.13.3, while the server's version is 0.11.7
[warn] Warning: this version of vineyard client may be incompatible with connected server: client's version is 0.13.3, while the server's version is 0.11.7
2023-04-11 11:31:57,705 [ERROR][rpc:188]: Runstep failed with code: INTERACTIVE_ENGINE_INTERNAL_ERROR, message: Error occurred during RunStep. The traceback is: Traceback (most recent call last):
  File "/home/airflow/.conda/envs/py39/lib/python3.9/site-packages/gscoordinator/coordinator.py", line 318, in _RunStep
    head, bodies = self._operation_executor.run_on_interactive_engine(
  File "/home/airflow/.conda/envs/py39/lib/python3.9/site-packages/gscoordinator/monitor.py", line 210, in runOnInteractiveEngineWarp
    res = func(instance, dag_def)
  File "/home/airflow/.conda/envs/py39/lib/python3.9/site-packages/gscoordinator/op_executor.py", line 446, in run_on_interactive_engine
    op_result = self._gremlin_to_subgraph(op)
  File "/home/airflow/.conda/envs/py39/lib/python3.9/site-packages/gscoordinator/op_executor.py", line 712, in _gremlin_to_subgraph
    gremlin_client.submit(
  File "/home/airflow/.conda/envs/py39/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/home/airflow/.conda/envs/py39/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/airflow/.conda/envs/py39/lib/python3.9/site-packages/gremlin_python/driver/resultset.py", line 90, in cb
    f.result()
  File "/home/airflow/.conda/envs/py39/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/home/airflow/.conda/envs/py39/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/airflow/.conda/envs/py39/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/airflow/.conda/envs/py39/lib/python3.9/site-packages/gremlin_python/driver/connection.py", line 90, in _receive
    status_code = self._protocol.data_received(data, self._results)
  File "/home/airflow/.conda/envs/py39/lib/python3.9/site-packages/gremlin_python/driver/protocol.py", line 138, in data_received
    raise GremlinServerError(message['status'])
gremlin_python.driver.protocol.GremlinServerError: 500: Status{code=UNAVAILABLE, description=Network closed for unknown reason, cause=null}
```

**Environment (please complete the following information):**
 - GraphScope version: 0.20.0
 - OS: Linux

**Comment by siyuan0322** [comment]
Could you find the log of frontend, in `~/.local/log/graphscope` or `/var/log/graphscope`

**Comment by JackyYangPassion** [comment]
```
[grpc-default-executor-0] ERROR com.alibaba.pegasus.RpcClient - get job response error: Status{code=UNAVAILABLE, description=Network closed for unknown reason, cause=null}
[grpc-default-executor-0] ERROR com.alibaba.pegasus.common.StreamIterator - iterator failed
io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
	at io.grpc.Status.asRuntimeException(Status.java:539)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:563)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:744)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
[gremlin-server-exec-2] ERROR com.alibaba.graphscope.common.client.RpcBroadcastProcessor - get result from grpc returns error {}
java.lang.RuntimeException: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
	at com.alibaba.pegasus.common.StreamIterator.hasNext(StreamIterator.java:47)
	at com.alibaba.pegasus.common.StreamIterator.next(StreamIterator.java:64)
	at com.alibaba.graphscope.common.client.RpcBroadcastProcessor.broadcast(RpcBroadcastProcessor.java:53)
	at com.alibaba.graphscope.gremlin.plugin.processor.IrStandardOpProcessor.processTraversal(IrStandardOpProcessor.java:337)
	at com.alibaba.graphscope.gremlin.plugin.processor.IrStandardOpProcessor.lambda$createLifeCycle$3(IrStandardOpProcessor.java:285)
	at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$0(GremlinExecutor.java:283)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
	at io.grpc.Status.asRuntimeException(Status.java:539)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:563)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:744)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	... 3 more
[gremlin-server-exec-2] INFO com.alibaba.graphscope.gremlin.plugin.processor.IrStandardOpProcessor - query "g.V().outE().subgraph('subgraph-20230411121103-1112245')" total execution time is 80.42139 ms
[gremlin-server-exec-2] INFO MetricLog - 5 | g.V().outE().subgraph('subgraph-20230411121103-1112245') | true | 80.42139 | 1681215064784
```

**Comment by JackyYangPassion** [comment]
```
[warn] Warning: this version of vineyard client may be incompatible with connected server: client's version is 0.13.3, while the server's version is 0.11.7
I20230411 12:11:04.836063 13951 property_graph_stream.cc:590] total_stream_chunks_ = 2
I20230411 12:11:04.836189 13951 property_graph_stream.cc:600] local stream chunk size: 2
I20230411 12:11:04.836295 13951 graph_builder_ffi.cc:178] initialize graph: builder = 0x7f2880023920
I20230411 12:11:04.836310 13951 property_graph_stream.cc:236] Initialize the graph builder using schema ...
I20230411 12:11:04.846407 13951 property_graph_stream.cc:96] prop.id = 1, address -> 0x56495c6d9970
I20230411 12:11:04.846629 13951 property_graph_stream.cc:96] prop.id = 2, eid -> 0x56495c6e4770
I20230411 12:11:04.846729 13951 property_graph_stream.cc:264] vertex_finished_ = 0, 0x7f2880004300
I20230411 12:11:04.846743 13951 property_graph_stream.cc:265] edge_finished_ = 0, 0x7f2880004300
I20230411 12:11:04.846751 13951 property_graph_stream.cc:267] The graph builder is initialized using schema
2023-04-11 12:11:04.846936204 INFO  (/work/interactive_engine/executor/ir/graph_proxy/src/adapters/gs_store/partitioner.rs:153) [tokio-runtime-worker] job_workers 2, worker id: 1,  worker_partition_list [1]
I20230411 12:11:04.849503 13951 property_graph_stream.cc:590] total_stream_chunks_ = 2
I20230411 12:11:04.849614 13951 property_graph_stream.cc:600] local stream chunk size: 2
I20230411 12:11:04.849699 13951 graph_builder_ffi.cc:178] initialize graph: builder = 0x7f288004d730
I20230411 12:11:04.849707 13951 property_graph_stream.cc:236] Initialize the graph builder using schema ...
I20230411 12:11:04.855044 13951 property_graph_stream.cc:96] prop.id = 1, address -> 0x56495c6d9970
I20230411 12:11:04.855182 13951 property_graph_stream.cc:96] prop.id = 2, eid -> 0x56495c6e4770
I20230411 12:11:04.855273 13951 property_graph_stream.cc:264] vertex_finished_ = 0, 0x7f2880053830
I20230411 12:11:04.855286 13951 property_graph_stream.cc:265] edge_finished_ = 0, 0x7f2880053830
I20230411 12:11:04.855294 13951 property_graph_stream.cc:267] The graph builder is initialized using schema
2023-04-11 12:11:04.855423875 INFO  (/work/interactive_engine/executor/engine/pegasus/pegasus/src/lib.rs:283) [tokio-runtime-worker] spawn job_ir_plan_5(5) with 2 workers;
F20230411 12:11:04.855672 13965 global_store_ffi.cc:126] get_outer_id is not supported on string fragment
*** Check failure stack trace: ***
```

"get_outer_id is not supported on string fragment" ?

**Comment by JackyYangPassion** [comment]
I want to implement LPA with GraphScope: 
three step:
1.  load graph
2. sub_graph = interactive.subgraph("g.V().has('address',within(%s)).in('0..%d','transactions').with('RESULT_OPT', 'ALL_V').with('PATH_OPT', 'SIMPLE').dedup()")
3. result_lpa = graphscope.lpa(sub_graph, max_round=20)

but when load graph set oid_type="string"
graph = session.g(oid_type="string") 

like this vertices id:
a
b
c
....
e

May I ask if there is any good way to implement it?

**Comment by sighingnow** [comment]
> May I ask if there is any good way to implement it?

Preprocess you source data to int OID.

**Comment by BingqingLyu** [comment]
> sub_graph = interactive.subgraph("g.V().outE().outE()")

Hi, `g.V().outE().outE()` is not a valid gremlin query. You can query like:
`sub_graph = interactive. Subgraph("g.V().out().outE()")`

**Comment by BingqingLyu** [comment]
> Firstly change OID to int
> 
> ```
> sub_graph = interactive.subgraph("g.V().outE()")
> ```
> 
> it's run success!
> 
> BTW when run this:
> 
> ```
> sub_graph = interactive.subgraph("g.V().outE().outE()")
> ```
> 
> there is some error in the log of frontend
> 
> ```
> [gremlin-server-exec-2] INFO com.alibaba.graphscope.gremlin.plugin.processor.IrStandardOpProcessor - gremlin query "g.V().outE().outE().subgraph('subgraph-20230412133940-8475289')", job conf name "ir_plan_5", ir plan {
>   "nodes": [
>     {
>       "opr": {
>         "opr": {
>           "Scan": {
>             "scan_opt": 0,
>             "alias": null,
>             "params": {
>               "tables": [],
>               "columns": [],
>               "is_all_columns": false,
>               "limit": null,
>               "predicate": null,
>               "sample_ratio": 1.0,
>               "extra": {}
>             },
>             "idx_predicate": null,
>             "meta_data": null
>           }
>         }
>       },
>       "children": [
>         1
>       ]
>     },
>     {
>       "opr": {
>         "opr": {
>           "Edge": {
>             "v_tag": null,
>             "direction": 0,
>             "params": {
>               "tables": [],
>               "columns": [],
>               "is_all_columns": false,
>               "limit": null,
>               "predicate": null,
>               "sample_ratio": 1.0,
>               "extra": {}
>             },
>             "alias": null,
>             "expand_opt": 1,
>             "meta_data": null
>           }
>         }
>       },
>       "children": [
>         2
>       ]
>     },
>     {
>       "opr": {
>         "opr": {
>           "Edge": {
>             "v_tag": null,
>             "direction": 0,
>             "params": {
>               "tables": [],
>               "columns": [],
>               "is_all_columns": true,
>               "limit": null,
>               "predicate": null,
>               "sample_ratio": 1.0,
>               "extra": {}
>             },
>             "alias": null,
>             "expand_opt": 1,
>             "meta_data": null
>           }
>         }
>       },
>       "children": [
>         3,
>         4
>       ]
>     },
>     {
>       "opr": {
>         "opr": {
>           "As": {
>             "alias": null
>           }
>         }
>       },
>       "children": [
>         6
>       ]
>     },
>     {
>       "opr": {
>         "opr": {
>           "Vertex": {
>             "tag": null,
>             "opt": 3,
>             "params": {
>               "tables": [],
>               "columns": [],
>               "is_all_columns": true,
>               "limit": null,
>               "predicate": null,
>               "sample_ratio": 1.0,
>               "extra": {}
>             },
>             "alias": null,
>             "meta_data": null
>           }
>         }
>       },
>       "children": [
>         5
>       ]
>     },
>     {
>       "opr": {
>         "opr": {
>           "Dedup": {
>             "keys": [
>               {
>                 "tag": null,
>                 "property": null,
>                 "node_type": null
>               }
>             ]
>           }
>         }
>       },
>       "children": [
>         6
>       ]
>     },
>     {
>       "opr": {
>         "opr": {
>           "Union": {
>             "parents": [
>               3,
>               5
>             ]
>           }
>         }
>       },
>       "children": [
>         7
>       ]
>     },
>     {
>       "opr": {
>         "opr": {
>           "Sink": {
>             "tags": [
>               {
>                 "key": null
>               }
>             ],
>             "sink_target": {
>               "inner": {
>                 "SinkVineyard": {
>                   "graph_name": "subgraph-20230412133940-8475289",
>                   "graph_schema": null
>                 }
>               }
>             }
>           }
>         }
>       },
>       "children": []
>     }
>   ],
>   "roots": [
>     0
>   ]
> }
> [grpc-default-executor-0] ERROR com.alibaba.pegasus.RpcClient - get job response error: Status{code=UNKNOWN, description=execution_error: user error: kind(Unknown), caused by:Unexpected data type in exec Cannot Expand from current entry DynEntry { inner: Edge { id: 3, label: Some(1), src_id: 0, dst_id: 4, src_label: Some(0), dst_label: Some(0), from_src: true, details: Lazy(gs_store LazyEdgeDetails { properties: None, inner: 0x7f472401dc00 }) } }, cause=null}
> [grpc-default-executor-0] ERROR com.alibaba.pegasus.common.StreamIterator - iterator failed
> io.grpc.StatusRuntimeException: UNKNOWN: execution_error: user error: kind(Unknown), caused by:Unexpected data type in exec Cannot Expand from current entry DynEntry { inner: Edge { id: 3, label: Some(1), src_id: 0, dst_id: 4, src_label: Some(0), dst_label: Some(0), from_src: true, details: Lazy(gs_store LazyEdgeDetails { properties: None, inner: 0x7f472401dc00 }) } }
> 	at io.grpc.Status.asRuntimeException(Status.java:539)
> 	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487)
> 	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:563)
> 	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
> 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:744)
> 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
> 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
> 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:750)
> [gremlin-server-exec-2] ERROR com.alibaba.graphscope.common.client.RpcBroadcastProcessor - get result from grpc returns error {}
> java.lang.RuntimeException: io.grpc.StatusRuntimeException: UNKNOWN: execution_error: user error: kind(Unknown), caused by:Unexpected data type in exec Cannot Expand from current entry DynEntry { inner: Edge { id: 3, label: Some(1), src_id: 0, dst_id: 4, src_label: Some(0), dst_label: Some(0), from_src: true, details: Lazy(gs_store LazyEdgeDetails { properties: None, inner: 0x7f472401dc00 }) } }
> 	at com.alibaba.pegasus.common.StreamIterator.hasNext(StreamIterator.java:47)
> 	at com.alibaba.pegasus.common.StreamIterator.next(StreamIterator.java:64)
> 	at com.alibaba.graphscope.common.client.RpcBroadcastProcessor.broadcast(RpcBroadcastProcessor.java:53)
> 	at com.alibaba.graphscope.gremlin.plugin.processor.IrStandardOpProcessor.processTraversal(IrStandardOpProcessor.java:337)
> 	at com.alibaba.graphscope.gremlin.plugin.processor.IrStandardOpProcessor.lambda$createLifeCycle$3(IrStandardOpProcessor.java:285)
> 	at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$0(GremlinExecutor.java:283)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:750)
> Caused by: io.grpc.StatusRuntimeException: UNKNOWN: execution_error: user error: kind(Unknown), caused by:Unexpected data type in exec Cannot Expand from current entry DynEntry { inner: Edge { id: 3, label: Some(1), src_id: 0, dst_id: 4, src_label: Some(0), dst_label: Some(0), from_src: true, details: Lazy(gs_store LazyEdgeDetails { properties: None, inner: 0x7f472401dc00 }) } }
> 	at io.grpc.Status.asRuntimeException(Status.java:539)
> 	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487)
> 	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:563)
> 	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
> 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:744)
> 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
> 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
> 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
> 	... 3 more
> [gremlin-server-exec-2] INFO com.alibaba.graphscope.gremlin.plugin.processor.IrStandardOpProcessor - query "g.V().outE().outE().subgraph('subgraph-20230412133940-8475289')" total execution time is 71.06462 ms
> [gremlin-server-exec-2] INFO MetricLog - 5 | g.V().outE().outE().subgraph('subgraph-20230412133940-8475289') | true | 71.06462 | 1681306781996
> ```

Hi @JackyYangPassion , g.V().interactive. Subgraph a valid gremlin query. You can query like:
sub_graph = interactive. Subgraph("g.V().out().outE()")

**Comment by JackyYangPassion** [comment]
DataSet
Vertices
```
id
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
```
Edges

```
from,to
2,6
0,16
0,11
0,4
3,13
0,7
0,14
0,10
1,17
2,5
3,9
2,8
9,15
2,12
```

when run lpa
```
# 查看算法结果
# run builtin applications
result_lpa = graphscope.lpa(sub_graph_with_path)
result_lpa.to_dataframe({"node": "v.id", "result": "r"})
```

the result:
![image](https://user-images.githubusercontent.com/13795366/231680118-10f8c811-54b7-44f7-b48a-2ae04945d376.png)


Use networkX 
Original Graph before clustering.
![image](https://user-images.githubusercontent.com/13795366/231680849-4136c654-4baf-4581-b3a6-e4c0f831c069.png)

Results after clustering.
![image](https://user-images.githubusercontent.com/13795366/231680910-9308309b-b2fc-4c23-bb71-6e6a69f63199.png)

I want to know how can get the result like networkX with graphScope lpa

for example
community 0 [node_list]
community 1 [node_list]
.....
community n [node_list]

**Comment by sighingnow** [comment]
Closing as the subgraph issue has been resolved.

If you have any further issue about networkx or GAE or something else, please open new issue or discussion thread for it.
