### ISSUE TITLE
Add ARM support for GraphScope

### ISSUE THREAD

**Issue by siyuan0322** [alibaba/GraphScope#2644]
Arm 架构的流行度越来越高，很多优秀国产芯片也拥抱 Arm 架构。因此，支持 Arm 平台将有助于扩大 GraphScope 的用户群体，提高 GraphScope 的使用率和影响力。同时，支持 ARM 平台还可以为用户提供更多的算力选择，满足不同用户的需求。

本项目旨在增加 GraphScope 对于 Arm 平台的支持。我们将通过构建持续集成和持续交付，保证 nightly build  可以每天晚上产出各计算引擎最新版本的镜像和  wheel package，并且，在 Arm 平台上执行单机和k8s两种方式的单元测试。

作为入手，我们将目标定为能够在运行 Ubuntu 22.04 的 Arm 机器上运行 GraphScope。所有镜像的基础镜像也将是 Ubuntu 22.04。

产出：
1. GraphScope 各引擎、存储的 arm64 版本镜像 (dockerfiles)
2. 基于 Arm64 镜像的 k8s 单元测试
3. 基于 GitHub Actions 的 CI 流程 (workflow 文件), 随版本发布自动构建和交付 Arm 平台各引擎镜像，并完成 CI 单元测试

**Comment by lidongze0629** [comment]
预热准备:

2. 基于 Amd64 构建各引擎镜像的[CI](https://github.com/alibaba/GraphScope/blob/main/.github/workflows/build-graphscope-images-linux.yml)

**Comment by FLYLX** [comment]
> 
完成了graphscope-dev和vineyard-dev在arm的dockerfile和makefile的配置以及部署，接下来是测试各个引擎是否可以使用。

**Comment by FLYLX** [comment]
> 任务排期 1.GraphScope各引擎、存储的arm64版本镜像（dockerfiles） 开始时间：2023年7月13日 结束时间：2023年8月7日
> 
> 2.基于Arm64镜像k8s单元测试 开始时间：2023年8月8日 结束时间：2023年8月14日
> 
> 3.基于GitHub Actions的CI流程（workflow文件），随版本发布自动构建和交付Arm平台各引擎像，并完成CI单元 开始时间：2023年8月15日 结束：2023年8月20日

完成了graphscope-dev和vineyard-dev在arm的dockerfile和makefile的配置以及部署，接下来是测试各个引擎是否可以使用。

**Comment by FLYLX** [comment]
> > 任务排期 1.GraphScope各引擎、存储的arm64版本镜像（dockerfiles） 开始时间：2023年7月13日 结束时间：2023年8月7日
> > 2.基于Arm64镜像k8s单元测试 开始时间：2023年8月8日 结束时间：2023年8月14日
> > 3.基于GitHub Actions的CI流程（workflow文件），随版本发布自动构建和交付Arm平台各引擎像，并完成CI单元 开始时间：2023年8月15日 结束：2023年8月20日
> 
> 完成了graphscope-dev和vineyard-dev在arm的dockerfile和makefile的配置以及部署，接下来是测试各个引擎是否可以使用。

在arm环境，配置好了dev环境的前提下，完成了gae，gle，gie和groot存储的dockerfile，并且确保了镜像能正常build。

**Comment by lidongze0629** [comment]
> > > 任务排期 1.GraphScope各引擎、存储的arm64版本镜像（dockerfiles） 开始时间：2023年7月13日 结束时间：2023年8月7日
> > > 2.基于Arm64镜像k8s单元测试 开始时间：2023年8月8日 结束时间：2023年8月14日
> > > 3.基于GitHub Actions的CI流程（workflow文件），随版本发布自动构建和交付Arm平台各引擎像，并完成CI单元 开始时间：2023年8月15日 结束：2023年8月20日
> > 
> > 
> > 完成了graphscope-dev和vineyard-dev在arm的dockerfile和makefile的配置以及部署，接下来是测试各个引擎是否可以使用。
> 
> 在arm环境，配置好了dev环境的前提下，完成了gae，gle，gie和groot存储的dockerfile，并且确保了镜像能正常build。

@FLYLX Nice job! 最终我们需要:

**1. 将 arm64 下构建镜像的流程集成进 Github CI**
- 参考 [build-graphscope-images-linux](https://github.com/alibaba/GraphScope/blob/main/.github/workflows/build-graphscope-images-linux.yml) 集成构建 coordinator、analytical、analytical-java、interactive-frontend、interactive-executor、learning 镜像，不用管 [dataset 镜像](https://github.com/alibaba/GraphScope/blob/main/.github/workflows/build-graphscope-images-linux.yml#L126)  
- 参考  [release.yml](https://github.com/alibaba/GraphScope/blob/main/.github/workflows/release.yml)  集成构建 groot 镜像
- 参考 [github-ci-workflows 文档](https://docs.github.com/en/actions/using-workflows/about-workflows) 了解 workflow 文件编写规则
- 参考 [build-graphscope-wheels-linux](https://github.com/alibaba/GraphScope/blob/main/.github/workflows/build-graphscope-wheels-linux.yml#L25) 将 CI 的调度到 [已有的 arm64 机器](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners) 上运行 `runs-on: [self-hosted, Linux, ARM64]`
- 注意需要是用 [docker manifest 命令](https://docs.docker.com/engine/reference/commandline/manifest/) 来构建跨平台镜像，以下是一些命令供参考
- 注意不要新增加 dockerfile 文件，如 arm 环境下的 dockerfile 如与 [k8s/dockerfiles](https://github.com/alibaba/GraphScope/tree/main/k8s/dockerfiles) 下的已有的 dockerfile 有改动，可参考[这里](https://github.com/alibaba/GraphScope/blob/main/k8s/dockerfiles/manylinux2014-ext.Dockerfile#L17)做兼容性修改；其中由于 graphscope-dev 镜像不在 CI 流程中，因此只需要考虑兼容性修改即可
```bash

export REGISTRY=registry.cn-hongkong.aliyuncs.com

# On x86_64 platform tag: v0.14.0-amd64
docker build xxx -t graphscope/graphscope-dev:v0.14.0-amd64

# On Arm64 platform tag: 0.14.0-arm64
docker build xxx -t graphscope/graphscope-dev:v0.14.0-arm64

# On whatever platform, create manifest and push 
docker manifest create $REGISTRY/graphscope/graphscope-dev:v0.14.0 $REGISTRY/graphscope/graphscope-dev:v0.14.0-arm64 $REGISTRY/graphscope/graphscope-dev:v0.14.0-amd64

docker manifest push $REGISTRY/graphscope/graphscope-dev:v0.14.0
```

**2. 基于 Arm64 镜像的 k8s 单元测试**
- TODO

**Comment by lidongze0629** [comment]
@FLYLX [已交pr](https://github.com/alibaba/GraphScope/pull/3070/files) 需要以下修改:

1. 不需要额外增加任何 dockefile，arm64/arm64 可共用一组 dockerfile
2. 不需要修改任何 makefile

为了使 issue 更具逻辑性，可考虑先完成前置 issue https://github.com/alibaba/GraphScope/issues/3074

**Comment by lidongze0629** [comment]
第二个 pr: (graphscope-dev analytical analytical-java interactive learning groot)

- dockerfiles + makefile 的修改都基于原文件做兼容性修改
- graphscope-dev: 参考[这个文件](https://github.com/alibaba/GraphScope/blob/main/.github/workflows/build-graphscope-dev-images.yml) 在改问价上加新的 job 就可以了
- analytical analytical-java interactive learning: 改[这个文件](https://github.com/alibaba/GraphScope/blob/main/.github/workflows/build-graphscope-images-linux.yml) 支持 arm64
- groot 改[这个文件](https://github.com/alibaba/GraphScope/blob/main/.github/workflows/release.yml)
