### ISSUE TITLE
[BUG] Out-of-memory Error when loading a new graph

### ISSUE THREAD

**Issue by EricaGuoQiuyu** [alibaba/GraphScope#2672]
**Describe the bug**
In *registry.cn-hongkong.aliyuncs.com/graphscope/graphscope-dev:latest* where graphscope is compiled and installed, when I try to load a new <a href="https://repository.surfsara.nl/datasets/cwi/lsqb" target="_blank">dataset</a> *social-network-sf3-merged-fk.tar.zst(compressed size 300M)*, I get an **out of memory** error like this:

```shell
/opt/graphscope/include/graphscope/frame/property_graph_frame.cc:361: AddLabelsToGraph -> Check 
failed: Not enough memory: Failed to allocate memory of size 10467840, total available memory size 
are 4294967296, and 4285825152 are already in use in "client.CreateBlob(size * sizeof(T), buffer_)", 
in function vineyard::PodArrayBuilder<T>::PodArrayBuilder(vineyard::Client&, size_t) [with T = 
vineyard::property_graph_utils::NbrUnit<long unsigned int, long unsigned int>; size_t = long unsigned
int], file /tmp/gs-local-deps/v6d-0.14.0/modules/basic/ds/arrow.h, line 231...
```
Is this memory usage reasonable?
The available memory of this container is :
```shell
free -m
               total        used        free      shared  buff/cache   available
Mem:          515481       67746      267575         247      180158      444152
```
The maximum memory usage when loading this dataset is monitored to be **no more than 13G** before reporting an out-of-memory. But the error message shows a memory usage of almost all **40G**. And other code with memory usage **over 36G** can be tested successfully in this environment.
Smaller dataset *social-network-sf0.3-merged-fk.tar.zst* can be loaded correctly. 

**To Reproduce**
1. Download the <a href="https://repository.surfsara.nl/datasets/cwi/lsqb" target="_blank">dataset</a> *social-network-sf3-merged-fk.tar.zst*, separate the *vertex* csv files and *edge* csv files into two folders.
2. Load dataset with:
```python
import graphscope as gs
import pandas as pd
import os

#set path
vertex_path = '/root/social-network-sf3-merged-fk/VertexFile/'
edge_path = '/root/social-network-sf3-merged-fk/EdgeFile/'
vertex_file = os.listdir(vertex_path)
edge_file = os.listdir(edge_path)

#construct session
sess = gs.session(cluster_type='hosts')
graph = sess.g()

#read vetex csv
for i in vertex_file:
   data = pd.read_csv(vertex_path + i, sep='|')
   vertex_label = os.path.splitext(i)[0]
   graph = graph.add_vertices(data, label=vertex_label)

#read edge csv
for i in edge_file:
   data = pd.read_csv(edge_path + i, sep='|')
   edge_label = os.path.splitext(i)[0]
   src = edge_label.split('_')[0]
   dst = edge_label.split('_')[2]
   graph = graph.add_edges(data, label = edge_label, src_label = src, dst_label = dst)

print(graph.schema)
sess.close()
```
3. Monitor real-time memory usage

**Expected behavior**
When the actual memory usage is only around 13G, an out-of-memory error is reported and the output shows an inflated memory usage value.

**Environment (please complete the following information):**
 - GraphScope version: [v0.22.0]
 - OS: [Ubuntu20.04]
 - Vineyard [0.14.3]

**Comment by EricaGuoQiuyu** [comment]
你好，你的来信我已收到！

**Comment by sighingnow** [comment]
Try `graphscope.set_option(vineyard_shared_mem="512G")` at the beginning to change the setting of the default session.

**Comment by siyuan0322** [comment]
>  But the error message shows a memory usage of almost all 40G. 

It's actually 4G

**Comment by sighingnow** [comment]
> > Try `graphscope.set_option(vineyard_shared_mem="512G")` at the beginning to change the setting of the default session.
> 
> Thank you very much! The problem has been solved.

FYI: We have improved the initialization of the default value for local sessions in #2678.
