### ISSUE TITLE
[BUG] Wrong query answer

### ISSUE THREAD

**Issue by EricaGuoQiuyu** [alibaba/GraphScope#2673]
**Describe the bug**
When I query for vertex properties, I get the wrong answer like **v[-9151314442816847839]**.

**To Reproduce**
```python
import graphscope as gs
from graphscope.dataset import load_ogbn_mag

sess = gs.session(cluster_type='hosts')
g_ogbn_mag = load_ogbn_mag(sess)
interactive = gs.gremlin(g_ogbn_mag)

Q1 = interactive.execute("g.V().hasLabel('author').has('id', 2)").one()
Q2 = interactive.execute("g.V().hasLabel('author').has('id', 315)").one()
Q3 = interactive.execute("g.V().hasLabel('author').has('id', -1)").one()

print(Q1)
print(Q2)
print(Q3)
sess.close()
```

**Expected behavior**
Output:
```shell
[v[72057594037971204]]
[v[-9151314442816847839]]
[]
```

**Environment (please complete the following information):**
 - registry.cn-hongkong.aliyuncs.com/graphscope/graphscope-dev:latest
 - GraphScope version: [v0.22.0]
 - OS: [Linux]

**Additional context**
When I do a pattern matching query, I also get some matches like [v[-9151314442816847839]].

**Comment by sighingnow** [comment]
I think returning the internal id for `g.V()` query is the expected/by-design behaviour. Try `g.V().....valueMap()` for properites.

**Comment by yecol** [comment]
Exactly. Also check the doc about inner ID & property ID here. 
https://graphscope.io/docs/latest/interactive_engine/faq.html#whats-the-difference-between-inner-id-and-property-id

**Comment by EricaGuoQiuyu** [comment]
Thank you for your attention!
But, I still don't quite understand it, it seems `has('id', 315)` should not return an Inner ID, as vertices 'author' have a property 'id'.
Besides, when I used the [Subgraph Query Benchmark](https://repository.surfsara.nl/datasets/cwi/lsqb) for simple pattern matching tests:
 ```python
interactive.execute("g.V().match(as('v1').both('Person_knows_Person').as('v2'), as('v2').both('Person_knows_Person').as('v3'), as('v3').both('Person_knows_Person').as('v1'))").one()
```

I got the result:
```shell
[{'v1': v[-9223372036854765637], 'v2': v[-9223372036854771638], 'v3': v[3375]}, {'v1': v[-9223372036854770418], 'v2': v[3535], 'v3': v[3376]}, {'v1': v[-9223372036854766730], 'v2': v[3535], 'v3': v[3376]}, {'v1': v[-9223372036854766714], 'v2': v[3535], 'v3': v[3376]}, {'v1': v[-9223372036854765974], 'v2': v[3535], 'v3': v[3376]}, {'v1': v[-9223372036854763780], 'v2': v[3535], 'v3': v[3376]}, {'v1': v[1947], 'v2': v[3535], 'v3': v[3376]}, {'v1': v[11247], 'v2': v[3535], 'v3': v[3376]}, {'v1': v[-9223372036854771008], 'v2': v[3653], 'v3': v[3376]}, {'v1': v[-9223372036854769330], 'v2': v[3653], 'v3': v[3376]}, {'v1': v[-9223372036854766730], 'v2': v[3653], 'v3': v[3376]}, {'v1': v[-9223372036854762321], 'v2': v[3653], 'v3': v[3376]}, {'v1': v[1467], 'v2': v[3653], 'v3': v[3376]}, {'v1': v[1741], 'v2': v[3653], 'v3': v[3376]}, {'v1': v[3364], 'v2': v[3653], 'v3': v[3376]}, {'v1': v[7154], 'v2': v[3653], 'v3': v[3376]}, {'v1': v[8516], 'v2': v[3653], 'v3': v[3376]}, {'v1': v[9592], 'v2': v[3653], 'v3': v[3376]}, {'v1': v[13035], 'v2': v[3653], 'v3': v[3376]}, {'v1': v[13333], 'v2': v[3653], 'v3': v[3376]}, {'v1': v[-9223372036854773856], 'v2': v[-9223372036854771969], 'v3': v[3376]}, {'v1': v[-9223372036854771319], 'v2': v[-9223372036854771969], 'v3': v[3376]}, {'v1': v[-9223372036854769474], 'v2': v[-9223372036854771969], 'v3': v[3376]}, {'v1': v[-9223372036854768269], 'v2': v[-9223372036854771969], 'v3': v[3376]}, {'v1': v[-9223372036854767321], 'v2': v[-9223372036854771969], 'v3': v[3376]}, {'v1': v[1741], 'v2': v[-9223372036854771969], 'v3': v[3376]}, {'v1': v[-9223372036854772730], 'v2': v[-9223372036854771937], 'v3': v[3376]}, {'v1': v[3364], 'v2': v[-9223372036854771937], 'v3': v[3376]}, {'v1': v[6851], 'v2': v[-9223372036854771937], 'v3': v[3376]}, {'v1': v[7154], 'v2': v[-9223372036854771937], 'v3': v[3376]}, {'v1': v[8516], 'v2': v[-9223372036854771937], 'v3': v[3376]}, {'v1': v[-9223372036854775708], 'v2': v[-9223372036854771319], 'v3': v[3376]}, {'v1': v[-9223372036854774291], 'v2': v[-9223372036854771319], 'v3': v[3376]}, {'v1': v[-9223372036854771969], 'v2': v[-9223372036854771319], 'v3': v[3376]}, {'v1': v[-9223372036854768269], 'v2': v[-9223372036854771319], 'v3': v[3376]}, {'v1': v[-9223372036854766730], 'v2': v[-9223372036854771319], 'v3': v[3376]}, {'v1': v[-9223372036854764685], 'v2': v[-9223372036854771319], 'v3': v[3376]}, {'v1': v[-9223372036854763780], 'v2': v[-9223372036854771319], 'v3': v[3376]}, {'v1': v[7599], 'v2': v[-9223372036854771319], 'v3': v[3376]}, {'v1': v[9176], 'v2': v[-9223372036854771319], 'v3': v[3376]}, {'v1': v[11247], 'v2': v[-9223372036854771319], 'v3': v[3376]}, {'v1': v[-9223372036854773594], 'v2': v[-9223372036854771047], 'v3': v[3376]}, {'v1': v[-9223372036854770418], 'v2': v[-9223372036854771047], 'v3': v[3376]}, {'v1': v[-9223372036854768270], 'v2': v[-9223372036854771047], 'v3': v[3376]}, {'v1': v[1741], 'v2': v[-9223372036854771047], 'v3': v[3376]}, {'v1': v[-9223372036854769611], 'v2': v[-9223372036854771008], 'v3': v[3376]}, {'v1': v[-9223372036854769605], 'v2': v[-9223372036854771008], 'v3': v[3376]}, {'v1': v[-9223372036854764631], 'v2': v[-9223372036854771008], 'v3': v[3376]}, {'v1': v[-9223372036854762321], 'v2': v[-9223372036854771008], 'v3': v[3376]}, {'v1': v[3653], 'v2': v[-9223372036854771008], 'v3': v[3376]}, {'v1': v[7154], 'v2': v[-9223372036854771008], 'v3': v[3376]}, {'v1': v[8516], 'v2': v[-9223372036854771008], 'v3': v[3376]}, {'v1': v[9592], 'v2': v[-9223372036854771008], 'v3': v[3376]}, {'v1': v[11247], 'v2': v[-9223372036854771008], 'v3': v[3376]}, {'v1': v[12615], 'v2': v[-9223372036854771008], 'v3': v[3376]}, {'v1': v[-9223372036854771047], 'v2': v[-9223372036854770418], 'v3': v[3376]}, {'v1': v[-9223372036854769474], 'v2': v[-9223372036854770418], 'v3': v[3376]}, {'v1': v[-9223372036854769330], 'v2': v[-9223372036854770418], 'v3': v[3376]}, {'v1': v[-9223372036854765974], 'v2': v[-9223372036854770418], 'v3': v[3376]}, {'v1': v[3535], 'v2': v[-9223372036854770418], 'v3': v[3376]}, {'v1': v[9592], 'v2': v[-9223372036854770418], 'v3': v[3376]}, {'v1': v[9769], 'v2': v[-9223372036854770418], 'v3': v[3376]}, {'v1': v[11247], 'v2': v[-9223372036854770418], 'v3': v[3376]}, {'v1': v[13035], 'v2': v[-9223372036854770418], 'v3': v[3376]}]
```

**Comment by longbinlai** [comment]
@EricaGuoQiuyu Hi, thank you for your comment. There are several reasons forcing us to use inner ID:
(1) Uniqueness: Even user provides property id, it is often the case that the id is unique only to the specific type of vertex/edge, but is not globally so. As a result, if we return property id to the user, and the user takes the property id to further query the vertex/edge, the results are unexpected thereafter. 
(2) Property Id may not present: The property id, in the concept of relational database, is more like a primary key, which is not necessarily called "id", but can rather be "name", and even a combination of "name, birthday". Therefore, property id cannot play the role of identifying vertices/edges. 
(3) A common practice: Both Gremlin and Cypher, two most widely used query language for graph, explicitly provide such a globally unique inner ID, which is globally unique as oppose to the property id. For example, in Gremlin, you may use this inner ID to query data like `g.V().hasId(innerId)`, while querying using property id is like `g.V().hasId("id")`.

**Comment by EricaGuoQiuyu** [comment]
> @EricaGuoQiuyu Hi, thank you for your comment. There are several reasons forcing us to use inner ID: (1) Uniqueness: Even user provides property id, it is often the case that the id is unique only to the specific type of vertex/edge, but is not globally so. As a result, if we return property id to the user, and the user takes the property id to further query the vertex/edge, the results will be unexpected thereafter. (2) Property Id may not present: The property id, in the concept of relational database, is more like a primary key, which is not necessarily called "id", but can rather be "name", and even a combination of "name, birthday". Therefore, property id cannot play the role of identifying vertices/edges. (3) A common practice: Both Gremlin and Cypher, two most widely used query language for graph, explicitly provide such a inner ID, which is globally unique as oppose to the property id. For example, in Gremlin, you may use this inner ID to query data like `g.V().hasId(innerId)`, while querying using property id is like `g.V().hasId("id", propertyId)`.

Thank you very much for your reply! I have no more questions.
