### ISSUE TITLE
Make `show_log` as a global configuration of graphscope.

### ISSUE THREAD

**Issue by lidongze0629** [alibaba/GraphScope#27]
**Is your feature request related to a problem? Please describe.**
The `show_log` parameters between different sessions will affect each other.

**Describe the solution you'd like**

Deprecated `show_log`, `log_level` params in the session,  instead，It is better to define as global configuration of graphscope.

```python
import graphscope
graphscope.set_option("show_log", True)
graphscope.get_option("show_log")
```

**Comment by lidongze0629** [comment]
@sighingnow Any comments?

**Comment by sighingnow** [comment]
> @sighingnow Any comments?

GOOD to me.
