### ISSUE TITLE
Lacks documentation of `Dev and Test` for GIE

### ISSUE THREAD

**Issue by yecol** [alibaba/GraphScope#2709]
Reported by dogfooding users, currently the documentation lacks how to build/test GIE part.

<img width="323" alt="image" src="https://github.com/alibaba/GraphScope/assets/426463/a62d852c-5a2f-4b5a-a295-0a3c7e7cdb1c">

**Comment by longbinlai** [comment]
Dev and Test (and other docs as well) is a little unclear for GIE at this moment. I am thinking this as part of the production development of GIE. May I consider this during the production process of GIE?

**Comment by longbinlai** [comment]
In progress, has blocked by the following issue: https://github.com/alibaba/GraphScope/issues/2721

**Comment by yecol** [comment]
#2721 is closed by a merged PR.

**Comment by longbinlai** [comment]
Yeah, working on it already.

**Comment by longbinlai** [comment]
Close by https://github.com/alibaba/GraphScope/pull/2733

**Comment by longbinlai** [comment]
We must further refine the docs according to these two dogfooding tasks: 
- [ ] 从源代码编译 Interactive Engine，找到编译出的 frontend-x-SNAPSHOT.jar和 gaia_executor,直接运行这个 jar 包和这个 gaia_executor，使 frontend 能够连接到 executor。
- [ ] 了解 Frontend 和 Executor 的代码位置和组织结构，为 GIE 的 Frontend (interactive_engine/frontend/src/main/java/com/alibaba/graphscope/frontend/Frontend.java) 和 executor (interactive_engine/executor/assembly/v6d/src/bin/gaia_executor.rs) 各添加一条日志，并重新编译，启动并找到新添加的日志

**Comment by longbinlai** [comment]
close by #2767
