### ISSUE TITLE
[BUG] GIE fails in compiling `match()` with anti-join sentences.

### ISSUE THREAD

**Issue by BingqingLyu** [alibaba/GraphScope#2712]
**Describe the bug**

GIE outputs compiling error when run the `match` query which contains anti-join.
The example to reproduce the bug is as follows:

```
g.V().match(
    __.as("a").in().as("b"),
    __.as("b").out().as("c"),
    __.not(__.as("c").out().as("a"))
)
```
which outputs error:
```
op type {class com.alibaba.graphscope.common.intermediate.operator.MatchOp} returns {Others, msg is the first sentence of `MergedSentence` must have InnerJoin}
```

**Screenshots**

![image](https://github.com/alibaba/GraphScope/assets/28559306/a0284308-1d47-47ec-aadc-c8f7028e2291)

**Comment by sighingnow** [comment]
Closed by #2730
