### ISSUE TITLE
auto-generate docs for Flex

### ISSUE THREAD

**Issue by yecol** [alibaba/GraphScope#2726]
Currently the reference doc files for Flex is pre-built and hosted in the code-repo, 
with path: `/flex/docs`

Please integrate the generate cmd to `make docs`, following the manner we used for the project:
- auto-gen the docs;
- please note that the generated files should be in `gh-pages` branch, rather than `main`;
- maybe output the generated files to a subfolder `Flex` under section `REFERENCES`.

**Comment by ds-ssj** [comment]
In this issue, do we need to generate `html` files directly under REFERENCES (similar to the GAE JAVA API) or do we need to re-describe them in the style of `rst` files (similar to the GAE API and Python API) and then generate `html` files?
