### ISSUE TITLE
[GIE] Provide Cypher instances in GraphScope's Python SDK for GIE

### ISSUE THREAD

**Issue by longbinlai** [alibaba/GraphScope#2736]
There are now two query languages in GIE: Cypher and Gremlin. We currently have a `gremlin` instance in GraphScope's python SDK, while there needs a `cypher` instance for submitting Cypher queries.

**Comment by longbinlai** [comment]
> Let me have a try 😁

Cheers. @shirly121 can provide necessary help.

**Comment by andydiwenzhu** [comment]
With the help from @siyuan0322 @shirly121 , I propose the user interface for cypher as follows:

interactive = graphscope.cypher(g)
records = interactive.execute("MATCH (n) RETURN n Limit 10”)
for record in records:
     print(record["n"])

@longbinlai Please comment whether it is suitable for a cypher user.

**Comment by yecol** [comment]
LGTM!

**Comment by yecol** [comment]
Please waiting for options from @longbinlai  
When implementing this interface, please be cautioned to check whether the GIE is launched, -- it may already be launched by `.cypher` or `.gremlin`.

**Comment by andydiwenzhu** [comment]
> 

Thanks for the advice!

**Comment by andydiwenzhu** [comment]
After discuss with @longbinlai @shirly121 , we update the design into:
```
interactive = graphscope.interactive(g)
q1 = interactive.execute('g.V().count()', lang='gremlin')
print(q1.all().result())

q2 = interactive.execute('Match (n:person) Return n Limit 1', lang='cypher', routing_=RoutingControl.READ)
for record in q2.records:
    print(record["n"])
```
