### ISSUE TITLE
Unify all session related parameters.

### ISSUE THREAD

**Issue by siyuan0322** [alibaba/GraphScope#2748]
Currently we have a bunch of similar parameters scattered throughout the code in session, coordinator, kubernetes launcher, etc. Since they are so similar and just been passed around with some renaming, an obvious solution is to aggregate all similar parameters together, which would make it easier to manage and modify.

The expected outcome is make the process to adding a new parameter to session/coordinator simple and straight forward.

**Comment by wenyuanyu** [comment]
I will give it a try...

**Comment by wenyuanyu** [comment]
A few places that handles configurations in ad-hoc and repetitive ways:
- https://github.com/alibaba/GraphScope/blob/main/python/graphscope/client/session.py#L285-L328
- https://github.com/alibaba/GraphScope/blob/a0b36eeef0f5c4ed14b5e340e9b62eb9ff8aff9f/python/graphscope/config.py#L28 
- https://github.com/alibaba/GraphScope/blob/a0b36eeef0f5c4ed14b5e340e9b62eb9ff8aff9f/python/graphscope/deploy/kubernetes/cluster.py#L65-L100
- https://github.com/alibaba/GraphScope/blob/a0b36eeef0f5c4ed14b5e340e9b62eb9ff8aff9f/coordinator/gscoordinator/coordinator.py#L621-L956
- https://github.com/alibaba/GraphScope/blob/a0b36eeef0f5c4ed14b5e340e9b62eb9ff8aff9f/coordinator/gscoordinator/kubernetes_launcher.py#L76-L113
