### ISSUE TITLE
unify the rust format configuration files

### ISSUE THREAD

**Issue by yecol** [alibaba/GraphScope#275]
https://github.com/alibaba/GraphScope/blob/3a83eade5565c7e1193a1b8bfc2393ea23b20afc/research/gaia/pegasus/rustfmt.toml#L3

I found 4 `rustfmt.toml` files in the repo. Maybe the format configurations should be consistent and one .toml file in the most outer directory like `research/GAIA` is sufficient?

**Comment by longbinlai** [comment]
Sadly no. As the whole repository is not a pure Rust project, we need 4 format configurations for each sub-project.

**Comment by youyangy** [comment]
We can remove research/gaia/rustfmt.toml, this one is unneccesary.
