### ISSUE TITLE
[GIE] 'ElementMap' operator support

### ISSUE THREAD

**Issue by lidongze0629** [alibaba/GraphScope#2778]
**Is your feature request related to a problem? Please describe.**
From the issue: https://github.com/alibaba/GraphScope/issues/2742, The result of `valueMap` operator doesn't include the properties info, which is necessary for graph visualization. The [elementMap](https://tinkerpop.apache.org/docs/current/reference/#elementmap-step) operator will be helpful for this.

https://tinkerpop.apache.org/docs/current/reference/#elementmap-step

**Comment by shirly121** [comment]
To test the functionality of `elementMap`, you can add gremlin standard cases in the test suite. i.e. you can add `ElementMapTest.Traversals.class` in https://github.com/alibaba/GraphScope/blob/main/interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/integration/suite/standard/IrGremlinTestSuite.java#L74 and https://github.com/alibaba/GraphScope/blob/main/interactive_engine/compiler/src/main/java/com/alibaba/graphscope/gremlin/integration/suite/standard/IrGremlinTestSuite.java#L110
