### ISSUE TITLE
[BUG] Bug of nested sub-traversal queries in GAIA

### ISSUE THREAD

**Issue by youyangy** [alibaba/GraphScope#279]
**Describe the bug**
Queries like:

```
g.V($id).repeat(both().where(both().both().limit(1))).times(1)
g.V($id).both().where(both().where(both())) 
g.V($id).repeat(both().as('a').select('a').by(both().count())).times(1)
```

The bug will be triggered when where nested sub-traversal appears.

**To Reproduce**
Disable the repeat unroll optimization of the compiler and early stop optimization of Pegasus, then run the query above.

**Comment by longbinlai** [comment]
Can we make it more generic? Is it all about nested subtraversal? or simply repeat nesting where. Can we try g.V(xx).out().where(both().where(both())) ?

**Comment by youyangy** [comment]
> Can we make it more generic? Is it all about nested subtraversal? or simply repeat nesting where. Can we try g.V(xx).out().where(both().where(both())) ?

The description is updated. Actually, all nested sub-traversal would have this problem.
