### ISSUE TITLE
[GS/Coordinator] Make query bypassing GS coordinator

### ISSUE THREAD

**Issue by longbinlai** [alibaba/GraphScope#2855]
Now GraphScope need results of query being forwarded to the Frontend by the (GS) coordination, which:
- makes coordinator vulnerable of being overflowed, 
- adds delay and bottleneck,
- is functionally unnecessary

Therefore, we may allow the executor to bypass coordinator to directly forward the results to the FrontEnd
in any k8s deployment of GIE.

**Comment by siyuan0322** [comment]
Fixed by #2923
