### ISSUE TITLE
[Gremlin] The predicate in where()/has() step returns wrong result

### ISSUE THREAD

**Issue by shirly121** [alibaba/GraphScope#286]
**Describe the bug**
Some queries produce the wrong results, not consistent with the expected.

**To Reproduce**
1. g.V().as("a").out("created").where(__.as("a").values("name").is("josh")).in("created").values("name")
2. g.V().has("age", P.without(27))
3. g.V().as("a").out("created").in("created").as("b").where("a", P.gt("b")).by("age").select("a", "b").by("name")

Expected:
1. 
==>marko
==>josh
==>peter
==>josh

2.
==>v[1]
==>v[4]
==>v[6]

3.
==>{a=josh, b=marko}
==>{a=peter, b=marko}
==>{a=peter, b=josh}

Actual:
1. Empty
2. Not support
3. Wrong result:
==>{a=marko, b=josh}
==>{a=marko, b=peter}
==>{a=josh, b=peter}

**Comment by longbinlai** [comment]
Could also present the wrong results and expected?
