### ISSUE TITLE
[GIE/Compiler] How compiler reacts to Gaia's failure 

### ISSUE THREAD

**Issue by longbinlai** [alibaba/GraphScope#2861]
We have tested that an executor of Gaia/Pegasus can recover itself upon failure via K8s. 
But it remains unclear how the compiler reacts to such failure. 
It is critical that the compiler:
- is aware of the errors of executors,
- may reject (instead of continuously submit) the queries from the clients until the executors are all recovered. 

We need a test (in ci) to verify the behavior.

**Comment by shirly121** [comment]
Through testing, it has been proven that the compiler can correctly throw Gaia errors to the users, whether they occur before or after the submission of execution. In both cases, the errors can be promptly returned as gRPC errors. Once an error occurs, the Pegasus client can handle the error promptly, throw an exception, and terminate the waiting for other executor channels.

kill one of executors and submit a query:
<img width="1684" alt="image" src="https://github.com/alibaba/GraphScope/assets/22363306/54367eae-6713-47d8-a717-06007b2b706d">


submit a query and then kill one of executors:
<img width="1057" alt="image" src="https://github.com/alibaba/GraphScope/assets/22363306/9e01931b-94cd-479f-b96f-489cffd5fb39">

**Comment by longbinlai** [comment]
Close by the above comments.
