### ISSUE TITLE
The analytical algorithm performance doesn't meet the expectation

### ISSUE THREAD

**Issue by vegetableysm** [alibaba/GraphScope#2898]
I tested pagerank and sssp algorithm on GraphScope and Gemini. And found that the Gemini performed much faster than the GraphScope. Here is the result of **pagerank** test with the dataset of **soc-LiveJournal1** . The iterations is **20**:

| platform  | time usage |
| ------------- | ------------- |
| GraphScope  | 1.4s |
| Gemini | 0.37s  |
| Libgrape-lite |   0.15s|

The script of GraphScope
```
import graphscope
import time
import datetime

sess = graphscope.session(num_workers=1, cluster_type='hosts')

graph = sess.g()

start = time.time()
graph = graph.add_edges('../data_set/live_journal/soc-livejournal.csv', src_label='v', dst_label='v', properties = [])
end = time.time()

print("Loading time: %f" % (end - start))

start = time.time()
ret1 = graphscope.pagerank(graph, max_round = 20)
end = time.time()

print("Running time: %f" % (end - start))

print(ret1.to_dataframe(selector={'id': 'v.id', 'label': 'r'}))

sess.close()
```
The command of running libgrape-lite
`mpirun -n 1 ./run_app --vfile ../../data_set/live_journal/soc-livejournal.vertex.csv --efile ../../data_set/live_journal/soc-livejournal.mtx --application pagerank --out_prefix ./output_pagerank --directed -pr_mr 20`

The running command of Gemini
`./toolkits/pagerank ./data_set/live_journal/soc-livejournal.binarye 4033137 20`

Each of the above three tests sets one partition.

The problem is that the graphscope is 10 times worse than the libgrape-lite. I don't know if my test script is wrong, please advise. Thanks!

**Comment by siyuan0322** [comment]
One reason of that is it may includes the compilation time and projection time.
Other reasons are under investigation.

**Comment by vegetableysm** [comment]
The first ten lines of edge file:
```
src,dst
2,1
3,1
5,1
6,1
7,1
8,1
9,1
10,1
16,1
```

**Comment by siyuan0322** [comment]
Found that the timing method includes the python codes to assemble the op, and the round trip time of RPC, the dynamic loading of libraries, thus add much over head to querying time (which is less than 1 second in this experiment), so the overhead is huge.

Add a new log to print the actual evaluating time of application in the grape_engine, which should as the realiable metrics.
