### ISSUE TITLE
[BUG] Timeout of small query with count() step on persistent storage

### ISSUE THREAD

**Issue by tianliplus** [alibaba/GraphScope#292]
**Describe the bug**

When executing the query `g.V().count()` on persistent storage, TimeoutException will be thrown after 120s. The amount of data is small, e.g., 10 vertices.

**To Reproduce**
1. load schema and insert data (10 vertices)
2. submit query g.V().count()
3. See TimeoutException after 120s

**Expected behavior**
Return count of vertices immediately

**Environment (please complete the following information):**
 - GraphScope version: [on branch store]
 - OS: [Linux]
 - Version [AliOs7]

**Comment by yecol** [comment]
hi @BingqingLyu any progress on this issue?

**Comment by BingqingLyu** [comment]
> hi @BingqingLyu any progress on this issue?

I have already fixed this bug within pull request #361
