### ISSUE TITLE
Lazy and eager mode support

### ISSUE THREAD

**Issue by yecol** [alibaba/GraphScope#303]
Currently GraphScope only support run eager mode. 
We'd like to introduce a parameter `mode` in the session to support lazy execution.

Major changes: 
- functions in a lazy session, return a DAG node, rather than a real object;
- a DAG belongs to a session
- When in lazy mode, only results assigned in the `run` and their dependencies are reserved, other data is destroyed.
- defer the lazy support for gremlin.
- lazy session doesn't finalize when run, since results maybe in vineyard.

```python

# Explicitly open a session, the mode is eager by default.
s1 = graphscope.session(RESOURCES_GROUP_1)
s2 = graphscope.session(RESOURCES_GROUP_2)

# Build a graph
g1 = s1.g() # g1 belongs to s1,  return a DAG node
g2 = g1.add_vertices() # g2 is a DAG node and it inherits g1, session = s1
g3 = g2.add_edges() # g3.session = s1

# Create an interactive query
interactive = s2.gremlin(g3) # ERROR! g3 and s2 are not in the same session;
interactive = graphscope.gremlin(g3) # OK, inherits the session, s1.
ret = graphscope.bfs(g3, src=0) # s1.
lg = graphscope.learning(g3, label...) # s1

# lazy-mode
s3 = graphscope.session(mode="lazy")
# blabla... natually, these statements are not executed until triggers`run`
s3.run()

# ithis should be error:
#--------VERY-BEGINNING-OF-THE-SCRIPT
g = graphscope.g() # error, since there is no session, gs doesn't know where to evaluate this statement.

# session can be explicitly claimed as default. as before.

#--------VERY-BEGINNING-OF-THE-SCRIPT
s4 = graphscope.session(mode="lazy").as_default()
g4 = graphscope.g() 
g5 = g4.add_vertices()
g6 = g5.add_edges()

ret = graphscope.bfs(g6, src=0) 
r = s4.run(ret) # r can be used by others. the session is not finalized, since r maybe in v6d.




#--------VERY-BEGINNING-OF-THE-SCRIPT
s5 = graphscope.session(mode="lazy").as_default()
g1 = graphscope.g() # g1 is DagNode
g2 = sess.run(g1) # g2 is also a DagNode，but has been run. 

r1 = pagerank(g1) 
sess.run(r1) # reload g1

r2 = pagerank(g2)
sess.run(r2)  # don't need to relead g2

# --------NETWORKX-AND-SESSION

s6 = graphscope.session(mode="eager").as_default()
import graphscope.nx as nx.    # use default session as nx binding session

s7 = graphscope.session(mode="eager")
nx = s7.nx()
```

**Comment by yecol** [comment]
Need further discussion:
- use `run` or `run_and_finalize`? the later prevent running twice.
- what is the return value of `s4.run_and_finalize(ret)`, since the finalize may close session and release the resources.
- co-operate with vineyard? 
- Lazy mode enabled job submission in production, need to get the resources context and pass to the session.

**Comment by yecol** [comment]
> Need further discussion:
> 
> * use `run` or `run_and_finalize`? the later prevent running twice.
> * what is the return value of `s4.run_and_finalize(ret)`, since the finalize may close session and release the resources.
> * co-operate with vineyard?
> * Lazy mode enabled job submission in production, need to get the resources context and pass to the session.

1. run
2. the data with its dependencies, session not finalized.

**Comment by acezen** [comment]
nx further discussion:
- import nx with session
```
s = graphscope.session(mode="eager")
nx = s.nx
```
Or
```
import graphscope.nx as nx
nx.bind(s)
```

- transform from graphscope.g, the session should be same as graphscope.g. should we enforce the graphscope.g has to be a eager session's g

**Comment by lidongze0629** [comment]
**Test Case**

```python
# test raise error when use nx graph with lazy
```

**Comment by lidongze0629** [comment]
Time Table:
- [ ] impl and test `add_vertices` and `add_edges` method with lazy mode
- [ ] graph op full support
- [ ] app op full support
- [ ] make `InteractiveQuery` and `Learning` as an op (need to support split dag)
- [ ] whole process test
- [ ] migrate logic of loading graph(OSS) from client to coordinator
- [ ] perfect and pass CI of lazy mode
