### ISSUE TITLE
Upgrade the build phase of image in CI with gsctl

### ISSUE THREAD

**Issue by lidongze0629** [alibaba/GraphScope#3074]
**Is your feature request related to a problem? Please describe.**

See background in #2925. 

For this task, you may want to investigate all the build phases in the CI, and replace them using `gsctl make --xxx`, to make the related sub-commands in `gsctl` robust and confident.

Here are some tips:

- after checkout, the first command should be cd python/graphscope && pip install --editable . to make gsctl usable.
add the missing pieces, (options or subcommand) in gsctl, if any.
- Please note there is a CI env in github actions. Check it if you have specific codings for CI runtime.
- To make our life easier, you may leave build wheel related jobs untouched.

**Here are the usage:**
```
gsctl install-deps     Install dependencies on local machine.
gsctl make xxx         # Build GraphScope on local.
gsctl test                  # Run tests of graphscope
gsctl format            
gsctl dev                   # Open a develop environment with docker.
```

**Useful links**
-  [cli (to be deprecated)](https://github.com/GraphScope/cli)
- [python click](https://click.palletsprojects.com/en/8.1.x/)

**Comment by lidongze0629** [comment]
![截屏2023-08-03 上午11 28 05](https://github.com/alibaba/GraphScope/assets/23491543/a6b62c2c-2d53-4d65-884c-d05324ec9fda)

**Comment by lidongze0629** [comment]
pr 形式:
- 删除 gs 文件
- 重构 gsctl 文件，支持已有的 gs 支持的功能，保证 CI 通过

**Comment by lidongze0629** [comment]
pr 形式:
- 删除 gs 文件
- 重构 gsctl 文件，支持已有的 gs 支持的功能，保证 CI 通过

**Comment by FLYLX** [comment]
gs文件在GraphScope文件下的命令整理：
gs --version | -v
gs --help | -h
gs make-image -h
gs install-deps :
        gs install-deps -h 
        
        gs install-deps dev:        
                gs install-deps dev
                gs install-deps dev --cn
                gs install-deps dev --v6d-version v0.16.1
                gs install-deps dev --cn --for-analytical --no-v6d
                gs install-deps dev --v6d-version=$VINEYARD_VERSION -j $(nproc)
                gs install-deps dev --v6d-version=$VINEYARD_VERSION -j 2
                gs install-deps dev --for-analytical --v6d-version=$VINEYARD_VERSION -j 2


gs make:
         gs make all
         gs make install:
                 gs make install
                 gs make install [--prefix=/opt/graphscope]
         gs make coordinator
         gs make client
         gs make analytical:
                 gs make analytical
                 gs make analytical-install --install-prefix /usr/local
         gs make learning:
                 gs make learning
                 gs make learning-install --install-prefix /opt/graphscope
         gs make interactive:
                 gs make interative --storage-type=vineyard
                 gs make interative-install --storage-type=vineyard  --install-prefix /opt/graphscope

gs test:
          gs test e2e --local
          gs test e2e --k8s --registry="docker.io" --tag="latest"
          gs test interactive --local --storage-type=vineyard

**Comment by FLYLX** [comment]
一周总结：了解了bashly是如何生成gs，以及src下各个bash的文件结构，联系bash文件参数策划好开发方案并尝试完成了make --component命令

**Comment by lidongze0629** [comment]
@FLYLX 争取本周(8.8 - 8.11)，我们完成对 `gsctl install-deps` 或 `gsctl make` 的迁移实现，涉及到的 bash 脚本代码，整理后放到 `python/graphscope/gsctl/scripts` 目录下
