### ISSUE TITLE
Cannot import datasets to graphscope with ShuffleTableByOffsetLists error

### ISSUE THREAD

**Issue by Suchun-sv** [alibaba/GraphScope#3210]
### Discussed in https://github.com/alibaba/GraphScope/discussions/3209

<div type='discussions-op-text'>

<sup>Originally posted by **Suchun-sv** September 12, 2023</sup>
According to the documentation (https://graphscope.io/docs/latest/zh/loading_graph), I imported the dataset with node.csv and edge.csv. Though I successfully done the nodes, I encountered problems as such:
<img width="1255" alt="image" src="https://github.com/alibaba/GraphScope/assets/35399433/053dadbf-d47f-436c-b2ec-d3c88f8fc876">
My code snippet is as follows: 
```python
graph = sess.g()
# graph = graph.add_vertices(".data/stone_story/data/stone_story_node.csv", label="name")
edges_sets = pd.read_csv("./stone_story/data/stone_story_edges.csv")
graph = graph.add_edges(edges_sets, src_label="head", dst_label="tail", properties=["relation"])
```
the node.csv shows like:
<img width="186" alt="image" src="https://github.com/alibaba/GraphScope/assets/35399433/3ef02b6b-8285-402e-a69d-2b838a3da2b4">
the edges.csv are:
<img width="291" alt="image" src="https://github.com/alibaba/GraphScope/assets/35399433/33508d96-c066-4c1d-aea7-1af69ee37b2b">
</div>
I'm worrying about what the error suggests? as I'm not an expert in the C++ field, I couldn't find effective solutions. Thanks for any help.

**Comment by sighingnow** [comment]
From the error message "OID_T 'int64' is not same with arrow::Column(large_string)", you can see that your graph's parameter is not consistent with the data. To fix the problem, you need

```
graph = sess.g(oid_type='string')
```

**Comment by sighingnow** [comment]
Closing.
