### ISSUE TITLE
GraphScope Interactive: Lacking a comprehensive test 

### ISSUE THREAD

**Issue by longbinlai** [alibaba/GraphScope#3215]
Currently, there lacks a comprehensive test for GraphScope Interactive, which may compromise the service if unexpected queries are submitted from the users that may trigger service crash. 

 A comprehensive test is inevitable  before we hand `gs_interactive` over to our users.

**Comment by zhanglei1949** [comment]
From robin: https://neo4j.com/docs/getting-started/appendix/tutorials/guide-cypher-basics/
