### ISSUE TITLE
Support writing gremlin queries in Python

### ISSUE THREAD

**Issue by yecol** [alibaba/GraphScope#329]
Currently the gremlin queries are passed in string:

```python
interactive = sess.gremlin(g)
papers = interactive.execute("g.V().has('author', 'id', 2)....)
```

Ideally, the gremlin should be written in Python, (maybe with the help of `gremlinpython` package?)

```python
# a wrapper to get a Traversal object.
g = sess.interactive(graph)

g.V().has('author', 'id', 2)...
```

**Comment by sighingnow** [comment]
It has already been here: https://github.com/alibaba/GraphScope/blob/main/python/graphscope/interactive/query.py#L187

Wrap the gremlin API to `g` itself still worths a PR.

**Comment by yecol** [comment]
OK, thanks for reminding me..
