### ISSUE TITLE
[BUG] GraphScope Interactive fail to run following queries

### ISSUE THREAD

**Issue by zhanglei1949** [alibaba/GraphScope#3377]
```cypher
MATCH(v)-[e]-() return distinct type(e);
MATCH(c: CCFField)<-[e]-(p:Paper) where type(e) = "HasField"  return e LIMIT 10;
```

Error results when run
```cypher
MATCH(c: CCFField)<-[e]-(p:Paper) return type(e) LIMIT 10;
```

**Comment by shirly121** [comment]
Support for the above query on the compiler side is as follows:

- Full support for cases 1 and 3.

- Partial support for case 2; after the FilterPushDown optimization, where type(e) = "HasField" should be merged into the edge 'e' and the filter can be further transformed into a label restriction on 'e,' the query becomes equivalent to MATCH(c: CCFField)<-[e: HasField]-(p:Paper) return e LIMIT 10;. However, there are currently bugs in the compiler that cause type(e) = "HasField" to persist as a condition; this issue will be addressed in subsequent pull requests.

- The compiler cannot, however, convert all label filter conditions into label restrictions. For instance, in the query MATCH(c: CCFField)<-[e]-(p:Paper) Where type(e) = 'HasField' or e.weight = XX, runtime considerations are still needed for support regarding label filter conditions.

**Comment by zhanglei1949** [comment]
For the second query, we support comparison  between `type(e)` and `int`.
```cypher
MATCH(c: CCFField)<-[e]-(p:Paper) where type(e) = 6  return e LIMIT 10;
```
