### ISSUE TITLE
Starting the interactive server resulted in an error

### ISSUE THREAD

**Issue by sighingnow** [alibaba/GraphScope#3414]
### Discussed in https://github.com/alibaba/GraphScope/discussions/3413

<div type='discussions-op-text'>

<sup>Originally posted by **pomelo-nwu** December  9, 2023</sup>
Hi, Graphscope team, first of all, thank you for creating such a great project. I'm using Flex/interactive and encountered some issues while following the documentation at https://graphscope.io/docs/flex/interactive/getting_started:

There was an error when initializing gs_interactive, along with a warning.
![image](https://github.com/alibaba/GraphScope/assets/10703060/c2556dfd-58c3-4226-98d8-4a12ae603d66)

It seems that the second step of starting the service also failed.
![image](https://github.com/alibaba/GraphScope/assets/10703060/5622cc20-db86-42cc-8e83-a599950b4228)

My environment is:

```bash
(py39) ➜  interactive uname -aDarwin U-2Q9KNH7F-2210.local 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:45 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6020 arm64
(py39) ➜  interactive python --versionPython 3.9.18
```</div>

**Comment by zhanglei1949** [comment]
There seems to be some problem running Interactive on mac, even in container.

**Comment by zhanglei1949** [comment]
Related seastar issue and PR:
https://github.com/scylladb/seastar/issues/1826
https://github.com/scylladb/seastar/pull/1974

**Comment by zhanglei1949** [comment]
It appears that due to a bug in QEMU, the Seastar that we rely on cannot be used normally on Macs (M1, M2).

**Comment by zhanglei1949** [comment]
This bug is marked wont fix, until QEMU fix it.

**Comment by zhanglei1949** [comment]
It seems that use image built on `aarch64` can fix this problem.
