### ISSUE TITLE
[BUG] It seems like the Interactive Engine doesn't support some Cypher statements

### ISSUE THREAD

**Issue by pomelo-nwu** [alibaba/GraphScope#3467]
**Describe the bug**

`MATCH p=()-[:write]->() RETURN p LIMIT 25;`
![image](https://github.com/alibaba/GraphScope/assets/10703060/d8c24a75-43bd-4943-9d1a-b7eba8138408)

`Match (a)-[c*1..3]->(b) Return a, c, b`

![image](https://github.com/alibaba/GraphScope/assets/10703060/9c4e5594-9926-4872-845e-b9b0cdba5f16)

`Match (n) return n limit 10` this statement executed successfully.

![image](https://github.com/alibaba/GraphScope/assets/10703060/2a724855-c8ac-4db6-aa2f-b4772fa9489b)

**To Reproduce**
 
Refer to this document: https://graphscope.io/docs/flex/interactive/custom_graph_data

**Comment by longbinlai** [comment]
For the first query, `p = xxx` such kind of query is not supported yet. We have no plan to support it in a short time.

**Comment by zhanglei1949** [comment]
For the second query, I will fix it via #3538 , BUT the returned result(only return the last vertex) will still different from the standard neo4j cypher query result(returning all vertices/edges on path). See #3537
