### ISSUE TITLE
run the algorithm related test case and reported an error[BUG] 

### ISSUE THREAD

**Issue by haohao0103** [alibaba/GraphScope#3485]
**Describe the bug**
When I completed the build based on the master branch, I ran the algorithm related test case and reported an error

**To Reproduce**
1. test_app.py→test_louvain_on_projected()

error message:
Running command: make -j2, cwd: /tmp/gs/builtin/41df71fc38edd891f4de0d9004c663e762002931afbe51e1e2fef7ef610ff9c2
2024-01-15 04:12:04,910 [ERROR][utils:325]: Failed to run command: make -j2, error message is: In file included from /opt/graphscope/include/graphscope/frame/property_graph_frame.cc:29:
/opt/graphscope/include/graphscope/core/loader/arrow_fragment_loader.h: In instantiation of ‘boost::leaf::result<long unsigned int> gs::ArrowFragmentLoader<OID_T, VID_T, VERTEX_MAP_T>::AddDataToExistedVLable(vineyard::ObjectID, typename gs::ArrowFragmentLoader<OID_T, VID_T, VERTEX_MAP_T>::Base::label_id_t) [with OID_T = long int; VID_T = long unsigned int; VERTEX_MAP_T = vineyard::ArrowVertexMap; vineyard::ObjectID = long unsigned int; typename gs::ArrowFragmentLoader<OID_T, VID_T, VERTEX_MAP_T>::Base::label_id_t = int; gs::ArrowFragmentLoader<OID_T, VID_T, VERTEX_MAP_T>::Base = vineyard::ArrowFragmentLoader<long int, long unsigned int>]’:
/opt/graphscope/include/graphscope/core/loader/arrow_fragment_loader.h:342:7:   required from ‘boost::leaf::result<long unsigned int> gs::ArrowFragmentLoader<OID_T, VID_T, VERTEX_MAP_T>::ExtendLabelData(vineyard::ObjectID, int) [with OID_T = long int; VID_T = long unsigned int; VERTEX_MAP_T = vineyard::ArrowVertexMap; vineyard::ObjectID = long unsigned int]’
/opt/graphscope/include/graphscope/frame/property_graph_frame.cc:352:5:   required from here
/opt/graphscope/include/graphscope/core/loader/arrow_fragment_loader.h:279:40: error: ‘addDataToExistedVLabel’ is not a member of ‘gs::ArrowFragmentLoader<long int, long unsigned int, vineyard::ArrowVertexMap>::Base’ {aka ‘vineyard::ArrowFragmentLoader<long int, long unsigned int>’}
  279 |     return Base::addDataToExistedVLabel(frag_id, label_id,
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
  280 |                                         std::move(raw_v_e_tables));
      |                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/graphscope/include/graphscope/core/loader/arrow_fragment_loader.h: In instantiation of ‘boost::leaf::result<long unsigned int> gs::ArrowFragmentLoader<OID_T, VID_T, VERTEX_MAP_T>::AddDataToExistedELable(vineyard::ObjectID, typename gs::ArrowFragmentLoader<OID_T, VID_T, VERTEX_MAP_T>::Base::label_id_t) [with OID_T = long int; VID_T = long unsigned int; VERTEX_MAP_T = vineyard::ArrowVertexMap; vineyard::ObjectID = long unsigned int; typename gs::ArrowFragmentLoader<OID_T, VID_T, VERTEX_MAP_T>::Base::label_id_t = int; gs::ArrowFragmentLoader<OID_T, VID_T, VERTEX_MAP_T>::Base = vineyard::ArrowFragmentLoader<long int, long unsigned int>]’:
/opt/graphscope/include/graphscope/core/loader/arrow_fragment_loader.h:345:7:   required from ‘boost::leaf::result<long unsigned int> gs::ArrowFragmentLoader<OID_T, VID_T, VERTEX_MAP_T>::ExtendLabelData(vineyard::ObjectID, int) [with OID_T = long int; VID_T = long unsigned int; VERTEX_MAP_T = vineyard::ArrowVertexMap; vineyard::ObjectID = long unsigned int]’
/opt/graphscope/include/graphscope/frame/property_graph_frame.cc:352:5:   required from here
/opt/graphscope/include/graphscope/core/loader/arrow_fragment_loader.h:287:40: error: ‘addDataToExistedELabel’ is not a member of ‘gs::ArrowFragmentLoader<long int, long unsigned int, vineyard::ArrowVertexMap>::Base’ {aka ‘vineyard::ArrowFragmentLoader<long int, long unsigned int>’}
  287 |     return Base::addDataToExistedELabel(frag_id, label_id,
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
  288 |                                         std::move(raw_v_e_tables));
      |                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: note: unrecognized command-line option ‘-Wno-unused-lambda-capture’ may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option ‘-Wno-undef-prefix’ may have been intended to silence earlier diagnostics

**Environment (please complete the following information):**
 - GraphScope version: [master]
 - OS: [devcontainer ]

**Additional context**
I have tried to locate the problem, and the available information is: Base: : addDataToExistedVLabel addDataToExistedVLabel in vineyard 0.16.4 version does not exist, only available in the updated version, And the installation directory is /opt/vineyard, because I am not very familiar with C, I am not sure how to solve this problem

**Comment by siyuan0322** [comment]
Just updated the base image of dev container. Could u delete that env and reopen again, thanks!
If pulled the latest successfully, then the vineyard version should be v0.18.2
