### ISSUE TITLE
[BUG] Connection failed: Failed to connect to vineyardd

### ISSUE THREAD

**Issue by gaoyuan5251** [alibaba/GraphScope#3490]
**Describe the bug**
[error] Check failed: Connection failed: Failed to connect to vineyardd: Failed to connect to IPC socket: /tmp/vineyard_workspace/vineyard.sock in "client->Connect(vineyard_socket)", in function void gs::EnsureClient(std::shared_ptr<vineyard::Client>&, const string&), file /home/graphscope/GraphScope/analytical_engine/core/launcher.cc, line 126

log detail file : 
[log.txt](https://github.com/alibaba/GraphScope/files/13959463/log.txt)

**To Reproduce**
1. k8s集群新增2节点，将graphscope部署到新增2台节点
2.利用session = graphscope.session(
                             k8s_coordinator_cpu=1,
                             k8s_coordinator_mem="1Gi",
                             k8s_vineyard_cpu=4,
                             k8s_vineyard_mem="5Gi",
                             vineyard_shared_mem="5Gi",
                             k8s_engine_cpu=2,
                             k8s_namespace='***********',
                             k8s_engine_mem="5Gi",
                             num_workers=1,
                             k8s_image_tag="0.26.0a20240115-x86_64",
                             k8s_client_config='**********')
的方式在k8s上面部署服务，部署不成功。
3.从coordinator的日志看，报错如上。

**Expected behavior**
曾尝试coordinator，ping engine节点，多次尝试无效。希望能帮助排查coordinator 无法访问engine的根因

**Screenshots**

**Environment (please complete the following information):**
 - GraphScope version: 0.26.0a20240115-x86_64
 - OS: linux
 - Version [e.g. 10.15]
 - Kubernetes Version ：1.23.6

**Additional context**

**Comment by gaoyuan5251** [comment]
Wechat : gaoyuan5251
thank u very much~

**Comment by siyuan0322** [comment]
Ok, I'll add u on wechat

**Comment by siyuan0322** [comment]
already communicated on wechat
