### ISSUE TITLE
[BUG] circular import

### ISSUE THREAD

**Issue by colinguozizhong** [alibaba/GraphScope#3589]
when import graphscope.learning.graphlearn_torch ，it has a ImportError

(graphscope) [root@p-96b7-lfbd script]# python pyg_learn.py 
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /root/graphscope/script/pyg_learn.py:10 in <module>                                              │
│                                                                                                  │
│    7 from torch_geometric.nn import GraphSAGE                                                    │
│    8                                                                                             │
│    9 import graphscope as gs                                                                     │
│ ❱ 10 import graphscope.learning.graphlearn_torch as glt                                          │
│   11 from graphscope.dataset import load_ogbn_arxiv                                              │
│   12 from graphscope.learning.graphlearn_torch.typing import Split                               │
│   13                                                                                             │
│                                                                                                  │
│ /data1/anaconda3/envs/graphscope/lib/python3.9/site-packages/graphscope/learning/graphlearn_torc │
│ h/__init__.py:21 in <module>                                                                     │
│                                                                                                  │
│   18 # Disable warning messages of LibTorch by default.                                          │
│   19 os.environ["TORCH_CPP_LOG_LEVEL"] = "ERROR"                                                 │
│   20                                                                                             │
│ ❱ 21 from . import channel                                                                       │
│   22 from . import data                                                                          │
│   23 from . import distributed                                                                   │
│   24 from . import loader                                                                        │
│                                                                                                  │
│ /data1/anaconda3/envs/graphscope/lib/python3.9/site-packages/graphscope/learning/graphlearn_torc │
│ h/channel/__init__.py:16 in <module>                                                             │
│                                                                                                  │
│   13 # limitations under the License.                                                            │
│   14 # ==============================================================================            │
│   15                                                                                             │
│ ❱ 16 from .base import SampleMessage, ChannelBase, QueueTimeoutError                             │
│   17 from .mp_channel import MpChannel                                                           │
│   18 from .shm_channel import ShmChannel                                                         │
│   19 from .remote_channel import RemoteReceivingChannel                                          │
│                                                                                                  │
│ /data1/anaconda3/envs/graphscope/lib/python3.9/site-packages/graphscope/learning/graphlearn_torc │
│ h/channel/base.py:19 in <module>                                                                 │
│                                                                                                  │
│   16 from abc import ABC, abstractmethod                                                         │
│   17 from typing import Dict                                                                     │
│   18 import torch                                                                                │
│ ❱ 19 from .. import py_graphlearn_torch as pywrap                                                │
│   20                                                                                             │
│   21 QueueTimeoutError =  pywrap.QueueTimeoutError                                               │
│   22                                                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: cannot import name 'py_graphlearn_torch' from partially initialized module 'graphscope.learning.graphlearn_torch' (most likely 
due to a circular import) (/data1/anaconda3/envs/graphscope/lib/python3.9/site-packages/graphscope/learning/graphlearn_torch/__init__.py)

**Comment by LiSu** [comment]
@colinguozizhong  Thank you for bringing this issue up. The import error is caused by a bug in wheel generation, we will fix it ASAP.
