### ISSUE TITLE
[BUG] analytical-java: run custom java-algorithm error

### ISSUE THREAD

**Issue by hanjf12** [alibaba/GraphScope#3616]
[test_java.tar.gz](https://github.com/alibaba/GraphScope/files/14535781/test_java.tar.gz)
**Describe the bug**
I was verifying the process of a Java custom algorithm. Using the official graphscope-dev image, I compiled the Traverse code from the 0.26.0 version of grape-demo and successfully created a jar package. However, an error occurred when running it.

**To Reproduce**
1. Download attach file: test_java.tar.gz
2. prepare graphscope-dev docker
3. mvn clean install
4. run test.py

**output message**

![image](https://github.com/alibaba/GraphScope/assets/17872527/17d2fe86-1791-4d4c-b10f-3c7057f6a078)

**Environment (please complete the following information):**
 - GraphScope version: [0.26.0]
 - OS: [Linux--graphscope-dev:latest]

**Additional context**

**Comment by zhanglei1949** [comment]
Thanks for using GraphScope Analytical Java! Let me try to reproduce the problem.
