### ISSUE TITLE
[BUG] Some problems of Interactive adminService interface

### ISSUE THREAD

**Issue by lidongze0629** [alibaba/GraphScope#3663]
**Describe the bug**
- `DELETE /v1/graph/{graph_name}` failed
- `POST /v1/service/start` start service on a non-data-loaded graph faield
![截屏2024-03-26 17 41 34](https://github.com/alibaba/GraphScope/assets/23491543/f491ebce-8b51-4865-a24c-58fcf17da6ae)
- create dataloading job failed
![截屏2024-03-26 17 48 35](https://github.com/alibaba/GraphScope/assets/23491543/4339d075-e577-42a1-a9ce-4b1071847ece)
- `GET /api/v1/graph/modern_graph/procedure` missing `query` field
```
[
  {
    "bound_graph": "modern_graph",
    "description": "xxxx",
    "enable": true,
    "name": "p1",
    "returns": [
      {
        "name": "id",
        "type": "LONG"
      },
      {
        "name": "name",
        "type": "STRING"
      }
    ],
    "runnable": false
  }
]
```

**Comment by zhanglei1949** [comment]
Closed since fixed.
