### ISSUE TITLE
[BUG] 用Loader加载S3协议时候，出现TypeError: __init__() got an unexpected keyword argument 'filetype'错误

### ISSUE THREAD

**Issue by colinguozizhong** [alibaba/GraphScope#3682]
**Describe the bug**
我希望通过Loader能加载到minio的文件，所以我尝试使用s3去加载，但是总是有TypeError: __init__() got an unexpected keyword argument 'filetype'错误

**Screenshots**
![image](https://github.com/alibaba/GraphScope/assets/2684252/83a72b96-5445-465e-99e4-b74b9beb1a7d)

![image](https://github.com/alibaba/GraphScope/assets/2684252/1c3ccc48-d172-421d-86d0-098e135a1a44)

**Environment (please complete the following information):**
 - GraphScope version: [v0.24.0]
 - OS: [macOS]
 - Version [14]

**Additional context**
另外，macOS m芯片的执行pip install graphscope为啥是0.24.0，啥时候能拉到最新的0.26.0

**Comment by siyuan0322** [comment]
https://github.com/alibaba/GraphScope/blob/b2db3bd31cdb26d3f6fb5812540cc269879f9f0f/python/graphscope/framework/loader.py#L155
你是本地安装的是么，在本地找到这个文件把这一行去掉吧。这里有点问题，等下会交commit fix。

M芯片的wheel包0.27.0我们会发布上去
