### ISSUE TITLE
[Demo] the demo site can't be accessed

### ISSUE THREAD

**Issue by chi-gao** [alibaba/GraphScope#3748]
**Describe the bug**
hi, there. I'm new to here. and when I try to learn from the demo site. I found the [demo site](https://try.graphscope.app/) which can't be visited. Are there any other online websites or demo projects that I can learn from?
![image](https://github.com/alibaba/GraphScope/assets/24784430/1de8a939-06c3-446a-87f4-b7d76efe144b)

**Comment by lidongze0629** [comment]
@chi-gao Thanks for reporting this problem. Currently, GraphScope Jupyterhhub lacks maintenance. We will fix it as soon as possible. Instead, you can try GraphScope through [google colab](https://colab.research.google.com/).

Useful link:
- https://github.com/alibaba/GraphScope/tree/main/tutorials

**Comment by chi-gao** [comment]
thank you very much.
