### ISSUE TITLE
[BUG] Unexpected alias maintenance in the new GOpt-based compilation stack

### ISSUE THREAD

**Issue by BingqingLyu** [alibaba/GraphScope#3792]
**Describe the bug**
In the new GOpt-based compilation stack, there exist some bugs in alias maintenance.

For example, on modern graph:
```
gremlin> g.V(1).outE("knows").as("here").has("weight", 1.0d).as("fake").inV().has("name", "josh").select("here")
{alias=here} not found; expected aliases are: [fake, _]
```
This is not as expected.

Another case, though is not occurred by alias maintenance, is:
```
gremlin> g.V().select("a").count()
{alias=a} not found; expected aliases are: [_]
```
while the expected output is "0".

**Comment by shirly121** [comment]
Compared to Gremlin's native implementation, we have type inference functionality, and we will directly throw an error for non-existent aliases.
