### ISSUE TITLE
Launch the server successfully, but the client cannot reach the server port

### ISSUE THREAD

**Issue by heiseon** [alibaba/GraphScope#385]
I launch the server following by official docs (scripts/prepare_env.sh) successfully.
But in the other host which install client environment cannot connect to the server port.

How do I find server port.
In server host I use " kind get kubeconfig" , I can hold the ip and port.
where am I wrong?

**Environment (please complete the following information):**
 - GraphScope version: v0.4.1
 - OS: Red hat
 - Version 7
 - Kubernetes Version latest

**Comment by acezen** [comment]
seems is not an issue, move to discussion.
