### ISSUE TITLE
[BUG] dingtalk is out of date

### ISSUE THREAD

**Issue by co63oc** [alibaba/GraphScope#3952]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
https://github.com/alibaba/GraphScope/pull/3951

![image](https://github.com/alibaba/GraphScope/assets/4617245/fe19d606-b4b0-49ee-81b1-551276511c10)
![image](https://github.com/alibaba/GraphScope/assets/4617245/d702a638-9e98-4735-89e8-66dfacfbc6f3)

**Environment (please complete the following information):**
 - GraphScope version: [e.g., v0.1, v0.2.2, master]
 - OS: [e.g. macOS, Linux]
 - Version [e.g. 10.15]
 - Kubernetes Version [e.g., 1.19]

**Additional context**

**Comment by siyuan0322** [comment]
Thanks! I have submitted a PR to update the link.
