### ISSUE TITLE
[BUG] Fail to run interactive: illegal instructions

### ISSUE THREAD

**Issue by zhanglei1949** [alibaba/GraphScope#4050]
System info
```text
Linux ip-172-31-37-103 6.5.0-1014-aws #14~22.04.1-Ubuntu SMP Thu Feb 15 15:27:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

It is so strage
<img width="1440" alt="截屏2024-07-16 14 40 59" src="https://github.com/user-attachments/assets/06e887d8-57ac-465b-9eb5-3bf28bc6d9f2">

**Comment by lidongze0629** [comment]
Similar problem when running Interactive image on MacOS(M2);

![截屏2024-08-14 14 48 58](https://github.com/user-attachments/assets/9e20a36f-45f1-4ca6-b9c0-77c708d57688)

**details**
- The image was built on linux arm64 machine, and it seems to work fine on a linux arm64 machine `Linux 5.10.134-16.3.al8.aarch64 #1 SMP Tue Mar 26 18:51:35 CST 2024 aarch64 aarch64 aarch64 GNU/Linux`
- MacOS: `Darwin 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:23 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6020 arm64`
