### ISSUE TITLE
feat (interactive) : Expand Node Storage Capacity in Interactive

### ISSUE THREAD

**Issue by yqylh** [alibaba/GraphScope#4105]
When loading a graph in interactive, if we bulkload a certain number of nodes, only an additional 20% space is reserved for storing newly inserted nodes. 

If more nodes are inserted, it fills up. For example, in the current testing of the interactive SDK with the modern graph, the person has only four nodes, and at most, only one more node can be inserted. 

It might be necessary to consider an expansion mechanism or initially have a strategy to store more.

**Comment by zhanglei1949** [comment]
Maybe we should increase the minimum vertex capactiy.
