### ISSUE TITLE
Add experimental test section in CI

### ISSUE THREAD

**Issue by siyuan0322** [alibaba/GraphScope#414]
We will reserve a permanent test step in CI for experimental features.
Once the experimental feature becomes stable, we move the relevant tests to other normal test steps.
At the same time, other experimental features may come in the codebase.

**Comment by yecol** [comment]
For CI, it is a just a matrix with experimental ON/OFF?

**Comment by siyuan0322** [comment]
For CI yes, my understanding is this is more like to establish a workflow mindset, like how to control the experimental flag, for c++, java, as well as rust.

**Comment by siyuan0322** [comment]
Closed due to the decision is not adding experimental flags in compile phase.
