### ISSUE TITLE
rapidjson v.s. nlohmannjson

### ISSUE THREAD

**Issue by yecol** [alibaba/GraphScope#4143]
For the same purpose, it is very wired to use two different json libraries in a single repo.

@zhanglei1949, as the one introducing the second json lib, you are obligated to compare the two libs and:
- either give strong support to unified to nlohmann json, and change all `rapidjson` usage.
- or unified to use rapidjson.

P.S. I will add a CI or post-commit hook to ask every PR explicitly to declare when introducing new third-party dependencies.

**Comment by zhanglei1949** [comment]
I find nlohmann json easy to use, but rapidjson offers better performance. We should consider switching to rapidjson.

**Comment by zhanglei1949** [comment]
Closed since resolved.
