### ISSUE TITLE
The statistics returned from call `gs.procedure.meta.statistics()` are not correct

### ISSUE THREAD

**Issue by longbinlai** [alibaba/GraphScope#4225]
As shown in the following figure: 

![lQLPJxMywdzL79vNA17NBauw2ngNrpfjxYQGytPkLWiPAA_1451_862](https://github.com/user-attachments/assets/fc44894d-19ef-4267-8b7b-4583031e3303)

**Comment by zhanglei1949** [comment]
It maybe the bug on engine side, let me check.
