### ISSUE TITLE
Fully Unicode support

### ISSUE THREAD

**Issue by siyuan0322** [alibaba/GraphScope#424]
To support Unicode characters in GraphScope.

- [x] Unicode character as label name, such as ‘人物'
- [x] Unicode character as property name, such as '年龄'
- [x] Unicode character in data path, such as '/home/边文件'
- [x] Unicode character in property value.

Add more case if you find one.

**Comment by sighingnow** [comment]
And Unicode character in property value as well.

**Comment by sighingnow** [comment]
> And Unicode character in property value as well.

Especially when it is used as "OID".

**Comment by siyuan0322** [comment]
Fixed in upstream v6d-io/v6d#353
