### ISSUE TITLE
[BUG] GraphScope Interactive Engine always restarts with default graph

### ISSUE THREAD

**Issue by pomelo-nwu** [alibaba/GraphScope#4253]
**Describe the bug**
as titled

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - GraphScope version: [e.g., v0.1, v0.2.2, master]
 - OS: [e.g. macOS, Linux]
 - Version [e.g. 10.15]
 - Kubernetes Version [e.g., 1.19]

**Additional context**

**Comment by zhanglei1949** [comment]
How to reproduce the bug:
Deploy the service with docker.

1. Create a new graph.
2. Switch service the graph to the new graph
3. Stop the container and restart the container.
4. Now the response of `GET /v1/service/status` is the new graph, but actually running on the default graph.
