### ISSUE TITLE
doc(interactive): Add documentation for SDK implementation

### ISSUE THREAD

**Issue by zhanglei1949** [alibaba/GraphScope#4263]
Currently Interactive SDK's Documentation has no introduction for the Implementation code such as `Result.py`.

**Comment by longbinlai** [comment]
In addition, all returned data structure from response has not been introduced. For example, 
```
resp = sess.create_graph(create_graph_request)
assert resp.is_ok()
return resp.get_value().graph_id
```

We do not know what resp.get_value() looks like, what data field can be accessed.
