### ISSUE TITLE
enrich the build scripts: support deploy local on mac

### ISSUE THREAD

**Issue by acezen** [alibaba/GraphScope#429]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sighingnow** [comment]
Note to use python 3.9 on Mac to test the basic functionality.

Including some networkx test cases as well.

**Comment by sighingnow** [comment]
@lidongze0629 Could you please add a test case, which run some GAE apps, as well as networkx apps on _local_ environment?
