### ISSUE TITLE
Enrich the documentation of GraphScope developer guide.

### ISSUE THREAD

**Issue by lidongze0629** [alibaba/GraphScope#430]
TBF.

**Comment by acezen** [comment]
some:
- add a notice that GraphScope can't be build and run on windows.  if on MacOS, can't not use learning engine.
- add an example to run GraphScope on hosts type (after deployment on local), this is for developer.

**Comment by lidongze0629** [comment]
Some good cases of the developer guide (Help to install and setup GraphScope from source code step by step.)

- https://apache.github.io/systemds/site/install.html
- https://giraph.apache.org/quick_start.html

**Comment by lidongze0629** [comment]
Also need to update [GraphScope Deployment Doc](https://graphscope.io/docs/deployment.html#deployment-on-local) and [Developer Guide](https://graphscope.io/docs/developer_guide.html#)
