### ISSUE TITLE
[BUG] Mac Pip install V0.29.0 not fund

### ISSUE THREAD

**Issue by JackyYangPassion** [alibaba/GraphScope#4303]
**Describe the bug**
python3 -m pip install graphscope==0.29.0 -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host=mirrors.aliyun.com

ERROR LOG
```
ERROR: Could not find a version that satisfies the requirement graphscope==0.29.0 (from versions: 0.20.0, 0.22.0, 0.24.0)
ERROR: No matching distribution found for graphscope==0.29.0
```

**Environment (please complete the following information):**
 - GraphScope version: [e.g., v0.1, v0.2.2, master]
 - OS: mac
- Python:3.9.6

**Additional context**

**Comment by subhash-angelone** [comment]
+1
