### ISSUE TITLE
[BUG] runtime interface count edge num failed

### ISSUE THREAD

**Issue by Mr-Xzz** [alibaba/GraphScope#4348]
![image](https://github.com/user-attachments/assets/1fe2ad8c-c246-4551-b551-ed3f9e77223d)
![image](https://github.com/user-attachments/assets/977aaba3-0b86-496e-9044-32e8e11703f3)

Query:

`MATCH (a)-[e]-(b) return count(e);`

or

`MATCH ()-[e]-() return count(e);`

graph schema data: @Mr-Xzz

**Comment by zhanglei1949** [comment]
It turns out to be the problem of supporting multiple edge properties in our runtime module. This issue will be closed, and future discussion and progress will be tracked here: #4349
