### ISSUE TITLE
bug (interactive): error querying the whole graph on the latest graphy dataset

### ISSUE THREAD

**Issue by longbinlai** [alibaba/GraphScope#4365]
After loading the latest graphy dataset: paper_reading_1211, and try to query:
```
MATCH (a)-[e]->(b) RETURNS a, e, b
```
Interactive returns error: 
String field 'common.Value.str' contains invalid UTF-8 data. 

This might be the issue of the data, but Interactive must be able to handle none UTF-8 data.

**Comment by zhanglei1949** [comment]
It seems that there is a invalid utf-8 char in the raw data. But in the bulk loading process, we didn't check whether the char is a valid utf-8 char.
