### ISSUE TITLE
Add a restart test of graphscope store in CI.

### ISSUE THREAD

**Issue by siyuan0322** [alibaba/GraphScope#470]
The persistent store service should have the ability to restart on previous PersistentVolume and retain all the schema and data.
Add a CI step to verify that.

**Comment by acezen** [comment]
try to add restart helm to ci, but it failed at `test_demo_after_restart` test case which use the previous PersistentVolume to query.  

relate action: https://github.com/alibaba/GraphScope/runs/3492932863?check_suite_focus=true

**Comment by acezen** [comment]
ci already add，restart failed issue move to #392
