### ISSUE TITLE
Compatibility of Python/Kubernetes/OS in GraphScope

### ISSUE THREAD

**Issue by doudoubobo** [alibaba/GraphScope#480]
Current version does not support python 3.9 due to the compatibility with NetworkX 2.5.

**Comment by sighingnow** [comment]
Cannot reproduce the failure with networkx 2.5.

I think it might be caused by using of lower version of networkx.

**Comment by sighingnow** [comment]
For conda users, pip install may won't truly upgrade their networkx installation.

**Comment by sighingnow** [comment]
Close as invalid, and more test cases will be added when resolve #479.
