### ISSUE TITLE
[BUG] graphscope.framework.errors.ConnectionError: connect   coordinator  timeout,grpc  connect    failed

### ISSUE THREAD

**Issue by yzjg** [alibaba/GraphScope#484]
**Describe the bug**
according  to  the  offical  document  to configure  the  argument,then   the  bug     throw  out,cann't  run  normally    

**Environment (please complete the following information):**
 - GraphScope version: 0.4.0
 - OS: centos7.7
 - Kubernetes Version  1.16.4

![image](https://user-images.githubusercontent.com/25189806/124693327-cd7ea800-df11-11eb-9864-3436da52a987.png)
![image](https://user-images.githubusercontent.com/25189806/124693341-d66f7980-df11-11eb-95fd-45ffed080151.png)
![image](https://user-images.githubusercontent.com/25189806/124693353-dc655a80-df11-11eb-9c7d-d285d03cbd8e.png)

**Comment by lidongze0629** [comment]
Closed and move to the discussion.

https://github.com/alibaba/GraphScope/discussions/485
