### ISSUE TITLE
Incorrect descriptions of some functions in document

### ISSUE THREAD

**Issue by doudoubobo** [alibaba/GraphScope#486]
For example, `Selector`, `get_inner_node`, `get_outer_node`

**Comment by siyuan0322** [comment]
- The selector part is a misunderstanding, who mistakenly regarded the syntax of selecting the result that was supposed to be the selecting the attribute.
- The node part is indeed not precisely reflected what the method does, has been fixed.

However, after a glance in the doc, there is still some room to refine, like the accuracy, syntax, and it's a little out of date, as well as the Chinese version.

**Comment by siyuan0322** [comment]
Maybe need another a few hours to go over the docs.
Leave this open for a few days.
