### ISSUE TITLE
[BUG] Building failed on Mac OS

### ISSUE THREAD

**Issue by alwaysdaylast** [alibaba/GraphScope#499]
**Describe the bug**

following the instructions on https://graphscope.io/docs/v0.1.2/zh/developer_guide.html#
I failed to build it as below

C02WT0G0HTDG:GraphScope alwaydaylast$ make graphscope

/Applications/Xcode.app/Contents/Developer/usr/bin/make -C /Users/alwaydaylast/dev/GraphScope//k8s/ graphscope VERSION=0.1.0
Makefile:6: WARNING: No docker user found, using graphscope
cd ../ && git submodule update --init
docker build --progress= \
				 --build-arg profile=release \
				 -t graphscope/graphscope:c3203acf \
				 --network=host \
				 -f /Users/alwaydaylast/dev/GraphScope/k8s//graphscope.Dockerfile ..
invalid value "" passed to --progress, valid values are: auto, plain, tty
make[1]: *** [graphscope] Error 1
make: *** [graphscope] Error 2

**Environment (please complete the following information):**
 - GraphScope version: [ master]
 - OS: [ MacOS]
 - Version [11.4]

any advice will be appreciated, thanks in advance.

**Comment by sighingnow** [comment]
Hi @alwaysdaylast,

Actually, we have a typo in the Makefile. It has been fixed on main and you may need to update the codebase with `git pull` and try again.

**Comment by alwaysdaylast** [comment]
> Hi @alwaysdaylast,
> 
> Actually, we have a typo in the Makefile. It has been fixed on main and you may need to update the codebase with `git pull` and try again.

Great , it works now, many thanks to you!
