### ISSUE TITLE
Clean up dependencies of unused modules and features 

### ISSUE THREAD

**Issue by yecol** [alibaba/GraphScope#52]
clean up dependencies of unused modules to make the code base more concise.

**Comment by zhengpingq** [comment]
Update (on behalf of @shirly121):
- [X] Removed the following dependencies: `lombok`, `hadoop-client`, `jtar`, `kafka-clients`, `jgrapht-core` (except for its usage in the compiler).

TODOs:
- [ ] Remove dependency on `jgrapht-core` from the compiler;
- [ ] Remove dependency on `aliyun-java-sdk-graphcompute` from `maxgraph-tests` and `maxgraph-benchmark`;
- [ ] Discuss whether we need to remove `ZooKeeper`-dependency (from `maxgraph-common`, `maxgraph-coordinator` and `instance-manager`) as well.
