### ISSUE TITLE
Reduce the size of the image

### ISSUE THREAD

**Issue by yecol** [alibaba/GraphScope#522]
**Is your feature request related to a problem? Please describe.**
Reduce the image size.

**Describe the solution you'd like**
- following the instructions in the documentations, to build and produce an GraphScope image; report problems about the missed/unclear information in the documentation.
- reduce the size of the image, ideally less than 3GB (with cupid)
- profiling the space occupation, give a list for large ones for further optimization.

**Describe alternatives you've considered**

**Additional context**

**Comment by WyjAloneSmile** [comment]
This is the statistics of gsruntime image.
<img width="897" alt="image" src="https://user-images.githubusercontent.com/43229540/126954179-11dd9db6-03ff-4643-abe1-ae9c38954264.png">
In this data, image of GIE RUNTIME occupies nearly half of the space(1600MB).

**Comment by yecol** [comment]
Please provide detailed information. Thanks!
