### ISSUE TITLE
Migrate the rocks-db dependency of storage to a stable version

### ISSUE THREAD

**Issue by yecol** [alibaba/GraphScope#525]
This is a historical issue: the MaxGraph storage has depended on this wired version. While it is necessary to migrate to a stable version, I think we can do that by creating another issue.

_Originally posted by @longbinlai in https://github.com/alibaba/GraphScope/pull/521#discussion_r668403048_

**Comment by yecol** [comment]
hi @longbinlai , could you help to triage this issue to the right person~

**Comment by yecol** [comment]
latest update:

Please address this, @GoldenLeaves 

![image](https://user-images.githubusercontent.com/426463/144375461-5d6033f1-8b0e-43b1-a843-8bd7efbd1829.png)

**Comment by GoldenLeaves** [comment]
> latest update:
> 
> Please address this, @GoldenLeaves
> 
> ![image](https://user-images.githubusercontent.com/426463/144375461-5d6033f1-8b0e-43b1-a843-8bd7efbd1829.png)

oka! my related pr for rust-rocksdb has been merged, and we can switch to the rust-rocksdb repo dependency. but it does not corresponds to a statble version, so we may just change our  dependecies as:
```
[dependencies.rocksdb]
git = "https://github.com/rust-rocksdb/rust-rocksdb.git"
rev = "db407cd05081230fca5755c3a38c5944650f3bd2"
```
