### ISSUE TITLE
Free the memory of graphs and context when a test suite is done in ci

### ISSUE THREAD

**Issue by acezen** [alibaba/GraphScope#528]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sighingnow** [comment]
Could we renew a session for every test suite or every model?

**Comment by acezen** [comment]
> Could we renew a session for every test suite or every model?

That would be to many 'pytest' in ci.yaml

**Comment by siyuan0322** [comment]
> > Could we renew a session for every test suite or every model?
> 
> That would be too many 'pytest' in ci.yaml

This could be done by narrowing the scope of the `session` fixture.

**Comment by acezen** [comment]
fix the ci test oom by narrowing the scope of `graphscope_session` to `module`. The release of context is move to #
