### ISSUE TITLE
Exclude the generated proto files in the repo

### ISSUE THREAD

**Issue by yecol** [alibaba/GraphScope#535]
https://github.com/alibaba/GraphScope/blob/101ab6f3f19dfcaceb8f1ea5bbcd97420815668c/interactive_engine/src/api/sdk-common/src/main/generated/com/alibaba/maxgraph/proto/AddIndexReq.java#L1

and the whole folder in `GraphScope/interactive_engine/src/api/sdk-common/src/main/generated/com/alibaba/maxgraph/proto`

the java code of proto files should be compile with maven, with the dep:

```
<dependency>
    <groupId>com.google.protobuf</groupId>
    <artifactId>protobuf-java</artifactId>
    <version>${protobuf.version}</version>
</dependency>
```

BTW, I found in many java repo, it seems that a common practice for the location of proto files is:

```
src/main/resources/protobuf/
# or
src/main/resources/proto/
```

**Comment by yecol** [comment]
btw, a single file `GraphScope/interactive_engine/src/api/sdk-common/src/main/generated/com/alibaba/maxgraph/Message.java` is 1.69M!

**Comment by yecol** [comment]
Known files to exclude:

/interactive_engine/src/api/sdk-common/src/main/generated/*
/interactive_engine/src/common/java/src/main/generated*

**Comment by tianliplus** [comment]
> Known files to exclude:
> 
> /interactive_engine/src/api/sdk-common/src/main/generated/*
> /interactive_engine/src/common/java/src/main/generated*
> /interactive_engine/src/common/rust/common/src/proto/mod.rs

Generated files are removed. `mod.rs` is required.
