### ISSUE TITLE
Provisioning k8s cluster on amazon/aliyun 

### ISSUE THREAD

**Issue by yecol** [alibaba/GraphScope#57]
Provisioning k8s cluster on amazon and aliyun, with configurations like `accessId` and `accessSecrets`.

**Comment by acezen** [comment]
- aliyun
wrap a class AliyunClient base GSClient of aliyun python sdk, provide  create_cluster,  deploy, delete_cluster.

ref: https://help.aliyun.com/document_detail/177423.html?spm=a2c4g.11186623.6.1501.6bbf123eJ18rBk

**Comment by acezen** [comment]
- aws

ref: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ecs.html

**Comment by sighingnow** [comment]
> * aliyun
>   wrap  AliyunClient class base on GSClient of aliyun python sdk, provide  create_cluster,  deploy, delete_cluster.
> 
> ref: https://help.aliyun.com/document_detail/177423.html?spm=a2c4g.11186623.6.1501.6bbf123eJ18rBk
> 
> * aws
> 
> ref: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ecs.html

For AWS, the kube config could be obtained via https://stackoverflow.com/a/54954302/5080177

**Comment by yecol** [comment]
I think we may need to add some parameters for the `session` for this task. Could you give a proposal here?

**Comment by acezen** [comment]
> I think we may need to add some parameters for the `session` for this task. Could you give a proposal here?

maybe add a **cluster_config** param to session.  we pass a json to the **cluster_config** param, it can include:
```python
{
     access_id_key,
     access_id_secret,
      region
}

**Comment by acezen** [comment]
> > I think we may need to add some parameters for the `session` for this task. Could you give a proposal here?
> 
> maybe add a **cluster_config** param to session. we pass a json to the **cluster_config** param, it can include:
> 
> ```python
> {
>      access_id_key,
>      access_id_secret,
>       region
> }
> ```

update:
we need four base parameters  ```cluster_type```, ```access_id_key```,  ```access_id_secret```, ```region``` to init a client, 
a ```cluster_config``` parameter to specify a config file of cluster to create.

**Comment by acezen** [comment]
aliyun cluster config file example:
```python
{
    "cluster_type":"Kubernetes",
    "name":"my-test-Kubernetes-cluster",
    "region_id":"cn-beijing",
    "disable_rollback":"true",
    "timeout_mins":"60",
    "kubernetes_version":"1.12.6-aliyun.1",
    "snat_entry":"true",
    "endpoint_public_access":"false",
    "cloud_monitor_flags":"false",
    "node_cidr_mask":"25",
    "proxy_mode":"iptables",
    "tags":[],
    "addons": [{"name": "flannel"},{"name": "aliyun-log-controller","config": "{\"sls_project_name\":\"k8s-log-c64f6eab6a1764d3dbee3dc2b9e41****\"}"},{"name": "nginx-ingress-controller", "config": "{\"IngressSlbNetworkType\":\"internet\"}"}],
    "node_port_range":"30000-32767",
    "login_password":"test****",
    "cpu_policy":"none",
    "master_count":"3",
    "master_vswitch_ids":["vsw-2ze48rkq464rsdts****","vsw-2ze48rkq464rsdts1****","vsw-2ze48rkq464rsdts1****"],
    "master_instance_types":["ecs.sn1.medium","ecs.sn1.medium","ecs.sn1.medium"],
    "master_system_disk_category":"cloud_efficiency",
    "master_system_disk_size":"40",
    "worker_instance_types":["ecs.sn2.3xlarge"],
    "num_of_nodes":"3",
    "worker_system_disk_category":"cloud_efficiency",
    "worker_system_disk_size":"120",
    "vpcid":"vpc-2zegvl5etah5requ0****",
    "worker_vswitch_ids":["vsw-2ze48rkq464rsdts****"],
    "container_cidr":"172.20.XX.XX/16",
    "service_cidr":"172.21.XX.XX/20",
    "worker_data_disks": [{"category": "cloud_ssd", "size": 500}],
    "master_data_disks": [{"category": "cloud_ssd", "size": 500}],
    "taints":[{"key": "special", "value": "true", "effect": "NoSchedule"}],
}
```
