### ISSUE TITLE
Integration with mars

### ISSUE THREAD

**Issue by yecol** [alibaba/GraphScope#58]
**Is your feature request related to a problem? Please describe.**

[mars](https://github.com/mars-project/mars) is a distributed tensor-based computation engine. The intermediate data/results of GraphScope in the format of dataframe should be enabled to process in mars, as a part of the workflow pipeline.

**Comment by power1628** [comment]
I wonder if we can build a graph engine on top of tensor engine like mars.

**Comment by power1628** [comment]
I wonder why not build a graph engine on top of a dataflow engine like mars. What are the cons and pros?

**Comment by acezen** [comment]
proposal: (the key is mars must in the same container with vineyard)
- integrate with helm, this would be ref to #161 
- create a new image that contain mars, and add a launch mars engine in coordinator. (that would be similar with learning engine)
