### ISSUE TITLE
[BUG] graphscope.framework.errors.GRPCError: 'RPC failed, the engine might have crashed: rpc create_interactive_engine: failed with error code StatusCode.UNKNOWN, details: Exception calling application: <urlopen error [Errno 111] Connection refused>'

### ISSUE THREAD

**Issue by 346057177** [alibaba/GraphScope#619]
**Describe the bug**

graphscope.framework.errors.GRPCError: 'RPC failed, the engine might have crashed: rpc create_interactive_engine: failed with error code StatusCode.UNKNOWN, details: Exception calling application: <urlopen error [Errno 111] Connection refused>'
**To Reproduce**

**Steps to reproduce the behavior:**
import os
import graphscope
from graphscope.framework.graph import Graph
from graphscope.framework.loader import Loader
import vineyard
graphscope.set_option(show_log=True)  # enable logging
graphscope.set_option(initializing_interactive_engine=False)
sess = graphscope.session()  # create a session
print(sess)
graph = sess.g()
print(graph)
interactive = sess.gremlin(graph)
print(interactive)

**Expected behavior**
graphscope session should be able to interact with GIE server .

**Screenshots**
I0729 14:14:31.375777    84 grape_instance.cc:110] Loading graph, graph name: graph_a37JncCH, graph type: ArrowFragment, type sig: e33529e80839a2064a804ce453c761a9483aa7ab775bcfddc1a1f9da63dcb521
I0729 14:14:31.372226    89 grape_instance.cc:110] Loading graph, graph name: graph_a37JncCH, graph type: ArrowFragment, type sig: e33529e80839a2064a804ce453c761a9483aa7ab775bcfddc1a1f9da63dcb521
I0729 14:14:32.171826    84 property_graph_frame.cc:107] [worker-1] loaded graph to vineyard ...
I0729 14:14:32.180032    89 property_graph_frame.cc:107] [worker-0] loaded graph to vineyard ...
graphscope.Graph
ARROW_PROPERTY

Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/graphscope/client/rpc.py", line 47, in with_grpc_catch
    return fn(*args, **kwargs)
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/graphscope/client/rpc.py", line 169, in create_interactive_engine
    response = self._stub.CreateInteractiveInstance(request)
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: <urlopen error [Errno 111] Connection refused>"
	debug_error_string = "{"created":"@1627539272.263514146","description":"Error received from peer ipv4:10.15.18.10:31281","file":"src/core/lib/surface/call.cc","file_line":1066,"grpc_message":"Exception calling application: <urlopen error [Errno 111] Connection refused>","grpc_status":2}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/graphscope/client/session.py", line 1135, in gremlin
    engine_params=engine_params,
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/graphscope/client/rpc.py", line 54, in with_grpc_catch
    ) from exc
graphscope.framework.errors.GRPCError: 'RPC failed, the engine might have crashed: rpc create_interactive_engine: failed with error code StatusCode.UNKNOWN, details: Exception calling application: <urlopen error [Errno 111] Connection refused>'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 12, in <module>
    interactive = sess.gremlin(graph)
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/graphscope/client/utils.py", line 156, in wrapper
    return_value = func(*args, **kwargs)
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/graphscope/client/session.py", line 1140, in gremlin
    raise InteractiveEngineInternalError(str(e)) from e
graphscope.framework.errors.InteractiveEngineInternalError: "'RPC failed, the engine might have crashed: rpc create_interactive_engine: failed with error code StatusCode.UNKNOWN, details: Exception calling application: <urlopen error [Errno 111] Connection refused>'"
2021-07-29 14:14:33,525 [INFO][coordinator:635]: Coordinator close interactive instance with url[http://xx.xx.xx.xx:8080/instance/close?graphName=11355625130038992&podNameList=gs-engine-juyknj-284dr,gs-engine-juyknj-bz2gf&containerName=engine&waitingForDelete=False]
2021-07-29 14:14:33,528 [ERROR][coordinator:639]: Failed to close interactive instance: <urlopen error [Errno 111] Connection refused>
2021-07-29 14:14:33,528 [ERROR][coordinator:639]: Failed to close interactive instance: <urlopen error [Errno 111] Connection refused>

**Environment (please complete the following information):**
GraphScope version: 0.5.0
OS: Ubuntu 20.04.2 
Kubernetes Version v1.20.5
python3: version3.6.8

**Additional context**

**Comment by lidongze0629** [comment]
@346057177 , Thanks for interesting in GraphScope.  It looks like the endpoint in Urlopen is not correct. Try `export GRAPHSCOPE_PREFIX=/usr/local` before run test again.

**Comment by 346057177** [comment]
hi thanks for replying me.  we need to research graphscope and findout if it fits into our product with large graph data analysis requirement. 
after we tried export GRAPHSCOPE_PREFIX=/usr/local, the issue still persists.  we are running in local mode , pod with GIE are dynamically autocreated by container image, endpoint with port no. is also dynamically generated.

**Comment by lidongze0629** [comment]
@346057177 From the output logs, Is it correct for the host of  `http://xx.xx.xx.xx:8080`? 

> 2021-07-29 14:14:33,525 [INFO][coordinator:635]: Coordinator close interactive instance with url[http://xx.xx.xx.xx:8080/instance/close?graphName=11355625130038992&podNameList=gs-engine-juyknj-284dr,gs-engine-juyknj-bz2gf&containerName=engine&waitingForDelete=False]

**Comment by 346057177** [comment]
xx.xx.xx.xx:8080 is  not correct.   it's different from Engines' pod host ip list.   I am also puzzled where it comes from? How is generated?

**Comment by acezen** [comment]
> xx.xx.xx.xx:8080 is not correct. it's different from Engines' pod host ip list. I am also puzzled where it comes from? How is generated?

hi, @346057177 ,could you try again without the set_option command  `graphscope.set_option(initializing_interactive_engine=False)
`

**Comment by acezen** [comment]
@346057177 hi, Were you run the code in https://try.graphscope.app/ and get the error ?

**Comment by 346057177** [comment]
yes , demo got no error.   demo is  Container image "registry.cn-hongkong.aliyuncs.com/graphscope/graphscope:0.4.0" , we are using  Container image "registry.cn-hongkong.aliyuncs.com/graphscope/graphscope:0.5.0"

**Comment by acezen** [comment]
> yes , demo got no error. demo is Container image "registry.cn-hongkong.aliyuncs.com/graphscope/graphscope:0.4.0" , we are using Container image "registry.cn-hongkong.aliyuncs.com/graphscope/graphscope:0.5.0"

thanks for your reply, I will try to reproduce the error.

**Comment by acezen** [comment]
@346057177 hi, I try with graphscope 5.0 and image "registry.cn-hongkong.aliyuncs.com/graphscope/graphscope:0.5.0". run as expected.

**Comment by 346057177** [comment]
kubectl get ns
gs-syqqgi                 Active   8s


kubectl -n gs-syqqgi get pods
coordinator-rplroa-84b6cd8c6c-r68d4       0/1     Running   0          29s
gs-engine-rplroa-4dr2z                    2/2     Running   0          17s
gs-engine-rplroa-9xj5f                    2/2     Running   0          17s
gs-etcd-rplroa-0                          1/1     Running   0          17s
gs-graphmanager-rplroa-55768999dc-wstws   2/2     Running   0          23s

**Comment by acezen** [comment]
> kubectl get ns
> gs-syqqgi Active 8s
> 
> kubectl -n gs-syqqgi get pods
> coordinator-rplroa-84b6cd8c6c-r68d4 1/1 Running 0 2m24s
> gs-engine-rplroa-4dr2z 2/2 Running 0 2m12s
> gs-engine-rplroa-9xj5f 2/2 Running 0 2m12s
> gs-etcd-rplroa-0 1/1 Running 0 2m12s
> gs-graphmanager-rplroa-55768999dc-wstws 2/2 Running 0 2m18s
> pod-12595529519442291 2/2 Running 0 87s
> 
> between, what is your kube-config file when run image 0.5.0.

it seems your graphmanager pod is launch success, but can't connect it from coordinator. that's weird.

**Comment by 346057177** [comment]
we are using k8s v1.20.5  with rancher RKE cluster.

**Comment by acezen** [comment]
can't not reproduce with GraphScope 5.0 + k8s, seems its k8s environment problem, not GraphScope bug

**Comment by acezen** [comment]
close

**Comment by acezen** [comment]
already fixed by 0.6.0
