### ISSUE TITLE
Improve the compatibility of NetworkX

### ISSUE THREAD

**Issue by yecol** [alibaba/GraphScope#62]
Currently the compatibility of NetworkX API is in preview.
We will make it solid in these aspects:
- graph manipulations
- built-in algorithms for large graphs in the distributed setting

**Comment by acezen** [comment]
some tasks:
- [ ] clear up the code;
- [ ] check the api of base Graph/DiGraph class compatible to  NetworkX and revise.
- [ ] make project_to_simple as a hidden method like graphscope.Graph.
- [ ] refactor the transformation base the latest GraphScope graph.
- [ ] builtin algorithm and fall_back algorithm.

here just list some task immediately surfaced in mind, more need to add

**Comment by yecol** [comment]
break-down to detailed issues.
