### ISSUE TITLE
[BUG] Image pulling failed during helm install graphscope.

### ISSUE THREAD

**Issue by colinJiangxl** [alibaba/GraphScope#636]
**Describe the bug**
helm install failed 
**To Reproduce**
![image](https://user-images.githubusercontent.com/45786690/127801544-7e2e8509-e0c8-47bc-9c60-21a385af714e.png)
![image](https://user-images.githubusercontent.com/45786690/127801614-d8408452-4d1f-4e72-905e-773290be5565.png)

**Comment by lidongze0629** [comment]
@colinJiangxl，Try run `(sudo) docker pull zookeeper:3.4.14` on your Kubernetes nodes to check whether can connect to the dockerhub service. If not, you can pre-download the image and set the session's params `k8s_image_pull_policy='IfNotPresent'`

> k8s_image_pull_policy (str, optional) – Kubernetes image pull policy. Defaults to “IfNotPresent”.

**Comment by colinJiangxl** [comment]
> @colinJiangxl，Try run `(sudo) docker pull zookeeper:3.4.14` on your Kubernetes nodes to check whether can connect to the dockerhub service. If not, you can pre-download the image and set the session's params `k8s_image_pull_policy='IfNotPresent'`
> 
> > k8s_image_pull_policy (str, optional) – Kubernetes image pull policy. Defaults to “IfNotPresent”.

直接执行docker pull zookeeper:3.4.14可以下载zk到本地
![image](https://user-images.githubusercontent.com/45786690/127815453-a3d8f2e6-da25-40db-9a5c-4842f3507b3d.png)
