### ISSUE TITLE
"session.g()" filed

### ISSUE THREAD

**Issue by colinJiangxl** [alibaba/GraphScope#642]
**Describe the bug**
python version 3.7:
             run session.g() filed

**To Reproduce**

![image](https://user-images.githubusercontent.com/45786690/127950682-b35c7f98-09ff-44ca-8537-bacca77f3d6c.png)

**Comment by sighingnow** [comment]
As suggested by @siyuan0322, it is a bug in our networkx integration and the patch hasn't been released yet. For a workaround, could you please try to downgrade your networkx installation to `networkx==2.5.0`?

**Comment by sighingnow** [comment]
Already fixed by https://github.com/alibaba/GraphScope/pull/511, and will be included in our next release v0.6.0.

**Comment by colinJiangxl** [comment]
> Already fixed by #511, and will be included in our next release v0.6.0.

do you have other solution to use ,now

**Comment by sighingnow** [comment]
You could downgrade your networkx to v2.5.0, by

```bash
pip3 install networkx==2.5
```

**Comment by colinJiangxl** [comment]
> ```shell
> ```shell
> pip3 install networkx==2.5
> ```
> 
> 
![image](https://user-images.githubusercontent.com/45786690/127973967-e95dcfd4-14a3-48e8-9201-639283e58462.png)
![image](https://user-images.githubusercontent.com/45786690/127974034-c0b057ba-d64d-48bb-8d87-3f965ca1cca4.png)

>     
>       
>     
> 
>       
>     
> 
>     
>   
>       
> ```

**Comment by sighingnow** [comment]
I guess it is a out-of-memory issue. May I know the resources settings for launching the cluster, and the size of graph data?
