### ISSUE TITLE
memory allocation bug in maxgraph+v2 gremlin-test

### ISSUE THREAD

**Issue by tianliplus** [alibaba/GraphScope#653]
as titled

**Comment by tianliplus** [comment]
Known case:

1) g_V_hasLabelXpersonX_order_byXageX_skipX1X_valuesXnameX
2) g_V_hasLabelXpersonX_order_byXageX_valuesXnameX_skipX1X

**Comment by yecol** [comment]
deprecated GIE, migrating to GAIA.
