### ISSUE TITLE
Performance evaluation of apps and manipulations on dynamic graph

### ISSUE THREAD

**Issue by yecol** [alibaba/GraphScope#681]
As titled, we need to know the status of the performance of dynamic graphs.
using datagen-8_0-fb dataset and 4 workers, we are going to test:

>  app计算方面

> 取（SSSP或BFS），测试对比DynamicFragment和ArrowFragment在datagen-8_0-fb上的计算时间 `DT0` 和 `AT0`，作为baseline

> 图的增删改查

> 边的增加：载入99%的边，剩余的1%通过add_edges_from扩充，测试扩充时间；测试 app 计算时间 DT-1；
> 边的增加：载入80%的边，剩余的20%通过add_edges_from扩充，测试扩充时间；测试 app 计算时间 DT-20；
> 边的删除：载入全图，通过remove_edges_from删除1%的边，测试删除时间；
> 边的删除：载入全图，通过remove_edges_from删除20%的边，测试删除时间；
> 点的增加：载入全图，新增1%节点，测试时间；
> 点的增加：载入全图，新增20%节点，测试时间；
> 点的删除：载入全图，删除1%节点的时间；
> 点的删除：载入全图，删除20%节点的时间；
> 点边的修改：修改1%点和边数据的时间（分开测试）；
> 点边的修改：修改20%点和边数据的时间（分开测试）；
> 点边的查找：载入全图，查找某一特定点或边所需时间；

> 载图性能：

> 普通载图性能：（使用datagen-7_5-fb), 通过read_from_egelist接口载图，测试时间；
> 从grpahscope转化的时间：datagen-8_0-fb, 测试 **双向** 转化时间；

**Comment by acezen** [comment]
### computation on SSSP (8cpu, 64GB memory)
- arrow_fragment: 0.767024s
- dynamic_fragment:

**Comment by acezen** [comment]
### Load graph
- transformation (datagen_8-0-fb)
    - graphscope to nx: 881.60248s

**Comment by acezen** [comment]
### Graph CRUD
- 边的增加1%: 
- 边的增加20%：

**Comment by acezen** [comment]
duplicated with #999, close this.
