### ISSUE TITLE
Print logs/hints about what we are doing at the different stages when launching a session

### ISSUE THREAD

**Issue by sighingnow** [alibaba/GraphScope#7]
**Is your feature request related to a problem? Please describe.**

The logs is still doesn't every helpful when error occurs. Could we print something like (when `show_logs=True`):

```
Launching coordinator...
Coordinator service is ready.
Launching graphscope engines... (or, `Waiting graphscope engines....`)
Graphscope engines are ready.
```

I mean, we should let user know what we are doing or waiting for, in a detailed manner, when `show_logs` is `True`.

**Additional context**

I just think log in comments https://github.com/alibaba/GraphScope/issues/3#issuecomment-747198036 is quite confusing. The word "ready" combined with no extra logs deliver a sense of "we are ready", but actually things are not ready, and users are confused about what they are waiting for and why it doesn't return or raise.

**Comment by yecol** [comment]
When addressing this, please also fix #10 .
