### ISSUE TITLE
[bug] Can multiple executors running on the same vineyard ? 

### ISSUE THREAD

**Issue by lidongze0629** [alibaba/GraphScope#701]
**Is your feature request related to a problem? Please describe.**

The gremlin results are redundancy and repetitive when multiple executors running on the same vineyard.

**Comment by sighingnow** [comment]
I think it has already been resolved in GAIA.

/cc @BingqingLyu

**Comment by yecol** [comment]
@BingqingLyu could you double check this?

**Comment by BingqingLyu** [comment]
> @BingqingLyu could you double check this?

Ok, we support both GAIA and MaxGraph on Vineyard for now. I'll check with Dongze for more details.

**Comment by BingqingLyu** [comment]
> @BingqingLyu could you double check this?

Both GAIA and MaxGraph support multiple executors on one storage (either Vineyard or V2). I think this may be a bug of MaxGraph on Vineyard.

**Comment by yecol** [comment]
Thanks, we will further investigate the bug.
