### ISSUE TITLE
The loading from edges behavior is diverged with the Doc. 

### ISSUE THREAD

**Issue by siyuan0322** [alibaba/GraphScope#727]
After we have eager, the `sess.g()` will immediately be evaluated and a graph will be created in the backend.
But out previous design is one can only load from edge files when the graph is not created, otherwise we cannot determine whether it's an *only load from edges* operation or an *Error* that one forgets to specify the vertex labels.

So currently the loading from edges cannot be achieved using `g = sess.g(); g = g.add_edges()`, we can only fallback to the `load_from` style, but the doc gives no hints about that.

We should 
- make the document consistent, and 
- find a way to enable loading from edges in `g = sess.g()` style, which may be achieved by eager optimization by combining steps.

The eager and lazy interoperation is very subtle, we should be very careful about that and keep the document updated whenever something changed.

**Comment by siyuan0322** [comment]
Reported by a user in antgroup, using graphscope-cupid package.

**Comment by siyuan0322** [comment]
I will take some time to look into this, hopefully can be fixed along release 0.8.0.

**Comment by sighingnow** [comment]
> I will take some time to look into this, hopefully can be fixed along release 0.8.0.

Should be 0.7.0?

**Comment by yecol** [comment]
`g.add_edges(add_vertex_if_not_exists=True|False)` , 

in case that users only provide an edge file, default set to False.

**Comment by sighingnow** [comment]
When adding is impossible, e.g., adding a type of edges with multiple different (src, dst) combination, we shouldn't fail with a strange exception and tedious traceback without useful information, we should, instead,

+ make it possible even very ineffcient, e.g., reloading the graph from scratch
+ or, tell users that they should use `Session.load_from(...)` for such cases, as a hint, or suggestion fix.

**Comment by sighingnow** [comment]
Related to #410 as well.
