### ISSUE TITLE
Use native GRPC context messages to return error.

### ISSUE THREAD

**Issue by siyuan0322** [alibaba/GraphScope#737]
Currently we use self-defined error codes between coordinator and client, coordinator and GAE, maybe we could adopt GRPC naive error handling method, which is also friendly to k8s error detecting mechanism https://kubernetes.io/blog/2018/10/01/health-checking-grpc-servers-on-kubernetes/

other resources:

https://grpc.io/docs/guides/error/
https://grpc.github.io/grpc/python/grpc.html#grpc.RpcError
https://stackoverflow.com/a/41028094

**Comment by yecol** [comment]
Let's improve the error handling and make them more informative. 
Avoid questions like this: https://github.com/alibaba/GraphScope/discussions/475

**Comment by siyuan0322** [comment]
Closed via #751
