### ISSUE TITLE
Organize the failing message of GAE

### ISSUE THREAD

**Issue by siyuan0322** [alibaba/GraphScope#739]
The GAE reports many code backtrace, compilation error directed to user, which is hard to identify where the true error resides.
Maybe we could first grab the message and do some processing, extracting and refining to be more user-friendly,
even better, we guide user how to fix them.

**Comment by yecol** [comment]
Logs from many workers are aggregated and streamed to the client for debugging. Won't fix if there is no appropriate proposal.
