### ISSUE TITLE
[BUG] BUG of Combining Copied with Merge operator in GAIA-X

### ISSUE THREAD

**Issue by youyangy** [alibaba/GraphScope#753]
**Describe the bug**
When Combining Copied with Merge operator in GAIA-X, this bug would be triggerd.

**To Reproduce**
```
let mut result = pegasus::run(conf, || {
        |input, output| {
            let src1 = input.input_from(0u32..1000)?;
            let (s1, s2) = src1.copied()?;
            let (s3, s4) = s1.copied()?;
            s2.merge(s4)?.count()?.sink_into(output)
        }
    })
    .expect("submit job failure");
```

ERROR	[reactor 1] [pegasus/src/data_plane/intra_thread.rs:107] [worker_0(5339012757023831333)]: ThreadPull#pull: fail to pull data as the push disconnected;
[worker_0(5339012757023831333)]: ChannelId { job_seq: 5339012757023831333, index: 2 }: drop 'ThreadPush' without close;

**Comment by bmmcq** [comment]
fixed in 95ec0256697f4e1cc104d180b5b5b62dca2e6cc8
