### ISSUE TITLE
Recompile graph/app libraries when necessary

### ISSUE THREAD

**Issue by siyuan0322** [alibaba/GraphScope#760]
We cached the app/graph libraries to speed up e2e time by eliminating the compilation time, but the caching may be out of date when the dependent **header** files are changed. 

We need to manually delete those caches, however we can try to compile that library and if there are no changes, the compilation will be very fast, if there are changes, then we can get a newly compiled latest library.

This optimization should located in compiling part in coordinator.

**Comment by sighingnow** [comment]
We could unconditionally run `cmake . && make` command. It nothing changed cmake has do smart cache for us. It changed, we got the new binary and then distribute it to workers.

**Comment by lidongze0629** [comment]
Close this issue cause we can't recompile libraries when running GraphScope with `pip install`. Some problems such as  permission denial will occur. In addition, the problem of cache expiration will only occur in local development. and recommend o delete it manually.
