### ISSUE TITLE
Distribute files across workers may fail.

### ISSUE THREAD

**Issue by siyuan0322** [alibaba/GraphScope#761]
In coordinator setup we will `scp` or `kubectl cp` some files to workers, but this `scp` or `kubectl cp` operation itself may fail, and the failure is not handled, then the cluster will stuck until the timeout. Apart from that, no useful messages are returned to users.

We should handle that failure, return the error messages to user, and terminate the cluster.

**Comment by yecol** [comment]
maybe check the status of a command with `$?`

**Comment by lidongze0629** [comment]
Already fixed.

![截屏2021-11-19 下午3 21 20](https://user-images.githubusercontent.com/23491543/142581899-11283c17-b48a-4146-87c6-f9c1376fb681.png)
