### ISSUE TITLE
Support NetworkX functions on immutable fragments

### ISSUE THREAD

**Issue by yecol** [alibaba/GraphScope#763]
as titled.

Try to support functions listed on [docs](https://networkx.org/documentation/stable/reference/functions.html). 

Hence, for the functions doesn't change the graph, users can use them on both graph types.
for the rest of functions, give a hint like

```python
Error: function xxx cannot be invocated on immutable graph. 
You may want to convert the graph to mutable using to_nx_graph() before using xxx again. 
```

**Comment by acezen** [comment]
### The functions we can support on immutable graph
- degree
- degree_histogram (better to implement as an app)
- density
- info
- is_directed
- is_empty
- nodes
- number_of_nodes
- neighbors
- all_neighbors
- non_neighbors
- common_neighbors
- edges
- number_of_edges
- selfloop_edges
- number_of_selfloops
- nodes_with_selfloops （keep record the nodes with selfloop)
- is_weighted
- is_negatively_weighted
- get_node_attributes
- get_edge_attributes
- is_path (implement as an app)
- path_weight (implement as an app)
- is_frozen (always true)

### The functions we can not support on immutable graph
- to_directed
- to_undirected
- add_star
- add_path
- add_cycle
- set_node_attributes
- set_edge_attributes
- freeze


### To be determined
- create_empty_copy （use project ?)
- subgraph (deep copy ?)
- edge_subgraph (deep copy ?)
- subgraph_view (a view of original graph)
- restricted_view
- induced_subgraph
- reverse_view
- non_edges

**Comment by acezen** [comment]
## The api of NetworkX Graph [doc](https://networkx.org/documentation/stable/reference/classes/graph.html)
### The functions we can support on immutable graph
- Graph.nodes
- Graph.has_node
- Graph.edges
- Graph.has_edge
- Graph.get_edge_data
- Graph.neighbors
- Graph.adj
- Graph.adjacency
- Graph.order
- Graph.number_of_nodes
- Graph.degree
- Graph.size([weight])
- Graph.number_of_edges
- Graph.copy


### The functions we can not support on immutable graph
- Graph.add_node
- Graph.add_nodes_from
- Graph.remove_node
- Graph.add_edge
- Graph.add_edges_from
- Graph.add_weighted_edges_from
- Graph.remove_edge
- Graph.remove_edges_from
- Graph.update
- Graph.clear
- Graph.clear_edges

## To be determined
- Graph.to_undirected
- Graph.to_directed
- Graph.subgraph(nodes)
- Graph.edge_subgraph(edges)
- Graph.reverse

**Comment by acezen** [comment]
The [dynamic_fragment_reporter.h](https://github.com/alibaba/GraphScope/blob/main/analytical_engine/core/fragment/dynamic_fragment_reporter.h) is the implementation of most report functions of networkx. 
Considering to revise the `Reporter` to support immutable fragment.

**Comment by acezen** [comment]
The [dynamic_fragment_view.h](https://github.com/alibaba/GraphScope/blob/main/analytical_engine/core/fragment/dynamic_fragment_view.h) is the implementation of views of networkx graph.
Considering to support `ArrowPropertyFragment` in Viewer.
