### ISSUE TITLE
[BUG] Not support m1 chip？

### ISSUE THREAD

**Issue by lovefxyo** [alibaba/GraphScope#779]
**Describe the bug**
I tried to install this great project on my macbook pro m1 chip. But I found that something wrong happen. So what can I do to solve this question, or it doesn't work on m1 chip?

**To Reproduce**
Follow the guide. And when I tried to run 
`pip install -U -r requirements.txt`
This error comes:
ERROR: Could not find a version that satisfies the requirement vineyard (from versions: none)
ERROR: No matching distribution found for vineyard
I tried to build vineyard on my own.But I failed too. So what Can I do to fix it?

**Environment (please complete the following information):**
 - OS: [e.g. MacOS, Big Sur]

**Comment by sighingnow** [comment]
We will try if we could drop the `vineyard` dependency in our client code.

**Comment by lovefxyo** [comment]
> We will try if we could drop the `vineyard` dependency in our client code.

Thanks  a lot! I also tried to build vineyard  from source code. But I failed too. I think I should try on my ubuntu server temporarily.

**Comment by lovefxyo** [comment]
> The issue has been fixed on main and a release will but published tomorrow.

I successfully installed. But another problem happened.
 When I tried to run this code:
`import os
import graphscope

# assume we mount `~/test_data` to `/testingdata` in pods.
k8s_volumes = {
    "data": {
        "type": "hostPath",
        "field": {
            "path": os.path.expanduser("~/test_data/"),
            "type": "Directory"
        },
        "mounts": {
            "mountPath": "/testingdata"
        }
    }
}

sess = graphscope.session(k8s_volumes=k8s_volumes)`

This error happened:
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/var/folders/63/1xf4hfcj5rx4rmpgk5d6f9z40000gn/T/ipykernel_4068/1956453178.py in <module>
      1 import os
----> 2 import graphscope
      3 
      4 # assume we mount `~/test_data` to `/testingdata` in pods.
      5 k8s_volumes = {

~/Documents/GitHub/GraphScope/python/graphscope/__init__.py in <module>
     17 #
     18 
---> 19 from graphscope.analytical.app import *
     20 from graphscope.analytical.udf import declare
     21 from graphscope.analytical.udf.types import Vertex

~/Documents/GitHub/GraphScope/python/graphscope/analytical/app/__init__.py in <module>
     18 
     19 
---> 20 from graphscope.analytical.app.bfs import bfs
     21 from graphscope.analytical.app.bfs import property_bfs
     22 from graphscope.analytical.app.cdlp import cdlp

~/Documents/GitHub/GraphScope/python/graphscope/analytical/app/bfs.py in <module>
     18 
     19 
---> 20 from graphscope.framework.app import AppAssets
     21 from graphscope.framework.app import not_compatible_for
     22 from graphscope.framework.app import project_to_simple

~/Documents/GitHub/GraphScope/python/graphscope/framework/app.py in <module>
     28 
     29 import graphscope
---> 30 from graphscope.framework.context import create_context_node
     31 from graphscope.framework.dag import DAGNode
     32 from graphscope.framework.dag_utils import bind_app

~/Documents/GitHub/GraphScope/python/graphscope/framework/context.py in <module>
     23 from typing import Mapping
     24 
---> 25 from graphscope.client.session import get_session_by_id
     26 from graphscope.framework import dag_utils
     27 from graphscope.framework import utils

~/Documents/GitHub/GraphScope/python/graphscope/client/session.py in <module>
     58 from graphscope.framework.errors import K8sError
     59 from graphscope.framework.errors import check_argument
---> 60 from graphscope.framework.graph import Graph
     61 from graphscope.framework.graph import GraphDAGNode
     62 from graphscope.framework.operation import Operation

~/Documents/GitHub/GraphScope/python/graphscope/framework/graph.py in <module>
     36 from graphscope.config import GSConfig as gs_config
     37 from graphscope.framework import dag_utils
---> 38 from graphscope.framework import graph_utils
     39 from graphscope.framework import utils
     40 from graphscope.framework.dag import DAGNode

~/Documents/GitHub/GraphScope/python/graphscope/framework/graph_utils.py in <module>
     55         Sequence[np.ndarray],
     56         pd.DataFrame,
---> 57         vineyard.Object,
     58         vineyard.ObjectID,
     59         vineyard.ObjectName,

AttributeError: 'NoneType' object has no attribute 'Object'`

**Comment by lovefxyo** [comment]
I successfully install from source code on main.
But when I import graphscope.Something wrong happend.
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/var/folders/63/1xf4hfcj5rx4rmpgk5d6f9z40000gn/T/ipykernel_12718/998998640.py in <module>
----> 1 import graphscope

~/Documents/GitHub/GraphScope/python/graphscope/__init__.py in <module>
     17 #
     18 
---> 19 from graphscope.analytical.app import *
     20 from graphscope.analytical.udf import declare
     21 from graphscope.analytical.udf.types import Vertex

~/Documents/GitHub/GraphScope/python/graphscope/analytical/app/__init__.py in <module>
     18 
     19 
---> 20 from graphscope.analytical.app.bfs import bfs
     21 from graphscope.analytical.app.bfs import property_bfs
     22 from graphscope.analytical.app.cdlp import cdlp

~/Documents/GitHub/GraphScope/python/graphscope/analytical/app/bfs.py in <module>
     18 
     19 
---> 20 from graphscope.framework.app import AppAssets
     21 from graphscope.framework.app import not_compatible_for
     22 from graphscope.framework.app import project_to_simple

~/Documents/GitHub/GraphScope/python/graphscope/framework/app.py in <module>
     28 
     29 import graphscope
---> 30 from graphscope.framework.context import create_context_node
     31 from graphscope.framework.dag import DAGNode
     32 from graphscope.framework.dag_utils import bind_app

~/Documents/GitHub/GraphScope/python/graphscope/framework/context.py in <module>
     23 from typing import Mapping
     24 
---> 25 from graphscope.client.session import get_session_by_id
     26 from graphscope.framework import dag_utils
     27 from graphscope.framework import utils

~/Documents/GitHub/GraphScope/python/graphscope/client/session.py in <module>
     58 from graphscope.framework.errors import K8sError
     59 from graphscope.framework.errors import check_argument
---> 60 from graphscope.framework.graph import Graph
     61 from graphscope.framework.graph import GraphDAGNode
     62 from graphscope.framework.operation import Operation

~/Documents/GitHub/GraphScope/python/graphscope/framework/graph.py in <module>
     36 from graphscope.config import GSConfig as gs_config
     37 from graphscope.framework import dag_utils
---> 38 from graphscope.framework import graph_utils
     39 from graphscope.framework import utils
     40 from graphscope.framework.dag import DAGNode

~/Documents/GitHub/GraphScope/python/graphscope/framework/graph_utils.py in <module>
     41 
     42 if vineyard is not None:
---> 43     VineyardObjectTypes = (vineyard.Object, vineyard.ObjectID, vineyard.ObjectName)
     44     LoaderVariants = Union[
     45         Loader,

AttributeError: module 'vineyard' has no attribute 'Object'`

**Comment by sighingnow** [comment]
> 
> AttributeError: module 'vineyard' has no attribute 'Object'`

Seems that you have a "vineyard" folder somewhere and it is in your `$PYTHONPATH`? Or is there a `vineyard` directory in your current working directory?

**Comment by lovefxyo** [comment]
Thanks a lot for helping my such a long time!
I tried to create a new conda envs, and remove all my vineyard folder. 
And I tried to import graphscope. But another problem happend.
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/var/folders/63/1xf4hfcj5rx4rmpgk5d6f9z40000gn/T/ipykernel_44449/3399690379.py in <module>
----> 1 import graphscope

~/miniforge3/envs/graph/lib/python3.9/site-packages/graphscope-0.6.0-py3.9.egg/graphscope/__init__.py in <module>
     17 #
     18 
---> 19 from graphscope.analytical.app import *
     20 from graphscope.analytical.udf import declare
     21 from graphscope.analytical.udf.types import Vertex

~/miniforge3/envs/graph/lib/python3.9/site-packages/graphscope-0.6.0-py3.9.egg/graphscope/analytical/app/__init__.py in <module>
     18 
     19 
---> 20 from graphscope.analytical.app.bfs import bfs
     21 from graphscope.analytical.app.bfs import property_bfs
     22 from graphscope.analytical.app.cdlp import cdlp

~/miniforge3/envs/graph/lib/python3.9/site-packages/graphscope-0.6.0-py3.9.egg/graphscope/analytical/app/bfs.py in <module>
     18 
     19 
---> 20 from graphscope.framework.app import AppAssets
     21 from graphscope.framework.app import not_compatible_for
     22 from graphscope.framework.app import project_to_simple

~/miniforge3/envs/graph/lib/python3.9/site-packages/graphscope-0.6.0-py3.9.egg/graphscope/framework/app.py in <module>
     28 
     29 import graphscope
---> 30 from graphscope.framework.context import create_context_node
     31 from graphscope.framework.dag import DAGNode
     32 from graphscope.framework.dag_utils import bind_app

~/miniforge3/envs/graph/lib/python3.9/site-packages/graphscope-0.6.0-py3.9.egg/graphscope/framework/context.py in <module>
     23 from typing import Mapping
     24 
---> 25 from graphscope.client.session import get_session_by_id
     26 from graphscope.framework import dag_utils
     27 from graphscope.framework import utils

~/miniforge3/envs/graph/lib/python3.9/site-packages/graphscope-0.6.0-py3.9.egg/graphscope/client/session.py in <module>
     58 from graphscope.framework.errors import K8sError
     59 from graphscope.framework.errors import check_argument
---> 60 from graphscope.framework.graph import Graph
     61 from graphscope.framework.graph import GraphDAGNode
     62 from graphscope.framework.operation import Operation

~/miniforge3/envs/graph/lib/python3.9/site-packages/graphscope-0.6.0-py3.9.egg/graphscope/framework/graph.py in <module>
     36 from graphscope.config import GSConfig as gs_config
     37 from graphscope.framework import dag_utils
---> 38 from graphscope.framework import graph_utils
     39 from graphscope.framework import utils
     40 from graphscope.framework.dag import DAGNode

~/miniforge3/envs/graph/lib/python3.9/site-packages/graphscope-0.6.0-py3.9.egg/graphscope/framework/graph_utils.py in <module>
     55         Sequence[np.ndarray],
     56         pd.DataFrame,
---> 57         vineyard.Object,
     58         vineyard.ObjectID,
     59         vineyard.ObjectName,

AttributeError: 'NoneType' object has no attribute 'Object'`

I successfully build it on my ubuntu server, but m1 mac seems a little difficult, I tried really hard to find out, but I failed.

**Comment by sighingnow** [comment]
> AttributeError: 'NoneType' object has no attribute 'Object'`

Thanks for responsing so quickly! Indeed I found there's a bug in previous patch, and I believe #782 will fix that.

The pull request will be merged ASAP.
