### ISSUE TITLE
Proxy all traffic from client in coordinator.

### ISSUE THREAD

**Issue by lidongze0629** [alibaba/GraphScope#78]
**Is your feature request related to a problem? Please describe.**
Too many services exposed by GraphScope to the client in one instance, such as vineyard RPC service、gremlin service、GLE train server service. 

**Describe the solution you'd like**
It would be great if we can proxy all traffic from the client in one coordinator service.

**Refs**
Look forward to any helpful information.

**Comment by yecol** [comment]
@lidongze0629 reopen this issue.
