### ISSUE TITLE
Replace Gaia with GaiaX

### ISSUE THREAD

**Issue by longbinlai** [alibaba/GraphScope#808]
After the new version of GaiaX has completely merged into the main branch, which includes integrating the gremlin runtime and compiler into gaiax, and fix some known bugs. The old version of Gaia must be replaced at best.

**Comment by yecol** [comment]
Maybe with this replacement, GAIA could graduate from `/research/gaia` to `gaia` ?

**Comment by longbinlai** [comment]
We can expect that. But still depends on how stable gaia-x is. We have some known bugs and are working on fixing them.
