### ISSUE TITLE
Unify the logging output file location

### ISSUE THREAD

**Issue by yecol** [alibaba/GraphScope#815]
following the common practices, the logs should be output to `/var/log`

Let's unify the output logs to 
```
/var/log/graphscope/
# submodules can be gae/gaia/store/frontend/gie....
# e.g., 
/var/log/graphscope/SUBMODULE.log
/var/log/graphscope/SUBMODULE.err
```

**Comment by acezen** [comment]
FYI: https://stackoverflow.com/questions/36762016/best-practice-to-write-logs-in-var-log-from-a-python-script
