### ISSUE TITLE
Test and CI refinement

### ISSUE THREAD

**Issue by siyuan0322** [alibaba/GraphScope#865]
> No files were found with the provided path: /tmp/graphscope/. No artifacts will be uploaded.
- [x] The upload-artifact uploads nothing, please double check the logs location @lidongze0629 
> macOS-latest workflows will use macOS-11 soon. For more details, see https://github.com/actions/virtual-environments/issues/4060
- [ ] Pre-check the compatibility of the dependencies of macOS-11, (low pri, @acezen )
- [x] unify the test scripts for local, use `script/test.sh` as local and minimum test in CI, as we discussed. @lidongze0629 
- [x] clean up the files in `.github/workflows`, remove download-etcd.sh, install-minikube.sh, graphscope.Dockerfile @lidongze0629 
- [x] use `make` command we defined in makefile to build. @lidongze0629 
- [ ] cache the rust built dependencies @siyuan0322 
- [x] `manager` artifact. @lidongze0629 
- [x] Unify `k8s/graphscope.Dcokerfile`and `.github/workflow/graphscope.Dockerfile`

**Comment by lidongze0629** [comment]
- [ ] Unify `k8s/graphscope.Dcokerfile`and `.github/workflow/graphscope.Dockerfile`
