### ISSUE TITLE
有办法完全从源码安装么

### ISSUE THREAD

**Issue by bookug** [alibaba/GraphScope#885]
不需要docker，不需要网络，全部源码安装，有这种方法么？有详细的教程吗

**Comment by sighingnow** [comment]
可不可以介绍一下为什么会有这样的需求？

目前对于离线环境，可以把graphscope的docker image传到离线环境中。vineyard下一个版本 v0.8.0 会发布一个standalone 的pip包，可以不依赖运行环境的网络安装和运行。

**Comment by sighingnow** [comment]
> vineyard的docker我是可以下载的。但graphscope本身的镜像在哪下载？是在dockerhub上么

在 `registry.cn-hongkong.aliyuncs.com/graphscope/graphscope:0.7.0`
