### ISSUE TITLE
support running GraphScope on WSL

### ISSUE THREAD

**Issue by acezen** [alibaba/GraphScope#9]
**Is your feature request related to a problem? Please describe.**
- GraphScope not test on windows WSL.

**Describe the solution you'd like**
- make the whole demo runnable on WSL
- since minikube need systemd to start, WSL not support systemd init, consider use kind on WSL.

**Describe alternatives you've considered**

**Additional context**

**Comment by sighingnow** [comment]
Close ax fixed by #14.
