### ISSUE TITLE
[BUG] NullPointerException: failure during running GAIA frontend under higher version JDK (>=15)

### ISSUE THREAD

**Issue by lidongze0629** [alibaba/GraphScope#917]
**To Reproduce**
```python
def test_gaia(ogbn_small_script):
    s1 = graphscope.session(cluster_type="hosts", num_workers=1, enable_gaia=True)
    g1 = load_ogbn_mag(s1)
    interactive1 = s1.gremlin(g1)
    papers = interactive1.gaia().execute(ogbn_small_script).one()[0]
    assert papers == 1
```

![L1VzZXJzL2xpZG9uZ3plL0xpYnJhcnkvQXBwbGljYXRpb24gU3VwcG9ydC9EaW5nVGFsa01hYy8zMTcwNjk1ODVfdjIvSW1hZ2VGaWxlcy8xNjM1NDEwMDMxOTMxX+aIquWxjzIwMjEtMTAtMjgg5LiL5Y2INC4zMy4zNy5wbmc=](https://user-images.githubusercontent.com/23491543/139251046-2c32fb89-991d-481a-bb61-deef28aa5f9e.png)

**Comment by yecol** [comment]
APIs on GAIA is deprecated.
