### ISSUE TITLE
[BUG] Bug of SubTask in GAIA-X

### ISSUE THREAD

**Issue by BingqingLyu** [alibaba/GraphScope#931]
**Describe the bug**

BUG 1:
It seems that a subtask with no output result (of sub query) will occur the following  bug:

[worker_0(2)]: job(2) execute error: user error: kind(Unknown), caused by:125th subtask with scope [504] had been joined;
thread 'reactor 3' panicked at 'buf can't be none', GraphScope/research/gaia-x/pegasus/pegasus/src/communication/output/output.rs:500:22

BUG 2:
It seems that some specific query with subtask may occur the following bug:

thread 'reactor 1' panicked at 'batch of [1423] not consumed; ', GraphScope/research/gaia-x/pegasus/pegasus/src/communication/input/session.rs:174:13
[worker_2(3)]: IntraProcessPush#push: send data failure batch[[3135] len=1]
[worker_2(3)]: job(3) execute error: system error: kind(IOError), caused by:IOError(kind=System(NotConnected)),	occurred at: GraphScope/research/gaia-x/pegasus/pegasus/src/data_plane/intra_process.rs:43, ;
[worker_3(3)]: ChannelId { job_seq: 3, index: 11 }: drop 'ThreadPush' without close;

BUG 3:
It seems that some specific query with subtask may output inconsistent results.

BUG 4:
It seems that some specific query with subtask may get stuck

**To Reproduce**

To Reproduce Bug 1:

1. load any LDBC datasets in distributed using two servers;
2. run the following gremlin query:
```
g.V().hasLabel('PERSON').has('id',17592186044810) \
  .both('KNOWS').as('friend').in('HASCREATOR').hasLabel('COMMENT') \
  .filter(out('REPLYOF') \
          .hasLabel('POST') \
          .out('HASTAG') \
          .out('HASTYPE') \
          .has('name',eq('BasketballPlayer'))) \
  .count()
```

To Reproduce Bug 2:

1. load any LDBC datasets in distributed using two servers;
2. run the following gremlin query:
```
g.V().hasLabel('PERSON').has('id',17592186044810) \
  .both('KNOWS').as('friend').in('HASCREATOR').hasLabel('COMMENT') \
  .filter(out().out()) \
  .count()
```

To Reproduce Bug 3:

1. load any LDBC datasets in distributed using two servers;
2. run the following gremlin query:
```
g.V().hasLabel('PERSON').has('id',17592186044810) \
  .both('KNOWS').as('friend').in('HASCREATOR').hasLabel('COMMENT') \
  .filter(out('REPLYOF') \
          .hasLabel('POST') \
          .out('HASTAG')) \
  .count()
```

To Reproduce Bug 4:

1. load any LDBC datasets in distributed using two servers;
2. run the following gremlin query:
```
g.V().hasLabel('PERSON').has('id',17592186044810) \
  .both('KNOWS').as('friend').in('HASCREATOR').hasLabel('COMMENT') \
  .filter(out().has('name',eq('India'))) \
  .count()
```

**Screenshots**

Bug 1:
![image](https://user-images.githubusercontent.com/28559306/139795009-bf83231f-70ea-40cd-bb35-b4d7eb34b2a7.png)

Bug 2:
![image](https://user-images.githubusercontent.com/28559306/139793957-549edc68-fc24-411f-8508-b5fcefd8e43f.png)

Bug 3:
![image](https://user-images.githubusercontent.com/28559306/139795657-a0f02927-311a-4f93-aa88-df50c9968ae8.png)

**Additional context**

The common part in above queries is just for initial the input (i.e., `g.V().hasLabel('PERSON').has('id',17592186044810).both('KNOWS').as('friend').in('HASCREATOR').hasLabel('COMMENT')`), which can be ignored. 

The bugs are mainly related to subtasks, and different sub-query seems occur different problems.

For Bug 2,
I tried one-hop query in subtask, it does not occur the bug. The correct query is as follows:
```
g.V().hasLabel('PERSON').has('id',17592186044810) \
  .both('KNOWS').as('friend').in('HASCREATOR').hasLabel('COMMENT') \
  .filter(out()) \
  .count()
```

**Comment by longbinlai** [comment]
This issue should be refined as follows: (1) the query should be described via gaia codes; (2) it must be simplified/included as a gaia test case if it is actually an issue of gaia.
