### ISSUE TITLE
[BUG] GIE filter timeout

### ISSUE THREAD

**Issue by RongRongJi** [alibaba/GraphScope#963]
**Describe the bug**
When I use GIE to filter my graph, I found its query will timeout. My graph has 500,000 edges and 560,000 nodes, so I wonder if the size of graph affects its working.

**Screenshots**
![image](https://user-images.githubusercontent.com/32476024/140701201-379b7e81-a900-4291-a9d5-baf5db11e149.png)

**Environment (please complete the following information):**
 - GraphScope version: 0.6.0
 - OS: Ubuntu 16.04

**Comment by yecol** [comment]
Since GIE is deprecating, the issue wontfix in GIE and would be fixed in the new version of interactive engine GAIA.
