### ISSUE TITLE
[BUG] Failed to expose gremlin service deployed with Helm Charts

### ISSUE THREAD

**Issue by Hspix** [alibaba/GraphScope#992]
Python Client Code ：
import graphscope
from graphscope.dataset.ogbn_mag import load_ogbn_mag
k8s_volumes = {
    "data": {
        "type": "hostPath",
        "field": {
            "path": '/xx',
            "type": "Directory"
        },
        "mounts": {
            "mountPath": "/graphscope/data"
        }
    }
}
graphscope.set_option(show_log=True)
sess=graphscope.session(addr='ip:port',k8s_volumes=k8s_volumes)
graph = load_ogbn_mag(sess,'/graphscope/data/ogbn_mag_small')
interactive = sess.gremlin(graph)

====================================================================================
Log：

I1115 13:32:08.000000    56 /home/graphscope/gs/analytical_engine/core/grape_instance.cc:877] Registering Graph, graph type: ARROW_PROPERTY, Type sigature: e33529e80839a2064a804ce453c761a9483aa7ab775bcfddc1a1f9da63dcb521, lib path: /tmp/gs/builtin/e33529e80839a2064a804ce453c761a9483aa7ab775bcfddc1a1f9da63dcb521/libe33529e80839a2064a804ce453c761a9483aa7ab775bcfddc1a1f9da63dcb521.so
I1115 13:32:08.000000    56 /home/graphscope/gs/analytical_engine/core/grape_instance.cc:882] Graph already registered, signature is: e33529e80839a2064a804ce453c761a9483aa7ab775bcfddc1a1f9da63dcb521
I1115 13:32:08.000000    54 /home/graphscope/gs/analytical_engine/core/grape_instance.cc:877] Registering Graph, graph type: ARROW_PROPERTY, Type sigature: e33529e80839a2064a804ce453c761a9483aa7ab775bcfddc1a1f9da63dcb521, lib path: /tmp/gs/builtin/e33529e80839a2064a804ce453c761a9483aa7ab775bcfddc1a1f9da63dcb521/libe33529e80839a2064a804ce453c761a9483aa7ab775bcfddc1a1f9da63dcb521.so
I1115 13:32:08.000000    54 /home/graphscope/gs/analytical_engine/core/grape_instance.cc:882] Graph already registered, signature is: e33529e80839a2064a804ce453c761a9483aa7ab775bcfddc1a1f9da63dcb521
I1115 13:32:08.000000    56 /home/graphscope/gs/analytical_engine/core/grape_instance.cc:110] Loading graph, graph name: graph_Nyp5Fl8w, graph type: ArrowFragment, type sig: e33529e80839a2064a804ce453c761a9483aa7ab775bcfddc1a1f9da63dcb521
I1115 13:32:08.000000    54 /home/graphscope/gs/analytical_engine/core/grape_instance.cc:110] Loading graph, graph name: graph_Nyp5Fl8w, graph type: ArrowFragment, type sig: e33529e80839a2064a804ce453c761a9483aa7ab775bcfddc1a1f9da63dcb521
2021-11-15 13:32:27,118 [INFO][cluster:378]: Create GIE instance with command: /opt/graphscope/bin/giectl create_gremlin_instance_on_k8s /tmp/gs/graphscope-1636944463/session_rvgynxtm 15350678438740988 /tmp/graph_4DNRVR0S.json gs-engine-graphscope-1636944463-6mgn5,gs-engine-graphscope-1636944463-zgkft engine gaia.engine.port:40104 False graphscope-1636944463-coordinator
2021-11-15 05:32:59,551 [ERROR][rpc:226]: Runstep failed with code: INTERACTIVE_ENGINE_INTERNAL_ERROR, message: Error occurred during preprocessing, The traceback is: Traceback (most recent call last):
  File "/home/graphscope/.local/lib/python3.9/site-packages/gscoordinator/coordinator.py", line 738, in _create_interactive_instance
    raise RuntimeError(
RuntimeError: Error code: 1, message [2021-11-15T13:32:57+0800]: Launch interactive engine(executor) in per engine pod.
[2021-11-15T13:32:59+0800]: Expose gremlin server.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/graphscope/.local/lib/python3.9/site-packages/gscoordinator/coordinator.py", line 511, in RunStep
    self.run_on_interactive_engine(
  File "/home/graphscope/.local/lib/python3.9/site-packages/gscoordinator/coordinator.py", line 428, in run_on_interactive_engine
    op_result = self._create_interactive_instance(op)
  File "/home/graphscope/.local/lib/python3.9/site-packages/gscoordinator/coordinator.py", line 744, in _create_interactive_instance
    raise RuntimeError("Create interactive instance failed.") from e
RuntimeError: Create interactive instance failed.

====================================================================================
Environment：
 - GraphScope version ：0.8.0
 - OS: CentOS Linux 7
 - Docker Version ：18.09.4
 - Kubernetes Version ：1.22.1

**Comment by siyuan0322** [comment]
@lidongze0629 Hi, could you take some time to look into this? I'm not sure whether this usage: addr together with volumes will work?

**Comment by lidongze0629** [comment]
@Hspix The param`k8s_volumes` doesn't work together with `addr`, you can try

```python
import graphscope
graphscope.set_option(show_log=True)

k8s_volumes = {xxx}

sess = graphscope.session(k8s_volumes=k8s_volumes)
# Or appropriately increase some resources
# sess = graphscope.session(k8s_volumes=k8s_volumes, k8s_engine_cpu=2, k8s_engine_mem="2Gi")
graph = load_ogbn_mag(sess,'/graphscope/data/ogbn_mag_small')
interactive = sess.gremlin(graph)
```

**Comment by Hspix** [comment]
> @Hspix The param`k8s_volumes` doesn't work together with `addr`, you can try
> 
> ```python
> import graphscope
> graphscope.set_option(show_log=True)
> 
> k8s_volumes = {xxx}
> 
> sess = graphscope.session(k8s_volumes=k8s_volumes)
> # Or appropriately increase some resources
> # sess = graphscope.session(k8s_volumes=k8s_volumes, k8s_engine_cpu=2, k8s_engine_mem="2Gi")
> graph = load_ogbn_mag(sess,'/graphscope/data/ogbn_mag_small')
> interactive = sess.gremlin(graph)
> ```

**Comment by Hspix** [comment]
Addr points to my k8s cluster, so it can't be ignored.
Therefore, k8s_volumes uses defaults.
But, giectl also failed to exposes gremlin server.

In giectl shell script, this conmand:
**kubectl expose deployment ${coordinator_name} --name=mg-gremlin-${object_id} --port=${maxgraph_frontend_port} \
      --target-port=${maxgraph_frontend_port} --type=NodePort 1>/dev/null 2>&1**
executed by manual, the ${coordinator_name}, the value is equal to graphscope coordinator pod name , can't be found.

**Comment by lidongze0629** [comment]
@Hspix Thanks for reporting this problem, It's a bug to expose gremlin service which treats pod name `${coordinator_name}` as a deployment resource, I'll fix it as soon as possible before next release.
